{
armspace ={
buildoptions = {
"armoc",
"armosat",
"armofighter",
"armocan",
"armosolar",
"armobruiser",
"armotachyon",
},
},
armspacet3 = {
buildoptions = {
"armoc",
"armobomber",
"armohorizon",
"armokaiser",
"armoliberator",
},
},
armofighter = {
weapondefs = {
			lightlaser = {
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "0.05 0.05 1",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 220,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armocan = {
weapondefs = {
			Orbital_Cannon = {
				areaofeffect = 300,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = true,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 10,
				impulsefactor = 1,
				name = "Orbital Bombardment",
				tolerance = 65000,
				noselfdamage = true,
				range = 100,
				reloadtime = 10,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "KroGun1",
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 500,
					commanders = 166.6,
					shields = 100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_CANNON",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
armorocket = {
weapondefs = {
			orbital_rocket = {
				areaofeffect = 250,
				alwaysvisible = true,
				canattackground = false,
				collideenemy = true,
				cegtag = "cruisemissiletrail-tacnuke",
				cylindertargeting = 1,
				energypershot = 0,
				explosiongenerator = "custom:newnuketac",
				firestarter = 10,
				impulsefactor = 1.1,
				name = "Orbital Rocket System",
				range = 1350,
				reloadtime = 7.5,
				model = "cortronmissile.s3o",
				stockpile = false,
				soundhit = "xplomed4",
				soundstart = "mismed1",
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 4,
				startvelocity = 200,
				tracks = true,
				tolerance = 40000,
				turnrate = 40000,
				weaponacceleration = 1000,
				weapontimer = 1,
				weapontype = "StarburstLauncher",
				weaponvelocity = 2000,
				waterweapon = true,
				flighttime = 2.5,
				firesubmersed = true,
				burnblow = true,
				damage = {
					default = 1,
					space = 2600,
				},
				customparams = {
						overrange_distance = 1400,
						projectile_destruction_method = "explode",
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_ROCKET",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armobruiser = {
weapondefs = {
			space_emg = {
				collidefriendly = false,
				collidefeature = false,
				accuracy = 0,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				duration = 0.05,
				edgeeffectiveness = 0.5,
				energypershot = 2,
				explosiongenerator = "custom:genericshellexplosion-small",
				impulsefactor = 0,
				intensity = 5,
				name = "Space Laser Battery",
				noselfdamage = true,
				proximitypriority = 1,
				range = 700,
				reloadtime = 0.5,
				rgbcolor = "0.05 0.05 1",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				thickness = 5,
				tolerance = 40000,
				turret = true,
				weapontimer = 1,
				weapontype = "LaserCannon",
				weaponvelocity = 2400,
				cylindertargeting = 0.5,
				damage = {
					default = 75,
				},
			},
		},
		weapons = {
			[1] = {
				def = "SPACE_EMG",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
				maxangledif = 360,
			},
			[2] = {
				def = "SPACE_EMG",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
				maxangledif = 360,
			},
		},
},
armotachyon = {
weapondefs = {
oata = {
				areaofeffect = 16,
				avoidfeature = false,
				collidefriendly = false,
				avoidfriendly = false,
				canattackground = false,
				beamtime = 0.1,
				corethickness = 0.3,
				largebeamlaser = true,
				laserflaresize = 6.5,
				noselfdamage = true,
				explosiongenerator = "custom:laserhit-large-blue",
				name = "Orbital 2 orbital tachyon lance.",
				rgbcolor = "0 0 1",
				scrollspeed = 5,
				soundhitwet = "sizzle",
				soundstart = "annigun1",
				soundtrigger = 1,
				texture3 = "largebeam",
				thickness = 4.5,
				tilelength = 150,
				range = 1200,
				reloadtime = 7,
				minIntensity = 1,
				energypershot = 200,
				weapontype = "BeamLaser",
				tolerance = 10000,
				turret = true,
				weaponvelocity = 1400,
				cylindertargeting = 30,
				damage = {
					default = 1550,
				},
			},
		},
		weapons = {
			[1] = {
				def = "OATA",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				def = "",
				onlytargetcategory = "",
			},
		},
},
armokaiser = {
weapondefs = {
			plasma = {
				range = 1000,
				heightBoostFactor = 0,
				customparams = {
					engagementrange = 1200,
					carried_unit = "armodrone",     --Name of the unit spawned by this carrier unit.
					spawns_surface = "LAND SEA",
				},
			},
			aamissile = {
				avoidfriendly = false,
				collidefriendly = false,
				burst = 2,
				burstrate = 0.8,
				areaofeffect = 100,
				burnblow = true,
				cegtag = "missiletrailaa",
				collidefeature = false,
				flighttime = 2.5,
				name = "Battleship Missile",
				range = 1000,
				weaponacceleration = 300,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1200,
				cylindertargeting = 0.4,
				damage = {
					default = 1000,
					vtol = "500",
				},
			},
		},
		weapons = {
			[1] = {
				def = "AAMISSILE",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[2] = {
				def = "PLASMA",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armodrone = {
weapondefs = {
armodrone_missile = {
				areaofeffect = 40,
				avoidfeature = false,
				burnblow = true,
				canattackground = false,
				cegtag = "missiletrailsmall-red",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-catapult",
				firestarter = 70,
				flighttime = 2.5,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "catapultmissile.s3o",
				name = "Seeking Interplanetary Missile Launcher",
				noselfdamage = true,
				range = 500,
				reloadtime = 0.3,
				smoketrail = true,
				smokePeriod = 7,
				smoketime = 13,
				smokesize = 5.4,
				smokecolor = 0.95,
				smokeTrailCastShadow = false,
				castshadow = false,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "rockhvy2",
				startvelocity = 800,
				texture1 = "null",
				texture2 = "smoketrailaa3",
				tolerance = 20000,
				tracks = true,
				turnrate = 50000,
				turret = true,
				weaponacceleration = 500,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1200,
				cylindertargeting = 0.4,
				damage = {
					default = 9,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARMODRONE_MISSILE",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armoliberator = {
weapondefs = {
			heavyplasma = {
				alwaysVisible = true,
				accuracy = 100,
				areaofeffect = 200,
				collidefriendly = false,
				collidefeature = false,
				name = "Orbital Cannon Array",
				hightrajectory = 0,
				range = 2100,
				heightBoostFactor = 0,
				reloadtime = 2,
				damage = {
					default = 400,
					shields = 400,
				},
			},
			ferret_missile = {
				areaofeffect = 50,
				collidefriendly = false,
				collidefeature = false,
				burnblow = false,
				edgeeffectiveness = 0.15,
				flighttime = 3,
				name = "Pop-up rapid-fire o2a missile launcher",
				range = 1000,
				reloadtime = 2,
				damage = {
					default = 600,
				},
			},
		},
		weapons = {
			[1] = {
				def = "HEAVYPLASMA",
				onlytargetcategory = "SURFACE T4AIR",
			},
			[2] = {
				def = "HEAVYPLASMA",
				maindir = "0 0 1",
				maxangledif = 320,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[3] = {
				def = "HEAVYPLASMA",
				maindir = "0 0 1",
				maxangledif = 320,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[4] = {
				def = "HEAVYPLASMA",
				maindir = "-4 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[5] = {
				def = "HEAVYPLASMA",
				maindir = "4 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[6] = {
				maindir = "0 -1 -2",
				maxangledif = 270,
				def = "FERRET_MISSILE",
				onlytargetcategory = "VTOL SPACENOTOBJECT",
			},
			[7] = {
				def = "FERRET_MISSILE",
				onlytargetcategory = "VTOL SPACENOTOBJECT",
			},
		},
},
corspace = {
buildoptions = {
"corosat",
"coroc",
"corosolar",
"corofighter",
"corocan",
"corobruiser",
"coroheavy",
},
},
corspacet3 = {
buildoptions = {
"coroc",
"corobomber",
"corohunter",
"coroheatray",
"coroapoc",
},
},
coroheatray ={
weapondefs = {
			laser = {
				avoidneutral = false,
				collideneutral = false,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				areaofeffect = 72,
				avoidfriendly = false,
				energypershot = 350,
				range = 1200,
				minIntensity = 1,
				cylindertargeting = 10,
				heightmod = 0.1,
				damage = {
					default = 4000,
				},
			},
		},
		weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
		},
},
corofighter = {
weapondefs = {
			lightlaser = {
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "1 0.05 0.05",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 100,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
}{
corocan = {
weapondefs = {
Orbital_3Cannon = {
				areaofeffect = 200,
				avoidfeature = false,
				avoidfriendly = false, 
				burst = 3,
				burstrate= 0.1,
				cegtag = "arty-extraheavy",
				craterareaofeffect = 300,
				collidefriendly = false,
				collidefeature = false,
				canattackground = true,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-large",
				firestarter = 10,
				impulsefactor = 0.2,
				name = "Orbital Bombardment",
				tolerance = 50000,
				noselfdamage = true,
				range = 100,
				reloadtime = 11,
				soundhit = "xplonuk5",
				soundhitwet = "splslrg",
				soundstart = "KroGun1",
				sprayangle = 500,
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 200,
					commanders = 66.6,
					shields = 40,
				},
			},
},
		weapons = {
			[1] = {
				def = "ORBITAL_3CANNON",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
corobruiser = {
weapondefs = {
Inquisitor_Missiles = {
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 25,
				avoidfeature = false,
				avoidfriendly = false,
				burst = 2,
				burstrate = 0.2,
				burnblow = true,
				canattackground = false,
				cegtag = "missiletrailviper",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				edgeeffectiveness = 0.15,
				energypershot = 0,
				explosiongenerator = "custom:genericshellexplosion-tiny-aa",
				firestarter = 72,
				flighttime = 1.8,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "cormissile3fast.s3o",
				name = "Orbital Striker Missiles.",
				noselfdamage = true,
				range = 800,
				reloadtime = 1,
				smoketrail = true,
				smokePeriod = 5,
				smoketime = 12,
				smokesize = 4.8,
				smokecolor = 0.95,
				smokeTrailCastShadow = false,
				castshadow = false, --projectile
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				soundtrigger = true,
				startvelocity = 200,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 9950,
				tracks = true,
				turnrate = 68000,
				turret = true,
				weaponacceleration = 1000,
				weapontype = "MissileLauncher",
				weaponvelocity = 1500,
				cylindertargeting = 0.4,
				damage = {
					default = 85,
				},
			},
},
		weapons = {
			[1] = {
				def = "INQUISITOR_MISSILES",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
maxangledif = 360,
			},
[2] = {
				def = "INQUISITOR_MISSILES",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
maxangledif = 360
			},
		},
},
coroheavy = {
weapondefs = {
			Heavy_Laser = {
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				avoidneutral = false,
				collideneutral = false,
				areaofeffect = 30,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.15,
				corethickness = 1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.2,
				energypershot = 50,
				explosiongenerator = "custom:laserhit-medium-red",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0.1,
				laserflaresize = 10,
				name = "High energy space laser",
				noselfdamage = true,
				range = 1100,
				reloadtime = 1.2,
				rgbcolor = "1 0 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 3.4,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 80,
				damage = {
					default = 300,
				},
			},
		},
		weapons = {
			[1] = {
				def = "HEAVY_LASER",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
[2] = {
				def = "HEAVY_LASER",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
cororocket = {
weapondefs = {
			madsam_missile = {
				burst = 3,
				burstrate = 0.2,
				burnblow = true,
				areaofeffect = 5,
				avoidfriendly = false,
				alwaysvisible = true,      
				collidefeature = false,
				collidefriendly = false,
				cylindertargeting = 1,
				energypershot = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium",
				flighttime = 1.5,
				name = "Orbital Rocket Defense System",
				tolerance = 65536,
				range = 1000,
				reloadtime = 1.5,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 4,
				smoketime = 60,
				smoketrail = true,
				weaponacceleration = 1000,
				weapontimer = 1,
				weaponvelocity = 2000,
				damage = {
					default = 96,
				},
			},
		},
		weapons = {
			[1] = {
				def = "MADSAM_MISSILE",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
corocannon = {
weapondefs = {
			Juno = {
				areaofeffect = 300,
				alwaysvisible = true,
				flighttime = 2.5,
				burnblow = true,
				cegtag = "genericshellexplosion-small-lightning",
				canattackground = false,
				collidefeature = false,
				collidefriendly = false,
				edgeeffectiveness = 0.5,
				impulsefactor = 2,
				name = "Unstable Anti-Orbital Plasma Sphere",
				model = "",
				range = 1350,
				reloadtime = 9.2,
				tolerance = 5000,
				tracks = true,
				turnRate = 32000,
				soundhit = "xplosml5",
				soundhitwet = "lightning",
				soundstart = "lghthvy1",
				weapontype = "StarburstLauncher",
				explosiongenerator = "custom:genericshellexplosion-huge-lightning",
				startVelocity = 1000,
				weaponvelocity = 2000,
				weaponTimer = 1,
				weaponacceleration = 1000,
				damage = {
					default = 1,
					space = 3500,
				},
				customparams = {
					overrange_distance = 1400,
					projectile_destruction_method = "explode",
				},
			},
		},
		weapons = {
			[1] = {
				def = "JUNO",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
coroapoc = {
weapondefs = {
			apocalypse = {
				areaofeffect = 500,
				avoidfeature = false,
				alwaysvisible = true,
				burst = 12,
				burstrate = 0.4,
				collidefriendly = false,
				craterareaofeffect = 500,
				craterboost = 1,
				cratermult = 1,
				cegtag = "meteortrail",
				canattackground = true,
				collidefeature = false,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-meteor",
				impulsefactor = 2,
				name = "Meteor Rain",
				noselfdamage = true,
				range = 1700,
				reloadtime = 33,
				tolerance = 4000,
				size = 10,
				soundhit = "xplonuk4",
				startvelocity = 400,
				soundhitwet = "sizzle",
				sprayangle = 2000,
				turret = true,
				weapontype = "Cannon",
				weaponacceleration = 600,
				weaponvelocity = 400,
				hightrajectory = 0,
				proximitypriority = -1,
				heightBoostFactor = 0.5,
				damage = {
					default = 2200,
					shields = 6600,
				},
			},
		},
		weapons = {
			[1] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[2] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[3] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[4] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[5] = {
				def = "",
			},
			[6] = {
				def = "",
			},
		},
},
legofighter = {
weapondefs = {
			lightlaser = {
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "0.05 1 0.05",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 100,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legocan = {
weapondefs = {
			Orbital_LightningCannon = {
				areaofeffect = 250,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				canattackground = true,
				collidefeature = false,
				collidefriendly = false,
				cegtag = "lightning_stormbolt",
				energypershot = 30,
				edgeeffectiveness = 0.6,
				explosiongenerator = "custom:genericshellexplosion-medium-lightning",
				firestarter = 10,
				flighttime = 12,
				gravityaffected = "false",
				impulsefactor = 0.4,
				name = "Orbital Lightning Cannon",
				tolerance = 65536,
				noselfdamage = true,
				range = 300,
				cylinderTargeting = 10,
				heightMod = 0.1,
				reloadtime = 12,
				model = "",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				startvelocity = 400,
				turret = true,
				tracks = true,
				tolerance = 60000,
				turnrate = 400,
				weaponacceleration = 400,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 400,
				interceptedByShieldType = 1,
				customparams = {
					cluster_def = 'zap',
					cluster_number = 10,
					exclude_preaim = true,
					smart_priority = true,
				},
				damage = {
					default = 300,
					commanders = 100,
					shields = 60,
				},
			},
			zap = {
				areaofeffect = 100,
				avoidfeature = false,
				cegtag = "lightning_stormbolt_small",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:plasmahit-sparkonly",
				gravityaffected = "true",
				impulsefactor = 0.3,
				name = "Lightning Discharge",
				noselfdamage = true,
				range = 30,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "",
				weapontype = "Cannon",
				damage = {
					default = 50,
					commanders = 20,
					shields = 20,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_LIGHTNINGCANNON",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "NOTAIR",
				weaponAimAdjustPriority = nil,
				fastAutoRetargeting = false,
			},
		},
},
legspace = {
buildoptions = {
"legoc",
"legosat",
"legofighter",
"legocan",
"legosolar",
"legobruiser",
"legotrigun",
},
},
legspacet3 = {
buildoptions = {
"legoc",
"legobomber",
"legospy",
"legofort",
"legohelios",
},
},
}{
legobruiser = {
weapondefs = {
			velgun = {
 				predictBoost = 0.3,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 15,
				avoidfeature = false,
				avoidfriendly = false,
				avoidneutral = false,
				collideneutral = false,
				burst = 6,
				burstrate = 0.09,
				burnblow = false,
				canattackground = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.038,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 0.5,
				intensity = 0.8,
				name = "Rapid-fire machine gun",
				noselfdamage = true,
				proximitypriority = 1,
				range = 540,
				reloadtime = 0.45,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun2",
				soundstartvolume = 5.0,
				thickness = 0.91,
				tolerance = 60000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 916,
				cylindertargeting = 0.5,
				damage = {
					default = 18,
				},
			},
		},
		weapons = {
			[1] = {
				def = "velgun",
				maindir = "0 0 1",
				maxangledif = 360,
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legotrigun = {
weapondefs = {
			Longinus_Missile = {
				fixedLauncher = true,
				areaofeffect = 30,
				avoidfeature = false,
				avoidfriendly = false,      
				burnblow = true,
				craterareaofeffect = 0,
				canattackground = false,
				collidefeature = false,
				collidefriendly = false,
				cegtag = "lightning_stormflares",
				energypershot = 30,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:ministarfire-explosion",
				firestarter = 10,
				flighttime = 3,
				impulsefactor = 0.4,
				name = "Longinus Missile",
				noselfdamage = true,
				range = 1205,
				reloadtime = 7,
				model = "",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				startvelocity = 450,
				turret = true,
				tracks = true,
				tolerance = 60000,
				turnrate = 60000,
				weaponacceleration = 450,
				weapontype = "MissileLauncher",
				weaponvelocity = 700,
				cylindertargeting = 0.32,
				model = "SimpleFlare.s3o",
				damage = {
					default = 1540,
				},
				customparams = {
						speceffect = "retarget",
				},
			},
		},
		weapons = {
			[1] = {
				def = "LONGINUS_MISSILE",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				def = "",
			},
		},
},
legospy = {
weapondefs = {
			spygun = {
				accuracy = 100,
				collidefriendly = false,
				collideenemy = false,
				collidefeature = false,
				accuracy = 0,
				areaofeffect = 1,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "arty-botrail",
				collidefriendly = false,
				edgeeffectiveness = 0,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				hightrajectory = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				energypershot = 850,
				metalpershot = 32,
				model = "Units/legeyes.s3o",
				mygravity = 0.22,
				name = "SpyCannon",
				noselfdamage = true,
				range = 1000,
				reloadtime = 6,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 30,
				sprayangle = 2000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1250,
				customparams = {
					spawns_name = "legoeyes",
					spawns_surface = "LAND SEA",
				},
				damage = {
					default = 1,
				},
},
},
weapons = {
			[1] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
[2] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
[3] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
		},
},
legohelios = {
weapondefs = {
			t3heatray = {
				areaofeffect = 800,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 5,
				camerashake = 0.1,
				corethickness = 20,
				craterareaofeffect = 100,
				craterboost = 0,
				cratermult = 0,
				canattackground = true,
				cylindertargeting = 50,
				edgeeffectiveness = 0.45,
				energypershot = 5000,
				explosiongenerator = "custom:heatray-huge",
				firestarter = 90,
				impulsefactor = 0,
				laserflaresize = 10,
				minIntensity = 1,
				name = "Perfect Orbital Heatray",
				noselfdamage = true,
				range = 500,
				reloadtime = 15,
				rgbcolor = "1 0.5 0",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray3",
				soundstartvolume = 38,
				soundtrigger = 1,
				thickness = 30,
				turret = true,
				tolerance = 65536,
				weapontype = "BeamLaser",
				weaponvelocity = 2100,
				heightmod = 0.1,
				damage = {
					default = 60000,
					shields = 180000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "t3heatray",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
		},
},
legocannon = {
weapondefs = {
					railgunt3 = {
				predictboost = 0.2,
				areaofeffect = 150,
				avoidfeature = false,
				collidefeature = false,
				collideneutral = false,
				avoidneutral = false,
				burnblow = false,
				canattackground = false,
				cegtag = "railgun",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.12,
				edgeeffectiveness = 0.85,
				energypershot = 800,
				explosiongenerator = "custom:genericshellexplosion-large-aa-purple",
				firestarter = 0,
				impulsefactor = 2,
				intensity = 1.0,
				name = "Heavy Anti-Orbital Railgun",
				noselfdamage = true,
				range = 1450,
				reloadtime = 8,
				rgbcolor = "1 0.33 0.7",
				soundhit = "impact",
				soundhitwet = "splshbig",
				soundstart = "railgun3",
				soundstartvolume = 80,
				thickness = 4,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 7000,
				damage = {
					default = 2900,
				},
			},
		},
		weapons = {
			[1] = {
				def = "railgunt3",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legolaser = {
weapondefs = {
Orbital_Beamer = {
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				burnblow = false,
				beamdecay = 0.05,
				beamtime = 0.1,
				beamttl = 1,
				corethickness = 0.233,
				gravityaffected = "false",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				cylindertargeting = 128,
				edgeeffectiveness = 1,
				energypershot = 2,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 9.35,
				name = "Anti Orbital Laser",
				noselfdamage = true,
				range = 1000,
				reloadtime = 0.1,
				rgbcolor = "0.1 1 0.1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "beamershot2",
				soundtrigger = 1,
				thickness = 2.4,
				tolerance = 65000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 3500,
				weapontimer = 4,
				minIntensity = 1,
				heightmod = 0.1,
				damage = {
					default = 19,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_BEAMER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
armolaser = {
weapondefs = {
			orbital_laser = {
				accuracy = 0,
				areaofeffect = 10,
				avoidfriendly = false,
				avoidfeature = false,
				alwaysvisible = true,
				burnblow = false,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				cylindertargeting = 5,
				duration = 0.1,
				edgeeffectiveness = 1,
				energypershot = 1,
				explosiongenerator = "custom:genericshellexplosion-small",
				gravityaffected = "false",
				stages = 0,
				impulsefactor = 0,
				intensity = 5,
				name = "Orbital Defense Laser",
				noselfdamage = true,
				range = 1000,
				reloadtime = 0.2,
				rgbcolor = "0 0 1",
				predictboost = 1,
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				thickness = 5,
				tolerance = 65535,
				turret = true,
				weapontimer = 3,
				weapontype = "LaserCannon",
				weaponvelocity = 1500,
				heightmod = 0.1,
				damage = {
					default = 39,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
armobomber = {
weapondefs = {
			arm_botrail = {
				accuracy = 0,
				areaofeffect = 0.2,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "arty-botrail",
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				hightrajectory = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				energypershot = 5900,
				metalpershot = 65,
				model = "Units/ARMVADER.s3o",
				mygravity = 0.22,
				name = "Tumbleweed Cannon",
				noselfdamage = true,
				range = 900,
				reloadtime = 1,
				stockpile = true,
				stockpiletime = 6,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 50,
				sprayangle = 600,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1250,
				customparams = {
					spawns_name = "armvader",
					spawns_surface = "LAND",
					stockpilelimit = 10,
				},
				damage = {
					default = 1000,
					commanders = 500,
					shields = 1000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARM_BOTRAIL",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
[2] = {
def = "",
},
[3] = {
def = "",
},
[4] = {
def = "",
},
[5] = {
def = "",
},
		},
},
}{
armomulti = {
weapondefs = {
			Orbital_cannon = {
				areaofeffect = 100,
				alwaysvisible = true,
				avoidfriendly = false,
				avoidfeature = false,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.3,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 5,
				impulsefactor = 0.2,
				name = "Orbital Gauss Cannon",
				noselfdamage = true,
				range = 600,
				reloadtime = 1,
				predictboost = 1,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "cannhvy2",
				turret = true,
				weapontimer = 3,
				weapontype = "Cannon",
				weaponvelocity = 1200,
				heightBoostFactor = 0,
				damage = {
					default = 400,
				},
			},
Orbital_HighEnergyLaser = {
				areaofeffect = 10,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 0.15,
				corethickness = 0.18,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.15,
				energypershot = 20,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7.7,
				name = "HighEnergyLaser",
				noselfdamage = true,
				range = 1200,
				reloadtime = 3,
				rgbcolor = "0 1 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 2.4,
				tolerance = 65000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 900,
				heightmod = 0.1,
				cylindertargeting = 50,
				minIntensity = 1,
				damage = {
					default = 600,
		},
},
},
		weapons = {
[1] = {
				def = "ORBITAL_HIGHENERGYLASER",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
},
[2] = {
				def = "ORBITAL_HIGHENERGYLASER",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
},
[3] = {
				def = "ORBITAL_CANNON",
				fastautoretargeting = true,
				onlytargetcategory = "NOTAIR",
			},
		},
},
coromulti = {
weapondefs = {
			corviper_missile = {
				areaofeffect = 50,
				avoidfeature = false,
				avoidfriendly = false,
				castshadow = true,
				cegtag = "missiletrailviper",
				alwaysvisible = true,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = true,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				firestarter = 70,
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile3fast.s3o",
				name = "Heavy o2g rocket launcher",
				noselfdamage = true,
				range = 600,
				reloadtime = 2,
				smokecolor = 0.8,
				smokeperiod = 10,
				smokesize = 10,
				smoketime = 33,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				startvelocity = 900,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 65000,
				tracks = true,
				turnrate = 6000,
				turret = true,
				weaponacceleration = 400,
				weapontimer = 0.1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1300,
				cylindertargeting = 10,
				heightmod = 0.1,
				damage = {
					default = 820,
				},
			},
			doomsday_green_laser = {
				areaofeffect = 8,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 0.225,
				corethickness = 0.185,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.15,
				energypershot = 45,
				explosiongenerator = "custom:laserhit-medium-red",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7.7,
				name = "High energy laser",
				noselfdamage = true,
				range = 1200,
				reloadtime = 6,
				rgbcolor = "1 0.1 0.1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 5,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 900,
				heightmod = 0.1,
				cylindertargeting = 50,
				minIntensity = 1,
				damage = {
					default = 1200,
				},
			},
			doomsday_red_laser = {
				areaofeffect = 40,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				burnblow = true,
				cegtag = "missiletrailsmall",
				flighttime = 3,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 100,
				impulsefactor = 0,
				model = "cormissile3fast.s3o",
				name = "Rocket Battery",
				noselfdamage = true,
				proximitypriority = 1,
				range = 900,
				reloadtime = 0.8,
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasrfir3",
				soundtrigger = 1,
				startvelocity = 600,
				tolerance = 10000,
				turnrate = 20000,
				turret = true,
				tracks = true,
				weapontype = "MissileLauncher",
				weaponvelocity = 600,
				damage = {
					default = 90,
				},
			},
		},
		weapons = {
			[1] = {
				def = "CORVIPER_MISSILE",
				onlytargetcategory = "NOTAIR",
			},
			[2] = {
				def = "DOOMSDAY_GREEN_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[3] = {
				def = "DOOMSDAY_RED_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
legomulti = {
		weapondefs = {
			Orbital_Gatling = {
				accuracy = 0,
				areaofeffect = 32,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				burst = 3,
				burstrate = 0.02,
				burnblow = false,
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 192,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 3,
				duration = 0.1,
				edgeeffectiveness = 1,
				gravityaffected = "false",
				impulsefactor = 0,
				mygravity = 0.01,
				name = "Heavy Anti-Orbital Gatling Gun",
				noselfdamage = true,
				predictboost = 1,
				range = 1100,
				reloadtime = 0.166,
				smoketrail = false,
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundhitvolume = 7.5,
				soundstartvolume = 5,
				stages = 0,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3,
				tolerance = 16000,
				turret = true,
				weapontimer = 3,
				weapontype = "LaserCannon",
				weaponvelocity = 3642,
				damage = {
					default = 20,
				},
				rgbcolor = "1 0.33 0.7",
				explosiongenerator = "custom:plasmahit-sparkonly",
				ownerExpAccWeight = 1.35,--does this affect sprayangle too?
				sprayangle = 100,
				fallOffRate = 0.2,
			},
			orbital_railgun = {
				areaofeffect = 16,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				cylindertargeting = 50,
				heightMod = 0.1,
				burnblow = false,
				cegtag = "railgun",
				collisionSize = 0.667,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.12,
				edgeeffectiveness = 0.85,
				energypershot = 200,
				explosiongenerator = "custom:plasmahit-sparkonly",
				firestarter = 0,
				hardstop = true,
				impactonly = true,
				impulsefactor = 1,
				intensity = 0.8,
				name = "Orbital Railgun",
				noexplode = true,
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				predictboost = 1,
				range = 850,
				reloadtime = 6,
				rgbcolor = "0.34 0.64 0.94",
				soundhit = "mavgun3",
				soundhitwet = "splshbig",
				soundstart = "heavyrailgun",
				soundstartvolume = 26,
				thickness = 3,
				tolerance = 65000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 3180,
				damage = {
					default = 2400,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_GATLING",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				burstControlWhenOutOfArc = "nil",
			},
			[2] = {
				def = "ORBITAL_RAILGUN",
				onlytargetcategory = "SURFACE",
				burstControlWhenOutOfArc = "nil",
				slaveto = "nil",
			},
		},
},
legobomber = {
weapondefs = {
shocker_low = {
				areaofeffect = 200,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "starfire_arty",
				collidefriendly = false,
				craterareaofeffect = 200,
				craterboost = 0,
				cratermult = 0,
				size = 6,
				edgeeffectiveness = 0.2,
				energypershot = 300,
				explosiongenerator = "custom:starfire-explosion",
				gravityaffected = "true",
				heightboostfactor = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				name = "Long-Range Heavy Cluster Plasma Cannon",
				noselfdamage = true,
				range = 1000,
				reloadtime = 5,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundhitvolume = 38,
				soundstartvolume = 24,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 600,
				customparams = {
					cluster_def = 'cluster_munition',
					cluster_number = 4,
				},
				damage = {
					default = 2000,
					shields = 1000,
					commanders = 666.6,
				},
			},
cluster_munition = {
				areaofeffect = 150,
				avoidfeature = false,
				cegtag = "ministarfire",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:ministarfire-explosion",
				gravityaffected = "true",
				impulsefactor = 0.5,
				name = "Plasma Burst",
				noselfdamage = true,
				maxvelocity = 720,
				range = 110,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				weapontype = "Cannon",
				reloadtime = 5,
				damage = {
					default = 500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "SHOCKER_LOW",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
armollt = {
	weapondefs = {
			arm_lightlaser = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
corollt = {
	weapondefs = {
			cor_lightlaser = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
legollt = {
	weapondefs = {
			heat_ray = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				beamtime = 0.12,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
}{
corobomber = {
weapondefs = {
cannon = {
				burst = 3,
				burstrate = 0.2,
				alwaysvisible = true,
				collidefriendly = false,
				collidefeature = false,
				avoidfriendly = false,
				canattackground = true,
				areaofeffect = 100,
				heightboostfactor = 0,
				cegtag = "missiletrailmship",
				craterareaofeffect = 100,
				edgeeffectiveness = 0.7,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				interceptedbyshieldtype = 1,
				name = "Orbital Bombardment Battery.",
				proximitypriority = 1,
				range = 900,
				reloadtime = 4,
				smoketrail = false,
				weapontype = "Cannon",
				weaponvelocity = 600,
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot2",
				soundhitvolume = 19,
				soundstartvolume = 12,
				soundtrigger = true,
				turret = true,
				damage = {
					default = 500,
					commanders = 166.6,
				},
			},
			heavy_cannon = {
				areaofeffect = 200,
				alwaysvisible = true,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				name = "Heavy long-range orbital payload cannon.",
				explosiongenerator = "custom:genericshellexplosion-huge-bomb",
				range = 900,
				size = 10,
				reloadtime = 7,
				weaponvelocity = 400,
				heightboostfactor = 0,
				edgeeffectiveness = 0.3,
				hightrajectory = 1,
				impulsefactor = 0.5,
				weapontype = "Cannon",
				tolerance = 4000,
				turret = true,
				soundhit = "lrpcexplo",
				soundhitvolume = 20,
				soundhitwet = "splshbig",
				soundstart = "lrpcshot",
				damage = {
					default = 2500,
					shields = 1250,
					commanders = 1000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "HEAVY_CANNON",
				maindir = "0 0.5 1",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "CANNON",
				onlytargetcategory = "SURFACE",
			},
		},
},
legofort = {
		weapondefs = {
			semiauto = {
				collidefriendly = false,
				collidefeature = false,
				accuracy = 1,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				beamburst = true,
				beamdecay = 1,
				beamtime = 0.07,
				burst = 6,
				burstrate = 0.06667,
				canattackground = false,
				corethickness = 0.35,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 10,
				impulsefactor = 0,
				largebeamlaser = true,
				laserflaresize = 8.8,
				name = "Rapid-fire close quarters orbital 2 orbital laser",
				noselfdamage = true,
				proximitypriority = 1,
				pulsespeed = 8,
				range = 1050,
				reloadtime = 0.63333,
				rgbcolor = "0 0.75 0",
				rgbcolor2 = "0.9 0.9 0.6",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasfirerc",
				soundtrigger = 1,
				targetborder = 0.2,
				thickness = 2.4,
				tolerance = 30000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 920,
				cylindertargeting = 20,
				damage = {
					default = 21.111,
				},
			},
			Omissiles = {
				proximitypriority = -1,
				avoidfriendly = false,
				areaofeffect = 60,
				avoidfeature = false,
				collidefriendly = false,
				collidefeature = false,
				burnblow = true,
				canattackground = false,
				cegtag = "missiletrailaa",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 72,
				flighttime = 3,
				impulsefactor = 0.123,
				model = "leglargerocket.s3o",
				name = "Advanced o2o missile launcher",
				noselfdamage = true,
				range = 1050,
				reloadtime = 6,
				smoketrail = true,
				smokePeriod = 5,
				smoketime = 8,
				smokesize = 4.2,
				smokecolor = 1.0,
				smokeTrailCastShadow = false,
				castshadow = false,
				startvelocity = 150,
				soundhit = "rockhit3",
				soundhitwet = "splssml",
				soundstart = "rocklit1",
				soundtrigger = true,
				startvelocity = 400,
				texture1 = "null",
				texture2 = "smoketrailaa",
				tolerance = 60950,
				tracks = true,
				turnrate = 52000,
				weaponacceleration = 500,
				weapontype = "StarburstLauncher",
				weaponvelocity = 1200,
				customparams = {
						overrange_distance = 1100,
						projectile_destruction_method = "explode",
				},
				damage = {
					default = 2600,
				},
			},
},
		weapons = {
			[1] = {
				def = "OMISSILES",
				maindir = "-1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[2] = {
				def = "OMISSILES",
				maindir = "1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[3] = {
				def = "SEMIAUTO",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[4] = {
				def = "SEMIAUTO",
				maindir = "-1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[5] = {
				def = "SEMIAUTO",
				maindir = "1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[6] = {
				def = "SEMIAUTO",
				maindir = "1 0 0",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
corohunter = {
weapondefs = {
corviper_missile = {
				areaofeffect = 50,
				burnblow = true,
				avoidfeature = false,
				avoidfriendly = false,
				castshadow = false,
				cegtag = "missiletrailviper",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				firestarter = 70,
				flighttime = 2,
				impulsefactor = 0.123,
				model = "cormissile3fast.s3o",
				name = "Anti Orbital and Air Rocket Battery.",
				noselfdamage = true,
				range = 600,
				reloadtime = 0.5,
				smokecolor = 0.8,
				smokeperiod = 10,
				smokesize = 10,
				smoketime = 33,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				startvelocity = 900,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 65000,
				tracks = true,
				turnrate = 10000,
				turret = true,
				weaponacceleration = 400,
				weapontimer = 0.1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1300,
				cylindertargeting = 0.5,
				damage = {
					default = 200,
				},
			},
},
		weapons = {
			[1] = {
				def = "CORVIPER_MISSILE",
				onlytargetcategory = "SPACENOTOBJECT",
				fastautoretargeting = true,
			},
		},
},
armohorizon = {
	weapondefs = {
		arm_botrail = {
				commandfire = true,
				accuracy = 1,
				areaofeffect = 150,
				avoidfeature = false,
				avoidfriendly = false,
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				impulsefactor = 0.5,
				energypershot = 71000,
				metalpershot = 3300,
				model = "pbr_cube.s3o",
				name = "Orbital Vanguard Deployment Cannon",
				noselfdamage = true,
				range = 2000,
				reloadtime = 1,
				stockpile = true,
				stockpiletime = 60,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 50,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 500,
				hightrajectory = 1,
				stages = 24,
				interceptedByShieldType = 1,
				customparams = {
					spawns_name = "armvang",
					spawns_surface = "LAND",
					stockpilelimit = 2,
				},
				damage = {
					default = 1000,
				},
			},
		waterballon = {
				canattackground = false,
				range = 1000,
				reloadtime = 5,
				burnblow = false,
				name = "Orbital Strike Rocket",
				cegtag = "missiletrailviper",
				weapontype = "MissileLauncher",
				turnrate = 10000,
				weaponacceleration = 150,
				weaponvelocity = 800,
				weapontimer = 1,
				flighttime = 5,
				cylindertargeting = 0.4,
				damage = {
					commanders = nil,
					default = 1000,
					subs = nil,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "",
				def = "waterballon",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[2] = {
				def = "ARM_BOTRAIL",
				onlytargetcategory = "SURFACE",
			},
			[3] = {
				def = "NUCLEAR_LAUNCH",
			},
		},
},
armoplane = {
   weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = true,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 2,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
coroplane = {
  weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				areaofeffect = 20,
				burnblow = true,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 2,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legoplane = {
   weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				burnblow = true,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 2,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
}