{
armspace ={
buildoptions = {
"armoc",
"armosat",
"armofighter",
"armocan",
"armosolar",
"armobruiser",
"armotachyon",
},
},
armspacet3 = {
buildoptions = {
"armoc",
"armobomber",
"armohorizon",
"armokaiser",
"armoliberator",
},
},
armofighter = {
weapondefs = {
			lightlaser = {
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "0.05 0.05 1",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 220,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armocan = {
weapondefs = {
			Orbital_Cannon = {
				areaofeffect = 300,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = true,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 10,
				impulsefactor = 1,
				name = "Orbital Bombardment",
				tolerance = 65000,
				noselfdamage = true,
				range = 100,
				reloadtime = 10,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "KroGun1",
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 500,
					commanders = 166.6,
					shields = 100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_CANNON",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
armorocket = {
weapondefs = {
			orbital_rocket = {
				areaofeffect = 250,
				alwaysvisible = true,
				canattackground = false,
				collideenemy = true,
				cegtag = "cruisemissiletrail-tacnuke",
				cylindertargeting = 1,
				energypershot = 0,
				explosiongenerator = "custom:newnuketac",
				firestarter = 10,
				impulsefactor = 1.1,
				name = "Orbital Rocket System",
				range = 1350,
				reloadtime = 7.5,
				model = "cortronmissile.s3o",
				stockpile = false,
				soundhit = "xplomed4",
				soundstart = "mismed1",
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 4,
				startvelocity = 200,
				tracks = true,
				tolerance = 40000,
				turnrate = 40000,
				weaponacceleration = 1000,
				weapontimer = 1,
				weapontype = "StarburstLauncher",
				weaponvelocity = 2000,
				waterweapon = true,
				firesubmersed = true,
				damage = {
					default = 1,
					space = 2600,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_ROCKET",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armobruiser = {
weapondefs = {
			space_emg = {
				collidefriendly = false,
				collidefeature = false,
				accuracy = 0,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				duration = 0.05,
				edgeeffectiveness = 0.5,
				energypershot = 2,
				explosiongenerator = "custom:genericshellexplosion-small",
				impulsefactor = 0,
				intensity = 5,
				name = "Space Laser Battery",
				noselfdamage = true,
				proximitypriority = 1,
				range = 700,
				reloadtime = 0.5,
				rgbcolor = "0.05 0.05 1",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				thickness = 5,
				tolerance = 40000,
				turret = true,
				weapontimer = 1,
				weapontype = "LaserCannon",
				weaponvelocity = 2400,
				cylindertargeting = 0.5,
				damage = {
					default = 75,
				},
			},
		},
		weapons = {
			[1] = {
				def = "SPACE_EMG",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
				maxangledif = 360,
			},
			[2] = {
				def = "SPACE_EMG",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
				maxangledif = 360,
			},
		},
},
armotachyon = {
weapondefs = {
oata = {
				areaofeffect = 16,
				avoidfeature = false,
				collidefriendly = false,
				avoidfriendly = false,
				canattackground = false,
				beamtime = 0.1,
				corethickness = 0.3,
				largebeamlaser = true,
				laserflaresize = 6.5,
				noselfdamage = true,
				explosiongenerator = "custom:laserhit-large-blue",
				name = "Orbital 2 orbital tachyon lance.",
				rgbcolor = "0 0 1",
				scrollspeed = 5,
				soundhitwet = "sizzle",
				soundstart = "annigun1",
				soundtrigger = 1,
				texture3 = "largebeam",
				thickness = 4.5,
				tilelength = 150,
				range = 1200,
				reloadtime = 7,
				minIntensity = 1,
				energypershot = 200,
				weapontype = "BeamLaser",
				tolerance = 10000,
				turret = true,
				weaponvelocity = 1400,
				cylindertargeting = 30,
				damage = {
					default = 1550,
				},
			},
		},
		weapons = {
			[1] = {
				def = "OATA",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				def = "",
				onlytargetcategory = "",
			},
		},
},
armokaiser = {
weapondefs = {
			plasma = {
				range = 1000,
				heightBoostFactor = 0,
				customparams = {
					engagementrange = 1200,
					carried_unit = "armodrone",     --Name of the unit spawned by this carrier unit.
					spawns_surface = "LAND SEA",
				},
			},
			aamissile = {
				avoidfriendly = false,
				collidefriendly = false,
				burst = 2,
				burstrate = 0.8,
				areaofeffect = 100,
				burnblow = false,
				cegtag = "missiletrailaa",
				collidefeature = false,
				flighttime = 5,
				name = "Battleship Missile",
				range = 1000,
				weaponacceleration = 300,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1200,
				cylindertargeting = 0.4,
				damage = {
					default = 1000,
					vtol = "500",
				},
			},
		},
		weapons = {
			[1] = {
				def = "AAMISSILE",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[2] = {
				def = "PLASMA",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armodrone = {
weapondefs = {
armodrone_missile = {
				areaofeffect = 40,
				avoidfeature = false,
				burnblow = false,
				canattackground = false,
				cegtag = "missiletrailsmall-red",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-catapult",
				firestarter = 70,
				flighttime = 9,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "catapultmissile.s3o",
				name = "Seeking Interplanetary Missile Launcher",
				noselfdamage = true,
				range = 500,
				reloadtime = 0.3,
				smoketrail = true,
				smokePeriod = 7,
				smoketime = 13,
				smokesize = 5.4,
				smokecolor = 0.95,
				smokeTrailCastShadow = false,
				castshadow = false,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "rockhvy2",
				startvelocity = 800,
				texture1 = "null",
				texture2 = "smoketrailaa3",
				tolerance = 20000,
				tracks = true,
				turnrate = 50000,
				turret = true,
				weaponacceleration = 500,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1200,
				cylindertargeting = 0.4,
				damage = {
					default = 9,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARMODRONE_MISSILE",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armoliberator = {
weapondefs = {
			heavyplasma = {
				alwaysVisible = true,
				accuracy = 100,
				areaofeffect = 200,
				collidefriendly = false,
				collidefeature = false,
				hightrajectory = 1,
				range = 2100,
				heightBoostFactor = 0,
				damage = {
					default = 400,
					shields = 200,
				},
			},
			ferret_missile = {
				areaofeffect = 50,
				collidefriendly = false,
				collidefeature = false,
				burnblow = false,
				edgeeffectiveness = 0.15,
				flighttime = 5,
				name = "Pop-up rapid-fire o2a missile launcher",
				range = 1000,
				reloadtime = 2,
				damage = {
					default = 600,
				},
			},
		},
		weapons = {
			[2] = {
				def = "HEAVYPLASMA",
				maindir = "0 0 1",
				maxangledif = 320,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[4] = {
				def = "HEAVYPLASMA",
				maindir = "-4 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[5] = {
				def = "HEAVYPLASMA",
				maindir = "4 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[6] = {
				maindir = "0 -1 -2",
				maxangledif = 270,
				def = "FERRET_MISSILE",
				onlytargetcategory = "VTOL SPACENOTOBJECT",
			},
			[7] = {
				def = "FERRET_MISSILE",
				onlytargetcategory = "VTOL SPACENOTOBJECT",
			},
		},
},
corspace = {
buildoptions = {
"corosat",
"coroc",
"corosolar",
"corofighter",
"corocan",
"corobruiser",
"coroheavy",
},
},
corspacet3 = {
buildoptions = {
"coroc",
"corobomber",
"corohunter",
"coroheatray",
"coroapoc",
},
},
coroheatray ={
weapondefs = {
			laser = {
				avoidneutral = false,
				collideneutral = false,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				areaofeffect = 72,
				avoidfriendly = false,
				energypershot = 350,
				range = 1200,
				minIntensity = 1,
				cylindertargeting = 10,
				heightmod = 0.1,
				damage = {
					default = 4000,
				},
			},
		},
		weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
		},
},
corofighter = {
weapondefs = {
			lightlaser = {
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "1 0.05 0.05",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 100,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
}{
corocan = {
weapondefs = {
Orbital_3Cannon = {
				areaofeffect = 200,
				avoidfeature = false,
				avoidfriendly = false, 
				burst = 3,
				burstrate= 0.1,
				cegtag = "arty-extraheavy",
				craterareaofeffect = 300,
				collidefriendly = false,
				collidefeature = false,
				canattackground = true,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-large",
				firestarter = 10,
				impulsefactor = 0.2,
				name = "Orbital Bombardment",
				tolerance = 50000,
				noselfdamage = true,
				range = 100,
				reloadtime = 11,
				soundhit = "xplonuk5",
				soundhitwet = "splslrg",
				soundstart = "KroGun1",
				sprayangle = 500,
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 200,
					commanders = 66.6,
					shields = 40,
				},
			},
},
		weapons = {
			[1] = {
				def = "ORBITAL_3CANNON",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
corobruiser = {
weapondefs = {
Inquisitor_Missiles = {
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 25,
				avoidfeature = false,
				avoidfriendly = false,
				burst = 2,
				burstrate = 0.2,
				burnblow = false,
				canattackground = false,
				cegtag = "missiletrailviper",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				edgeeffectiveness = 0.15,
				energypershot = 0,
				explosiongenerator = "custom:genericshellexplosion-tiny-aa",
				firestarter = 72,
				flighttime = 2,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "cormissile3fast.s3o",
				name = "Orbital Striker Missiles.",
				noselfdamage = true,
				range = 800,
				reloadtime = 1,
				smoketrail = true,
				smokePeriod = 5,
				smoketime = 12,
				smokesize = 4.8,
				smokecolor = 0.95,
				smokeTrailCastShadow = false,
				castshadow = false, --projectile
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				soundtrigger = true,
				startvelocity = 200,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 9950,
				tracks = true,
				turnrate = 68000,
				turret = true,
				weaponacceleration = 1000,
				weapontype = "MissileLauncher",
				weaponvelocity = 1500,
				cylindertargeting = 0.4,
				damage = {
					default = 85,
				},
			},
},
		weapons = {
			[1] = {
				def = "INQUISITOR_MISSILES",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
maxangledif = 360,
			},
[2] = {
				def = "INQUISITOR_MISSILES",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
maxangledif = 360
			},
		},
},
coroheavy = {
weapondefs = {
			Heavy_Laser = {
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				avoidneutral = false,
				collideneutral = false,
				areaofeffect = 30,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.15,
				corethickness = 1,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.2,
				energypershot = 50,
				explosiongenerator = "custom:laserhit-medium-red",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0.1,
				laserflaresize = 10,
				name = "High energy space laser",
				noselfdamage = true,
				range = 1100,
				reloadtime = 1.2,
				rgbcolor = "1 0 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 3.4,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 80,
				damage = {
					default = 220,
				},
			},
		},
		weapons = {
			[1] = {
				def = "HEAVY_LASER",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
[2] = {
				def = "HEAVY_LASER",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
cororocket = {
weapondefs = {
			madsam_missile = {
				burst = 3,
				burstrate = 0.2,
				areaofeffect = 5,
				avoidfriendly = false,
				alwaysvisible = true,      
				collidefeature = false,
				collidefriendly = false,
				cylindertargeting = 1,
				energypershot = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium",
				flighttime = 2,
				name = "Orbital Rocket Defense System",
				tolerance = 65536,
				range = 1000,
				reloadtime = 1.5,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 4,
				smoketime = 60,
				smoketrail = true,
				weaponacceleration = 1000,
				weapontimer = 1,
				weaponvelocity = 2000,
				damage = {
					default = 93.3333,
				},
			},
		},
		weapons = {
			[1] = {
				def = "MADSAM_MISSILE",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
corocannon = {
weapondefs = {
			Juno = {
				areaofeffect = 300,
				alwaysvisible = true,
				flighttime = 6,
				cegtag = "genericshellexplosion-small-lightning",
				canattackground = false,
				collidefeature = false,
				collidefriendly = false,
				edgeeffectiveness = 0.5,
				impulsefactor = 2,
				name = "Unstable Anti-Orbital Plasma Sphere",
				model = "",
				range = 1350,
				reloadtime = 9.2,
				tolerance = 5000,
				tracks = true,
				turnRate = 32000,
				soundhit = "xplosml5",
				soundhitwet = "lightning",
				soundstart = "lghthvy1",
				weapontype = "StarburstLauncher",
				explosiongenerator = "custom:genericshellexplosion-huge-lightning",
				startVelocity = 1500,
				weaponvelocity = 1500,
				weaponTimer = 1,
				damage = {
					default = 1,
					space = 3500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "JUNO",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
coroapoc = {
weapondefs = {
			apocalypse = {
				areaofeffect = 500,
				avoidfeature = false,
				alwaysvisible = true,
				burst = 11,
				burstrate = 0.4,
				collidefriendly = false,
				craterareaofeffect = 500,
				craterboost = 1,
				cratermult = 1,
				cegtag = "meteortrail",
				canattackground = true,
				collidefeature = false,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-meteor",
				impulsefactor = 2,
				name = "Meteor Rain",
				noselfdamage = true,
				range = 1700,
				reloadtime = 33,
				tolerance = 4000,
				size = 10,
				soundhit = "xplonuk4",
				startvelocity = 400,
				soundhitwet = "sizzle",
				sprayangle = 900,
				turret = true,
				weapontype = "Cannon",
				weaponacceleration = 600,
				weaponvelocity = 400,
				hightrajectory = 1,
				proximitypriority = -1,
				heightBoostFactor = 0.5,
				damage = {
					default = 2200,
					shields = 1100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[2] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[3] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[4] = {
				def = "APOCALYPSE",
				onlytargetcategory = "SURFACE",
				maxangledif = 360,
			},
			[5] = {
				def = "",
			},
			[6] = {
				def = "",
			},
		},
},
legofighter = {
weapondefs = {
			lightlaser = {
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "0.05 1 0.05",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 1,
				cylindertargeting = 100,
				damage = {
					default = 17.5,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legocan = {
weapondefs = {
			Orbital_LightningCannon = {
				areaofeffect = 250,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				canattackground = true,
				collidefeature = false,
				collidefriendly = false,
				cegtag = "lightning_stormbolt",
				energypershot = 30,
				edgeeffectiveness = 0.6,
				explosiongenerator = "custom:genericshellexplosion-medium-lightning",
				firestarter = 10,
				flighttime = 12,
				gravityaffected = "false",
				impulsefactor = 0.4,
				name = "Orbital Lightning Cannon",
				tolerance = 65536,
				noselfdamage = true,
				range = 300,
				cylinderTargeting = 10,
				heightMod = 0.1,
				reloadtime = 12,
				model = "",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "lghthvy1",
				startvelocity = 400,
				turret = true,
				tracks = true,
				tolerance = 60000,
				turnrate = 400,
				weaponacceleration = 400,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 400,
				interceptedByShieldType = 1,
				customparams = {
					cluster_def = 'zap',
					cluster_number = 10,
					exclude_preaim = true,
					smart_priority = true,
				},
				damage = {
					default = 300,
					commanders = 100,
					shields = 60,
				},
			},
			zap = {
				areaofeffect = 100,
				avoidfeature = false,
				cegtag = "lightning_stormbolt_small",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:plasmahit-sparkonly",
				gravityaffected = "true",
				impulsefactor = 0.3,
				name = "Lightning Discharge",
				noselfdamage = true,
				range = 30,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "lashit",
				soundhitwet = "sizzle",
				soundstart = "",
				weapontype = "Cannon",
				damage = {
					default = 50,
					commanders = 20,
					shields = 20,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_LIGHTNINGCANNON",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "NOTAIR",
				weaponAimAdjustPriority = nil,
				fastAutoRetargeting = false,
			},
		},
},
legspace = {
buildoptions = {
"legoc",
"legosat",
"legofighter",
"legocan",
"legosolar",
"legobruiser",
"legotrigun",
},
},
legspacet3 = {
buildoptions = {
"legoc",
"legobomber",
"legospy",
"legofort",
"legohelios",
},
},
}{
legobruiser = {
weapondefs = {
			velgun = {
 				predictBoost = 0.3,
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 15,
				avoidfeature = false,
				avoidfriendly = false,
				avoidneutral = false,
				collideneutral = false,
				burst = 6,
				burstrate = 0.09,
				burnblow = false,
				canattackground = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.038,
				edgeeffectiveness = 0.85,
				explosiongenerator = "custom:plasmahit-sparkonly",
				fallOffRate = 0.2,
				firestarter = 0,
				impulsefactor = 0.5,
				intensity = 0.8,
				name = "Rapid-fire machine gun",
				noselfdamage = true,
				proximitypriority = 1,
				range = 540,
				reloadtime = 0.45,
				rgbcolor = "1 0.95 0.4",
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "mgun2",
				soundstartvolume = 5.0,
				thickness = 0.91,
				tolerance = 60000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 916,
				cylindertargeting = 0.5,
				damage = {
					default = 18,
				},
			},
		},
		weapons = {
			[1] = {
				def = "velgun",
				maindir = "0 0 1",
				maxangledif = 360,
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legotrigun = {
weapondefs = {
			Longinus_Missile = {
				fixedLauncher = true,
				areaofeffect = 30,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				canattackground = false,
				collidefeature = false,
				collidefriendly = false,
				cegtag = "starfire_arty",
				energypershot = 30,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:ministarfire-explosion",
				firestarter = 10,
				flighttime = 5,
				gravityaffected = "false",
				impulsefactor = 0.4,
				name = "Longinus Missile",
				tolerance = 65536,
				noselfdamage = true,
				range = 1200,
				reloadtime = 7,
				model = "",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				startvelocity = 450,
				turret = true,
				tracks = true,
				tolerance = 60000,
				turnrate = 30000,
				weaponacceleration = 450,
				weapontype = "StarburstLauncher",
				weaponvelocity = 700,
				cylindertargeting = 0.32,
				damage = {
					default = 1540,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LONGINUS_MISSILE",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				maxangledif = 360,
			},
			[2] = {
				def = "",
			},
		},
},
legospy = {
weapondefs = {
			spygun = {
				accuracy = 100,
				collidefriendly = false,
				collideenemy = false,
				collidefeature = false,
				accuracy = 0,
				areaofeffect = 1,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "arty-botrail",
				collidefriendly = false,
				edgeeffectiveness = 0,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				hightrajectory = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				energypershot = 850,
				metalpershot = 32,
				model = "Units/legeyes.s3o",
				mygravity = 0.22,
				name = "SpyCannon",
				noselfdamage = true,
				range = 1000,
				reloadtime = 6,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 30,
				sprayangle = 2000,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1250,
				customparams = {
					spawns_name = "legoeyes",
					spawns_surface = "LAND SEA",
				},
				damage = {
					default = 1,
				},
},
},
weapons = {
			[1] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
[2] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
[3] = {
				def = "SPYGUN",
				onlytargetcategory = "SURFACE",

			},
		},
},
legohelios = {
weapondefs = {
			t3heatray = {
				areaofeffect = 800,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 5,
				camerashake = 0.1,
				corethickness = 5,
				craterareaofeffect = 100,
				craterboost = 0,
				cratermult = 0,
				canattackground = true,
				cylindertargeting = 50,
				edgeeffectiveness = 0.45,
				energypershot = 5000,
				explosiongenerator = "custom:heatray-huge",
				firestarter = 90,
				impulsefactor = 0,
				laserflaresize = 10,
				minIntensity = 1,
				name = "Perfect Orbital Heatray",
				noselfdamage = true,
				range = 500,
				reloadtime = 15,
				rgbcolor = "1 0.5 0",
				rgbcolor2 = "0.9 1.0 0.5",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "heatray3",
				soundstartvolume = 38,
				soundtrigger = 1,
				thickness = 10,
				turret = true,
				tolerance = 65536,
				weapontype = "BeamLaser",
				weaponvelocity = 2100,
				heightmod = 0.1,
				damage = {
					default = 50000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "t3heatray",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
		},
},
legocannon = {
weapondefs = {
					railgunt3 = {
				predictboost = 0.2,
				areaofeffect = 150,
				avoidfeature = false,
				collidefeature = false,
				collideneutral = false,
				avoidneutral = false,
				burnblow = false,
				canattackground = false,
				cegtag = "railgun",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.12,
				edgeeffectiveness = 0.85,
				energypershot = 800,
				explosiongenerator = "custom:genericshellexplosion-large-aa-purple",
				firestarter = 0,
				impulsefactor = 2,
				intensity = 1.0,
				name = "Heavy Anti-Orbital Railgun",
				noselfdamage = true,
				range = 1450,
				reloadtime = 8,
				rgbcolor = "1 0.33 0.7",
				soundhit = "impact",
				soundhitwet = "splshbig",
				soundstart = "railgun3",
				soundstartvolume = 80,
				thickness = 4,
				tolerance = 6000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 7000,
				damage = {
					default = 2900,
				},
			},
		},
		weapons = {
			[1] = {
				def = "railgunt3",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legolaser = {
weapondefs = {
Orbital_Beamer = {
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				burnblow = false,
				beamdecay = 0.05,
				beamtime = 0.1,
				beamttl = 1,
				corethickness = 0.233,
				gravityaffected = "false",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				cylindertargeting = 128,
				edgeeffectiveness = 1,
				energypershot = 2,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 9.35,
				name = "Anti Orbital Laser",
				noselfdamage = true,
				range = 1000,
				reloadtime = 0.1,
				rgbcolor = "0.1 1 0.1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "beamershot2",
				soundtrigger = 1,
				thickness = 2.4,
				tolerance = 65000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 3500,
				weapontimer = 4,
				minIntensity = 1,
				heightmod = 0.1,
				damage = {
					default = 19,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_BEAMER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
armolaser = {
weapondefs = {
			orbital_laser = {
				accuracy = 0,
				areaofeffect = 10,
				avoidfriendly = false,
				avoidfeature = false,
				alwaysvisible = true,
				burnblow = false,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				cylindertargeting = 5,
				duration = 0.1,
				edgeeffectiveness = 1,
				energypershot = 1,
				explosiongenerator = "custom:genericshellexplosion-small",
				gravityaffected = "false",
				stages = 0,
				impulsefactor = 0,
				intensity = 5,
				name = "Orbital Defense Laser",
				noselfdamage = true,
				range = 1000,
				reloadtime = 0.2,
				rgbcolor = "0 0 1",
				predictboost = 1,
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				thickness = 5,
				tolerance = 65535,
				turret = true,
				weapontimer = 3,
				weapontype = "LaserCannon",
				weaponvelocity = 1500,
				heightmod = 0.1,
				damage = {
					default = 39,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
armobomber = {
weapondefs = {
			arm_botrail = {
				accuracy = 0,
				areaofeffect = 0.2,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "arty-botrail",
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				hightrajectory = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				energypershot = 5900,
				metalpershot = 65,
				model = "Units/ARMVADER.s3o",
				mygravity = 0.22,
				name = "Tumbleweed Cannon",
				noselfdamage = true,
				range = 900,
				reloadtime = 1,
				stockpile = true,
				stockpiletime = 6,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 50,
				sprayangle = 600,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 1250,
				customparams = {
					spawns_name = "armvader",
					spawns_surface = "LAND",
					stockpilelimit = 10,
				},
				damage = {
					default = 1000,
					commanders = 500,
					shields = 500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ARM_BOTRAIL",
				maindir = "0 -1 0",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
[2] = {
def = "",
},
[3] = {
def = "",
},
[4] = {
def = "",
},
[5] = {
def = "",
},
		},
},
}{
armomulti = {
weapondefs = {
			Orbital_cannon = {
				areaofeffect = 100,
				alwaysvisible = true,
				avoidfriendly = false,
				avoidfeature = false,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.3,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 5,
				impulsefactor = 0.2,
				name = "Orbital Gauss Cannon",
				noselfdamage = true,
				range = 600,
				reloadtime = 1,
				predictboost = 1,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "cannhvy2",
				turret = true,
				weapontimer = 3,
				weapontype = "Cannon",
				weaponvelocity = 1200,
				heightBoostFactor = 0,
				damage = {
					default = 400,
				},
			},
Orbital_HighEnergyLaser = {
				areaofeffect = 10,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 0.15,
				corethickness = 0.18,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.15,
				energypershot = 20,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7.7,
				name = "HighEnergyLaser",
				noselfdamage = true,
				range = 1200,
				reloadtime = 3,
				rgbcolor = "0 1 0",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 2.4,
				tolerance = 65000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 900,
				heightmod = 0.1,
				cylindertargeting = 50,
				minIntensity = 1,
				damage = {
					default = 450,
		},
},
},
		weapons = {
[1] = {
				def = "ORBITAL_HIGHENERGYLASER",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
},
[2] = {
				def = "ORBITAL_HIGHENERGYLASER",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
},
[3] = {
				def = "ORBITAL_CANNON",
				fastautoretargeting = true,
				onlytargetcategory = "NOTAIR",
			},
		},
},
coromulti = {
weapondefs = {
			corviper_missile = {
				areaofeffect = 50,
				avoidfeature = false,
				avoidfriendly = false,
				castshadow = true,
				cegtag = "missiletrailviper",
				alwaysvisible = true,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = true,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				firestarter = 70,
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile3fast.s3o",
				name = "Heavy o2g rocket launcher",
				noselfdamage = true,
				range = 600,
				reloadtime = 2,
				smokecolor = 0.8,
				smokeperiod = 10,
				smokesize = 10,
				smoketime = 33,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				startvelocity = 900,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 65000,
				tracks = true,
				turnrate = 6000,
				turret = true,
				weaponacceleration = 400,
				weapontimer = 0.1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1300,
				cylindertargeting = 10,
				heightmod = 0.1,
				damage = {
					default = 820,
				},
			},
			doomsday_green_laser = {
				areaofeffect = 8,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				beamtime = 0.225,
				corethickness = 0.185,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.15,
				energypershot = 45,
				explosiongenerator = "custom:laserhit-medium-red",
				firestarter = 90,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7.7,
				name = "High energy laser",
				noselfdamage = true,
				range = 1200,
				reloadtime = 6,
				rgbcolor = "1 0.1 0.1",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "Lasrmas2",
				soundtrigger = 1,
				thickness = 5,
				tolerance = 10000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 900,
				heightmod = 0.1,
				cylindertargeting = 50,
				minIntensity = 1,
				damage = {
					default = 1000,
				},
			},
			doomsday_red_laser = {
				areaofeffect = 40,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				cegtag = "missiletrailsmall",
				flighttime = 4,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 100,
				impulsefactor = 0,
				model = "cormissile3fast.s3o",
				name = "Rocket Battery",
				noselfdamage = true,
				proximitypriority = 1,
				range = 900,
				reloadtime = 0.8,
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasrfir3",
				soundtrigger = 1,
				startvelocity = 600,
				tolerance = 10000,
				turnrate = 20000,
				turret = true,
				tracks = true,
				weapontype = "MissileLauncher",
				weaponvelocity = 600,
				damage = {
					default = 80,
				},
			},
		},
		weapons = {
			[1] = {
				def = "CORVIPER_MISSILE",
				onlytargetcategory = "NOTAIR",
			},
			[2] = {
				def = "DOOMSDAY_GREEN_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[3] = {
				def = "DOOMSDAY_RED_LASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
legomulti = {
		weapondefs = {
			Orbital_Gatling = {
				accuracy = 0,
				areaofeffect = 32,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				burst = 3,
				burstrate = 0.02,
				burnblow = false,
				canattackground = false,
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 192,
				craterboost = 0,
				cratermult = 0,
				cylindertargeting = 3,
				duration = 0.1,
				edgeeffectiveness = 1,
				gravityaffected = "false",
				impulsefactor = 0,
				mygravity = 0.01,
				name = "Heavy Anti-Orbital Gatling Gun",
				noselfdamage = true,
				predictboost = 1,
				range = 1100,
				reloadtime = 0.166,
				smoketrail = false,
				soundhit = "bimpact3",
				soundhitwet = "splshbig",
				soundstart = "minigun3",
				soundhitvolume = 7.5,
				soundstartvolume = 5,
				stages = 0,
				texture1 = "shot",
				texture2 = "empty",
				thickness = 3,
				tolerance = 16000,
				turret = true,
				weapontimer = 3,
				weapontype = "LaserCannon",
				weaponvelocity = 3642,
				damage = {
					default = 15.5,
				},
				rgbcolor = "1 0.33 0.7",
				explosiongenerator = "custom:plasmahit-sparkonly",
				ownerExpAccWeight = 1.35,--does this affect sprayangle too?
				sprayangle = 100,
				fallOffRate = 0.2,
			},
			orbital_railgun = {
				areaofeffect = 16,
				avoidfeature = false,
				avoidfriendly = false,
				alwaysvisible = true,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				cylindertargeting = 50,
				heightMod = 0.1,
				burnblow = false,
				cegtag = "railgun",
				collisionSize = 0.667,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				duration = 0.12,
				edgeeffectiveness = 0.85,
				energypershot = 200,
				explosiongenerator = "custom:plasmahit-sparkonly",
				firestarter = 0,
				hardstop = true,
				impactonly = true,
				impulsefactor = 1,
				intensity = 0.8,
				name = "Orbital Railgun",
				noexplode = true,
				noselfdamage = true,
				ownerExpAccWeight = 4.0,
				proximitypriority = 1,
				predictboost = 1,
				range = 850,
				reloadtime = 6,
				rgbcolor = "0.34 0.64 0.94",
				soundhit = "mavgun3",
				soundhitwet = "splshbig",
				soundstart = "heavyrailgun",
				soundstartvolume = 26,
				thickness = 3,
				tolerance = 65000,
				turret = true,
				weapontype = "LaserCannon",
				weaponvelocity = 3180,
				damage = {
					default = 2400,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_GATLING",
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
				burstControlWhenOutOfArc = "nil",
			},
			[2] = {
				def = "ORBITAL_RAILGUN",
				onlytargetcategory = "SURFACE",
				burstControlWhenOutOfArc = "nil",
				slaveto = "nil",
			},
		},
},
legobomber = {
weapondefs = {
shocker_low = {
				areaofeffect = 200,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "starfire_arty",
				collidefriendly = false,
				craterareaofeffect = 200,
				craterboost = 0,
				cratermult = 0,
				size = 6,
				edgeeffectiveness = 0.2,
				energypershot = 300,
				explosiongenerator = "custom:starfire-explosion",
				gravityaffected = "true",
				heightboostfactor = 0,
				impulsefactor = 0.5,
				leadbonus = 0,
				name = "Long-Range Heavy Cluster Plasma Cannon",
				noselfdamage = true,
				range = 1000,
				reloadtime = 5,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundhitvolume = 38,
				soundstartvolume = 24,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 600,
				customparams = {
					cluster_def = 'cluster_munition',
					cluster_number = 4,
				},
				damage = {
					default = 2000,
					shields = 1000,
					commanders = 666.6,
				},
			},
cluster_munition = {
				areaofeffect = 150,
				avoidfeature = false,
				cegtag = "ministarfire",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:ministarfire-explosion",
				gravityaffected = "true",
				impulsefactor = 0.5,
				name = "Plasma Burst",
				noselfdamage = true,
				maxvelocity = 720,
				range = 110,
				rgbcolor = "0.7 0.7 1.0",
				soundhit = "xplomed2",
				soundhitwet = "splsmed",
				soundstart = "cannhvy5",
				weapontype = "Cannon",
				reloadtime = 5,
				damage = {
					default = 500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "SHOCKER_LOW",
				maindir = "0 -1 0",
				onlytargetcategory = "SURFACE",
			},
		},
},
armollt = {
	weapondefs = {
			arm_lightlaser = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
corollt = {
	weapondefs = {
			cor_lightlaser = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
legollt = {
	weapondefs = {
			heat_ray = {
				range = 600,
				reloadtime = 0.7,
				minIntensity = 1,
				beamtime = 0.12,
				cylindertargeting = 50,
				heightmod = 0.1,
				damage = {
					commanders = nil,
					default = 42,
					subs = nil,
					vtol = nil,
				},
               },
        },
weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
		},
},
}{
corobomber = {
weapondefs = {
cannon = {
				burst = 3,
				burstrate = 0.2,
				alwaysvisible = true,
				collidefriendly = false,
				collidefeature = false,
				avoidfriendly = false,
				canattackground = true,
				areaofeffect = 100,
				heightboostfactor = 0,
				cegtag = "missiletrailmship",
				craterareaofeffect = 100,
				edgeeffectiveness = 0.7,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				interceptedbyshieldtype = 1,
				name = "Orbital Bombardment Battery.",
				proximitypriority = 1,
				range = 900,
				reloadtime = 4,
				smoketrail = false,
				weapontype = "Cannon",
				weaponvelocity = 500,
				soundhit = "lrpcexplo",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot2",
				soundhitvolume = 19,
				soundstartvolume = 12,
				soundtrigger = true,
				turret = true,
				damage = {
					default = 500,
					commanders = 166.6,
				},
			},
			heavy_cannon = {
				areaofeffect = 200,
				alwaysvisible = true,
				canattackground = true,
				collidefriendly = false,
				collidefeature = false,
				name = "Heavy long-range orbital payload cannon.",
				explosiongenerator = "custom:genericshellexplosion-huge-bomb",
				range = 900,
				size = 10,
				reloadtime = 7,
				weaponvelocity = 400,
				heightboostfactor = 0,
				edgeeffectiveness = 0.3,
				hightrajectory = 1,
				impulsefactor = 0.5,
				weapontype = "Cannon",
				tolerance = 4000,
				turret = true,
				soundhit = "lrpcexplo",
				soundhitvolume = 20,
				soundhitwet = "splshbig",
				soundstart = "lrpcshot",
				damage = {
					default = 2500,
					shields = 1250,
					commanders = 1000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "HEAVY_CANNON",
				maindir = "0 0.5 1",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "CANNON",
				onlytargetcategory = "SURFACE",
			},
		},
},
legofort = {
		weapondefs = {
			semiauto = {
				collidefriendly = false,
				collidefeature = false,
				accuracy = 1,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				beamburst = true,
				beamdecay = 1,
				beamtime = 0.07,
				burst = 6,
				burstrate = 0.06667,
				canattackground = false,
				corethickness = 0.35,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-medium-green",
				firestarter = 10,
				impulsefactor = 0,
				largebeamlaser = true,
				laserflaresize = 8.8,
				name = "Rapid-fire close quarters orbital 2 orbital laser",
				noselfdamage = true,
				proximitypriority = 1,
				pulsespeed = 8,
				range = 1050,
				reloadtime = 0.63333,
				rgbcolor = "0 0.75 0",
				rgbcolor2 = "0.9 0.9 0.6",
				soundhitdry = "",
				soundhitwet = "sizzle",
				soundstart = "lasfirerc",
				soundtrigger = 1,
				targetborder = 0.2,
				thickness = 2.4,
				tolerance = 30000,
				turret = true,
				weapontype = "BeamLaser",
				weaponvelocity = 920,
				damage = {
					default = 21.111,
				},
			},
			Omissiles = {
				proximitypriority = -1,
				avoidfriendly = false,
				areaofeffect = 60,
				avoidfeature = false,
				collidefriendly = false,
				collidefeature = false,
				burnblow = true,
				canattackground = false,
				cegtag = "missiletrailaa",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 72,
				fixedLauncher = true,
				flighttime = 7.5,
				impulsefactor = 0.123,
				model = "leglargerocket.s3o",
				name = "Advanced o2o missile launcher",
				noselfdamage = true,
				range = 1050,
				reloadtime = 6,
				smoketrail = true,
				smokePeriod = 5,
				smoketime = 8,
				smokesize = 4.2,
				smokecolor = 1.0,
				smokeTrailCastShadow = false,
				castshadow = false,
				startvelocity = 150,
				soundhit = "rockhit3",
				soundhitwet = "splssml",
				soundstart = "rocklit1",
				soundtrigger = true,
				startvelocity = 400,
				texture1 = "null",
				texture2 = "smoketrailaa",
				tolerance = 9950,
				tracks = true,
				trajectoryHeight = 1,
				turnrate = 52000,
				weaponacceleration = 500,
				weapontype = "StarburstLauncher",
				weapontimer = 0.32,
				weaponvelocity = 1200,
				damage = {
					default = 2600,
				},
			},
},
		weapons = {
			[1] = {
				def = "OMISSILES",
				maindir = "-1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[2] = {
				def = "OMISSILES",
				maindir = "1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT T4AIR",
			},
			[3] = {
				def = "SEMIAUTO",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[4] = {
				def = "SEMIAUTO",
				maindir = "-1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[5] = {
				def = "SEMIAUTO",
				maindir = "1 0 0",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[6] = {
				def = "SEMIAUTO",
				maindir = "1 0 0",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
corohunter = {
weapondefs = {
corviper_missile = {
				areaofeffect = 50,
				avoidfeature = false,
				avoidfriendly = false,
				castshadow = false,
				cegtag = "missiletrailviper",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:genericshellexplosion-medium-bomb",
				firestarter = 70,
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile3fast.s3o",
				name = "Anti Orbital and Air Rocket Battery.",
				noselfdamage = true,
				range = 600,
				reloadtime = 0.5,
				smokecolor = 0.8,
				smokeperiod = 10,
				smokesize = 10,
				smoketime = 33,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "SabotHit",
				soundhitwet = "splshbig",
				soundstart = "SabotFire",
				startvelocity = 900,
				texture1 = "null",
				texture2 = "railguntrail",
				tolerance = 65000,
				tracks = true,
				turnrate = 10000,
				turret = true,
				weaponacceleration = 400,
				weapontimer = 0.1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1300,
				cylindertargeting = 0.5,
				damage = {
					default = 200,
				},
			},
},
		weapons = {
			[1] = {
				def = "CORVIPER_MISSILE",
				onlytargetcategory = "SPACENOTOBJECT",
				fastautoretargeting = true,
			},
		},
},
armohorizon = {
	weapondefs = {
		arm_botrail = {
				commandfire = true,
				accuracy = 1,
				areaofeffect = 150,
				avoidfeature = false,
				avoidfriendly = false,
				collidefriendly = false,
				craterareaofeffect = 116,
				craterboost = 0.1,
				cratermult = 0.1,
				edgeeffectiveness = 0.2,
				explosiongenerator = "custom:botrailspawn",
				gravityaffected = "true",
				heightboostfactor = 0,
				impulsefactor = 0.5,
				energypershot = 71000,
				metalpershot = 3300,
				model = "pbr_cube.s3o",
				name = "Orbital Vanguard Deployment Cannon",
				noselfdamage = true,
				range = 2000,
				reloadtime = 1,
				stockpile = true,
				stockpiletime = 60,
				soundhit = "xplonuk1xs",
				soundhitwet = "splshbig",
				soundstart = "lrpcshot3",
				soundstartvolume = 50,
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 500,
				hightrajectory = 1,
				stages = 24,
				interceptedByShieldType = 1,
				customparams = {
					spawns_name = "armvang",
					spawns_surface = "LAND",
					stockpilelimit = 2,
				},
				damage = {
					default = 1000,
				},
			},
		waterballon = {
				canattackground = false,
				range = 1000,
				reloadtime = 5,
				burnblow = false,
				name = "Orbital Strike Rocket",
				cegtag = "missiletrailviper",
				weapontype = "MissileLauncher",
				turnrate = 10000,
				weaponacceleration = 150,
				weaponvelocity = 800,
				weapontimer = 1,
				flighttime = 5,
				cylindertargeting = 0.4,
				damage = {
					commanders = nil,
					default = 1000,
					subs = nil,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "",
				def = "waterballon",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[2] = {
				def = "ARM_BOTRAIL",
				onlytargetcategory = "SURFACE",
			},
			[3] = {
				def = "NUCLEAR_LAUNCH",
			},
		},
},
armoplane = {
   weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
coroplane = {
  weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
legoplane = {
   weapondefs = {
      			space_rocket = {
				burst = 2,
				burstrate = 0.3,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "missiletrailfighter",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.25,
				explosiongenerator = "custom:genericshellexplosion-tiny-air",
				flighttime = 3,
				impulsefactor = 0.123,
				model = "cormissile2fast.s3o",
				name = "Anti Space Rockets",
				noselfdamage = true,
				range = 410,
				reloadtime = 1,
				soundhit = "xplosml2",
				soundhitwet = "splshbig",
				soundstart = "Rocklit3",
				tolerance = 12000,
				tracks = true,
				turnrate = 20000,
				turret = true,
				weapontype = "MissileLauncher",
				startVelocity = 700,
				weaponVelocity = 700,
				canAttackGround = false,
				damage = {
					default = 40,
				},
			},
   },
		weapons = {
			[1] = {
				def = "SPACE_ROCKET",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
}{
raptor_orbital_fighter_basic_t2_v1 = {
   weapondefs = {
      weapon = {
         areaofeffect = 20,
         range = 500,
         damage = {
            default = 150,
         },
      },
   },
   weapons ={
      [1] = {
         maxangledif = 360,
         onlytargetcategory = "SPACENOTOBJECT",
      },
   },
},
raptor_orbital_bomber_basic_t2_v1 = {
   weapondefs = {
     			acidspit = {
				areaofeffect = 150,
				collidefriendly = 0,
				collidefeature = 0,
				avoidfeature = 0,
				avoidfriendly = 0,
				cegtag = "blob_trail_green",
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.63,
				explosiongenerator = "custom:acid-explosion-xl",
				impulsefactor = 0,
				intensity = 0.7,
				interceptedbyshieldtype = 1,
				name = "ACIDCANNON",
				noselfdamage = true,
				nogap = false,
				size = 9,
				sizedecay = 0.04,
				alphaDecay = 0.18,
				stages = 8,
				proximitypriority = -1,
				range = 500,
				reloadtime = 10,
				rgbcolor = "0.8 0.99 0.11",
				soundhit = "bloodsplash3",
				soundstart = "alien_bombrel",
				tolerance = 5000,
				turret = true,
				weapontype = "Cannon",
				weapontimer = 3,
				weaponvelocity = 520,
				heightBoostFactor = 0,
				customparams = {
					area_onhit_ceg = "acid-area-150-repeat",
					area_onhit_damageCeg = "acid-damage-gen",
					area_onhit_time = 10,
					area_onhit_damage = 100,
					area_onhit_range = 150,
					area_onhit_resistance = "_RAPTORACID_",
				},
				damage = {
					default = 100,
					shields = 100,
				},
			},
   },
   weapons = {
      [1] = {
				badtargetcategory = "MOBILE",
				def = "acidspit",
				onlytargetcategory = "SURFACE",
			},
   },
},
raptor_orbital_bruiser_basic_t2_v1 = {
weapondefs = {
      weapon = {
         areaofeffect = 100,
         range = 800,
         damage = {
            default = 250,
         },
      },
   },
   weapons ={
      [1] = {
         maxangledif = 360,
         onlytargetcategory = "SPACENOTOBJECT",
      },
   },
},
raptor_orbital_bomber_basic_t3_v1 = {
   weapondefs = {
      goolauncher = {
				projectiles = 6,
				areaofeffect = 150,
				collidefriendly = 0,
				collidefeature = 0,
				avoidfeature = 0,
				avoidfriendly = 0,
				cegtag = "blob_trail_red",
				craterareaofeffect = 150,
				craterboost = 0.2,
				cratermult = 0.2,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-huge",
				impulsefactor = 0.4,
				intensity = 0.7,
				interceptedbyshieldtype = 1,
				name = "GOOLAUNCHER",
				noselfdamage = true,
				proximitypriority = -1,
				range = 1000,
				reloadtime = 6,
				rgbcolor = "1 0.5 0.1",
				size = 5.5,
				sizedecay = 0.09,
				soundhit = "bombsmed2",
				soundstart = "bugarty",
				sprayangle = 300,
				tolerance = 20000,
				turret = true,
				heightBoostFactor = 0,
				weapontype = "Cannon",
				weaponvelocity = 600,
				damage = {
					default = 500,
				},
			},
		},
		weapons = {
			[1] = {
				def = "GOOLAUNCHER",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SURFACE",
			},
		},
},
raptor_orbital_battleship_basic_t3_v1 = {
   weapondefs = {
      goo = {
				areaofeffect = 250,
				avoidfeature = 0,
				avoidfriendly = 0,
				projectiles = 3,
				cegtag = "nuketrail-roost",
				flighttime = 6,
				collidefriendly = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.7,
				explosiongenerator = "custom:genericshellexplosion-large",
				firesubmersed = true,
				impulsefactor = 0,
				intensity = 0.7,
				interceptedbyshieldtype = 1,
				model = "Raptors/SGreyRock1.S3O",
				name = "Blob",
				noselfdamage = true,
				proximitypriority = -1,
				range = 1100,
				reloadtime = 1,
				rgbcolor = "0.1 0.6 1",
				size = 8,
				sizedecay = 0,
				soundhit = "e16",
				soundstart = "bigraptorroar",
				tolerance = 50000,
				turret = true,
				tracks = true,
				turnrate = 30000,
				weapontimer = 0.2,
				weaponvelocity = 1000,
				weaponAcceleration = 100,
				startvelocity = 400,
				weapontype = "MissileLauncher",
				damage = {
					default = 1200,
				},
			},
   },
   weapons = {
[1] = {
				def = "GOO",
				onlytargetcategory = "ALL SPACENOTOBJECT",
				fastautoretargeting = true,
			},
   },
},
}--NuttyB v1.52 Units Main
-- Authors: ChrispyNut, BackBash
-- docs.google.com/spreadsheets/d/1QSVsuAAMhBrhiZdTihVfSCwPzbbZWDLCtXWP23CU0ko
{cortron={energycost=42000,metalcost=3600,buildtime=110000,health=12000,weapondefs={cortron_weapon={energypershot=51000,metalpershot=600,range=4050,damage={default=9000}}}},corfort={repairable=true},armfort={repairable=true},legforti={repairable=true},armgate={explodeas='empblast',selfdestructas='empblast'},corgate={explodeas='empblast',selfdestructas='empblast'},legdeflector={explodeas='empblast',selfdestructas='empblast'},corsat={sightdistance=3100,radardistance=4080,cruisealtitude=3300,energyupkeep=1250,category="OBJECT"},armsat={sightdistance=3100,radardistance=4080,cruisealtitude=3300,energyupkeep=1250,category="OBJECT"},legstarfall={weapondefs={starfire={energypershot=270000}}},armflak={airsightdistance=1350,energycost=30000,metalcost=1500,health=4000,weapondefs={armflak_gun={collidefriendly=0,collidefeature=0,avoidfeature=0,avoidfriendly=0,areaofeffect=150,range=1150,reloadtime=0.475,weaponvelocity=2400,intensity=0.18}}},corflak={airsightdistance=1350,energycost=30000,metalcost=1500,health=4000,weapondefs={armflak_gun={collidefriendly=0,collidefeature=0,avoidfeature=0,avoidfriendly=0,areaofeffect=200,range=1350,reloadtime=0.56,weaponvelocity=2100,intensity=0.18}}},legflak={footprintx=4,footprintz=4,airsightdistance=1350,energycost=35000,metalcost=2100,health=6000,weapondefs={legflak_gun={collidefriendly=0,collidefeature=0,avoidfeature=0,avoidfriendly=0,areaofeffect=100,burst=3,range=1050,intensity=0.18}}},armmercury={airsightdistance=2200,weapondefs={arm_advsam={areaofeffect=500,energypershot=2000,explosiongenerator='custom:flak',flighttime=1.5,metalpershot=6,name='Mid-range, rapid-fire g2a guided missile launcher',range=2500,reloadtime=1.2,smoketrail=false,startvelocity=1500,weaponacceleration=1000,weaponvelocity=4000}}},corscreamer={airsightdistance=2800,weapondefs={cor_advsam={areaofeffect=800,energypershot=2000,explosiongenerator='custom:flak',flighttime=1,metalpershot=10,name='Long-range g2a guided heavy flak missile launcher',range=2800,reloadtime=1.8,smoketrail=false,startvelocity=4000,weaponacceleration=1000,weaponvelocity=8000}}},armassistdrone={buildoptions={[31]='armclaw'}},corassistdrone={buildoptions={[32]='cormaw'}},legassistdrone={buildoptions={[31]='legdtf',[32]='legdtl',[33]='legdtr'}},legfortt4={explodeas="fusionExplosionSelfd",selfdestructas="fusionExplosionSelfd"},legfort={explodeas="empblast",selfdestructas="empblast"},raptor_hive={weapondefs={antiground={burst=5,burstrate=0.01,cegtag='arty-heavy-purple',explosiongenerator='custom:dirt',model='Raptors/s_raptor_white.s3o',range=1600,reloadtime=5,rgbcolor='0.5 0 1',soundhit='smallraptorattack',soundstart='bugarty',sprayangle=256,turret=true,stockpiletime=12,proximitypriority='',damage={default=1,shields=100},customparams={spawns_count=15,spawns_expire=11,spawns_mode='random',spawns_name='raptor_acidspawnling raptor_hive_swarmer_basic raptor_land_swarmer_basic_t1_v1 ',spawns_surface='LAND SEA',stockpilelimit=10}}}},armapt3={buildoptions={[58]='armsat'}},corapt3={buildoptions={[58]='corsat'}},legapt3={buildoptions={[58]='corsat'}},armlwall={energycost=25000,metalcost=1300,weapondefs={lightning={energypershot=200,range=430}}},armclaw={collisionvolumeoffsets='0 -2 0',collisionvolumescales='30 51 30',collisionvolumetype='Ell',usepiececollisionvolumes=0,weapondefs={dclaw={energypershot=60}}},legdtl={weapondefs={dclaw={energypershot=60}}},armamd={metalcost=1800,energycost=41000,weapondefs={amd_rocket={coverage=2125,stockpiletime=70}}},corfmd={metalcost=1800,energycost=41000,weapondefs={fmd_rocket={coverage=2125,stockpiletime=70}}},legabm={metalcost=1800,energycost=41000,weapondefs={fmd_rocket={coverage=2125,stockpiletime=70}}},corwint2={metalcost=400},legwint2={metalcost=400},legdtr={buildtime=5250,energycost=5500,metalcost=400,collisionvolumeoffsets='0 -10 0',collisionvolumescales='39 88 39',collisionvolumetype='Ell',usepiececollisionvolumes=0,weapondefs={corlevlr_weapon={areaofeffect=30,avoidfriendly=true,collidefriendly=false,cegtag='railgun',range=650,energypershot=75,explosiongenerator='custom:plasmahit-sparkonly',rgbcolor='0.34 0.64 0.94',soundhit='mavgun3',soundhitwet='splshbig',soundstart='lancefire',weaponvelocity=1300,damage={default=550}}}},armrespawn={blocking=false,canresurrect=true},legnanotcbase={blocking=false,canresurrect=true},correspawn={blocking=false,canresurrect=true},legrwall={collisionvolumeoffsets="0 -3 0",collisionvolumescales="32 50 32",collisionvolumetype="CylY",energycost=21000,metalcost=1400,weapondefs={railgunt2={collidefriendly=0,collidefeature=0,avoidfeature=0,avoidfriendly=0,range=725,reloadtime=3,energypershot=200,damage={default=1500}}},weapons={[1]={def="railgunt2",onlytargetcategory="SURFACE"}}},cormwall={energycost=18000,metalcost=1350,weapondefs={exp_heavyrocket={areaofeffect=70,collidefriendly=0,collidefeature=0,cameraShake=0,energypershot=125,avoidfeature=0,avoidfriendly=0,burst=1,burstrate=0,colormap='0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008',craterareaofeffect=0,explosiongenerator='custom:burnblack',flamegfxtime=1,flighttime=1.05,name='Raptor Boomer',reloadtime=1.5,rgbcolor='1 0.25 0.1',range=700,size=2,proximitypriority={},impactonly=1,trajectoryheight=1,targetmoveerror=0.2,tracks=true,weaponacceleration=660,weaponvelocity=950,damage={default=1050}}}},cormaw={collisionvolumeoffsets='0 -2 0',collisionvolumescales='30 51 30',collisionvolumetype='Ell',usepiececollisionvolumes=false,metalcost=350,energycost=2500,weapondefs={dmaw={collidefriendly=0,collidefeature=0,areaofeffect=80,edgeeffectiveness=0.45,energypershot=50,burst=24,rgbcolor='0.051 0.129 0.871',rgbcolor2='0.57 0.624 1',sizegrowth=0.80,range=450,intensity=0.68,damage={default=28}}}},legdtf={collisionvolumeoffsets='0 -24 0',collisionvolumescales='30 51 30',collisionvolumetype='Ell',metalcost=350,energycost=2750,weapondefs={dmaw={collidefriendly=0,collidefeature=0,areaofeffect=80,edgeeffectiveness=0.45,energypershot=50,burst=24,sizegrowth=2,range=450,intensity=0.38,sprayangle=500,damage={default=30}}}},corhllllt={collisionvolumeoffsets='0 -24 0',collisionvolumescales='30 51 30',metalcost=415,energycost=9500,buildtime=10000,health=2115},corhlt={energycost=5500,metalcost=520,weapondefs={cor_laserh1={range=750,reloadtime=0.95,damage={default=395,vtol=35}}}},armhlt={energycost=5700,metalcost=510,weapondefs={arm_laserh1={range=750,reloadtime=1,damage={default=405,vtol=35}}}},armbrtha={explodeas='fusionExplosion',energycost=500000,metalcost=18500,buildtime=175000,turnrate=16000,health=10450,weapondefs={ARMBRTHA_MAIN={areaofeffect=50,collidefriendly=0,collidefeature=0,avoidfeature=0,avoidfriendly=0,beamtime=2.5,corethickness=0.1,craterareaofeffect=90,craterboost=0,cratermult=0,cameraShake=0,edgeeffectiveness=0.30,energypershot=14000,explosiongenerator='custom:laserhit-large-blue',firestarter=90,impulseboost=0,impulsefactor=0,largebeamlaser=true,laserflaresize=1,impactonly=1,name='Experimental Duction Beam',noselfdamage=true,range=2400,reloadtime=13,rgbcolor='0.4 0.2 0.6',scrollspeed=13,soundhitdry="",soundhitwet="sizzle",soundstart="hackshotxl3",soundtrigger=1,targetmoveerror=0.3,texture3='largebeam',thickness=14,tilelength=150,tolerance=10000,turret=true,turnrate=16000,weapontype='LaserCannon',weaponvelocity=3100,damage={commanders=480,default=34000}}},weapons={[1]={badtargetcategory='VTOL GROUNDSCOUT',def='ARMBRTHA_MAIN',onlytargetcategory='SURFACE'}}},corint={explodeas='fusionExplosion',energycost=505000,metalcost=19500,buildtime=170000,health=12450,footprintx=6,footprintz=6,weapondefs={CORINT_MAIN={areaofeffect=70,collidefriendly=0,collidefeature=0,avoidfeature=0,avoidfriendly=0,beamtime=2.5,corethickness=0.1,craterareaofeffect=90,craterboost=0,cratermult=0,cameraShake=0,edgeeffectiveness=0.30,energypershot=17000,explosiongenerator='custom:laserhit-large-blue',firestarter=90,impulseboost=0,impulsefactor=0,largebeamlaser=true,laserflaresize=1,impactonly=1,name='Mini DeathStar',noselfdamage=true,range=2800,reloadtime=15,rgbcolor='0 1 0',scrollspeed=13,soundhitdry='',soundhitwet='sizzle',soundstart='annigun1',soundtrigger=1,targetmoveerror=0.3,texture3='largebeam',thickness=14,tilelength=150,tolerance=10000,turret=true,turnrate=1600,weapontype='LaserCannon',weaponvelocity=3100,damage={commanders=480,default=50000}}},weapons={[1]={badtargetcategory='VTOL GROUNDSCOUT',def='CORINT_MAIN',onlytargetcategory='SURFACE'}}},leglrpc={explodeas='fusionExplosion',energycost=555000,metalcost=21000,buildtime=150000,health=11000,footprintx=6,footprintz=6,weapondefs={LEGLRPC_MAIN={areaofeffect=70,collidefriendly=0,collidefeature=0,avoidfeature=0,avoidfriendly=0,beamtime=0.5,burst=3,burstrate=0.4,corethickness=0.1,craterareaofeffect=90,craterboost=0,cratermult=0,cameraShake=0,edgeeffectiveness=0.30,energypershot=10000,explosiongenerator='custom:laserhit-large-red',firestarter=90,impactonly=1,impulseboost=0,impulsefactor=0,largebeamlaser=true,laserflaresize=1,name='The Eagle Standard',noselfdamage=true,range=2150,reloadtime=3,rgbcolor='0/1/0.4',scrollspeed=13,soundhitdry='',soundhitwet='sizzle',soundstart='lasrcrw1',soundtrigger=1,targetmoveerror=0.3,texture3='largebeam',thickness=12,tilelength=150,tolerance=10000,turret=true,turnrate=16000,weapontype='LaserCannon',weaponvelocity=3100,damage={commanders=480,default=6000}}},weapons={[1]={badtargetcategory='VTOL GROUNDSCOUT',def='LEGLRPC_MAIN',onlytargetcategory='SURFACE'}}}}--NuttyB v1.52c Legion Com
-- Authors: ChrispyNut, BackBash
-- docs.google.com/spreadsheets/d/1QSVsuAAMhBrhiZdTihVfSCwPzbbZWDLCtXWP23CU0ko
{legcom={energymake=50,metalmake=5,health=6000,autoheal=40,buildoptions={'legrezbot','legdtl','legdtf','legdtr','legjam','legwin'},customparams={evolution_target='legcomlvl2',evolution_condition='timer_global',evolution_timer=420},weapondefs={legcomlaser={corethickness=0.25,duration=0.09,name='Light close-quarters g2g/g2a laser',range=360,reloadtime=0.20,rgbcolor='0 2 1',soundhitdry='',soundhitwet='sizzle',soundstart='lasrcrw1',soundtrigger=true,sprayangle=700,thickness=6,texture1='shot',texture2='empty',weapontype='LaserCannon',weaponvelocity=2100,damage={default=250}},shotgun={areaofeffect=60,energypershot=0,avoidfeature=false,craterboost=0,cratermult=0,cameraShake=0,edgeeffectiveness=0.65,explosiongenerator='custom:genericshellexplosion-small',impulseboost=0.2,impulsefactor=0.2,intensity=3,name='6 Gauge Shotgun',noselfdamage=true,predictboost=1,projectiles=6,range=320,reloadtime=2,rgbcolor='1 0.75 0.25',size=2,soundhit='xplomed2xs',soundhitwet='splsmed',soundstart='kroggie2xs',soundstartvolume=12,sprayangle=2000,turret=true,commandfire=true,weapontimer=1,weapontype='Cannon',weaponvelocity=600,stockpile=true,stockpiletime=5,customparams={stockpilelimit=10},damage={default=1800,commanders=0}}},weapons={[3]={def='shotgun',onlytargetcategory='SURFACE'}}},legcomlvl2={energymake=150,metalmake=15,speed=57.5,autoheal=100,health=6700,customparams={evolution_condition='timer_global',evolution_timer=1020},buildoptions={'legrezbot','legadvsol','corhllt','leggeo','legnanotc','legjam','legdtf','legmg','legrad','legdtl','legdtr','legrhapsis','legwin'},weapondefs={legcomlaser={accuracy=50,areaofeffect=12,avoidfriendly=false,avoidfeature=false,collidefriendly=false,collidefeature=true,beamtime=0.09,corethickness=0.3,duration=0.09,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=1,impulseboost=0,impulsefactor=0,name='Light close-quarters g2g/g2a laser',noselfdamage=true,range=500,reloadtime=0.2,rgbcolor='0 0.95 0.05',soundhitdry='',soundhitwet='sizzle',soundstart='lasrcrw1',soundtrigger=true,sprayangle=500,targetmoveerror=0.05,thickness=7,tolerance=1000,texture1='shot',texture2='empty',turret=true,weapontype='LaserCannon',weaponvelocity=2200,damage={bombers=180,default=450,fighters=110,subs=5}},shotgun={areaofeffect=65,energypershot=0,avoidfeature=false,craterboost=0,cratermult=0,cameraShake=0,edgeeffectiveness=0.65,explosiongenerator='custom:genericshellexplosion-small',impulseboost=0.2,impulsefactor=0.2,intensity=3,name='12 Gauge Shotgun',noselfdamage=true,predictboost=1,projectiles=7,range=440,reloadtime=2,rgbcolor='1 0.75 0.25',size=2.5,soundhit='xplomed2xs',soundhitwet='splsmed',soundstart='kroggie2xs',soundstartvolume=12,sprayangle=2250,turret=true,commandfire=true,weapontimer=1,weapontype='Cannon',weaponvelocity=600,stockpile=true,stockpiletime=5,customparams={stockpilelimit=15},damage={default=2200,commanders=0}}},weapons={[1]={def='legcomlaser',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={def='shotgun',onlytargetcategory='SURFACE'}}},legcomlvl3={energymake=1280,metalmake=40,speed=70.5,workertime=700,autoheal=150,health=7500,customparams={evolution_condition='timer_global',evolution_timer=1440},buildoptions={'legdeflector','legfus','legbombard','legadvestore','legmoho','legadveconv','legarad','legajam','legforti','legacluster','legamstor','legflak','legabm','legbastion','legdtr','legdtf','legrezbot','legdtl','leglab','legendary_bastion','legnanotct3','legapopupdef'},weapondefs={legcomlaser={accuracy=50,areaofeffect=12,avoidfriendly=true,avoidfeature=true,collidefriendly=false,collidefeature=true,beamtime=0.09,corethickness=0.55,duration=0.09,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=0,impulseboost=0,impulsefactor=0,name='Light close-quarters g2g/g2a laser',noselfdamage=true,range=640,reloadtime=0.2,rgbcolor='0 0.2 0.8',soundhitdry='',soundhitwet='sizzle',soundstart='lasrcrw1',soundtrigger=true,sprayangle=500,targetmoveerror=0.05,thickness=7,tolerance=1000,texture1='shot',texture2='empty',turret=true,weapontype='LaserCannon',weaponvelocity=2500,damage={bombers=180,default=650,fighters=110,subs=5}},shotgun={areaofeffect=90,energypershot=0,avoidfeature=false,craterboost=0,cratermult=0,cameraShake=0,edgeeffectiveness=0.65,explosiongenerator='custom:genericshellexplosion-small',impulseboost=0.2,impulsefactor=0.2,intensity=3,name='12 Gauge Shotgun',noselfdamage=true,predictboost=1,projectiles=7,range=540,reloadtime=2,rgbcolor='1 0.75 0.25',size=2.5,soundhit='xplomed2xs',soundhitwet='splsmed',soundstart='kroggie2xs',soundstartvolume=12,sprayangle=2500,turret=true,commandfire=true,weapontimer=1,weapontype='Cannon',weaponvelocity=600,stockpile=true,stockpiletime=5,customparams={stockpilelimit=20},damage={default=3200,commanders=0}}},weapons={[1]={def='legcomlaser',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={def='shotgun',onlytargetcategory='SURFACE'},[5]={def=''}}},legcomlvl4={energymake=1980,metalmake=46,speed=88.5,workertime=1000,autoheal=180,health=24500,customparams={evolution_condition='timer_global',evolution_timer=1740},buildoptions={'legdeflector','legfus','legbombard','legadvestore','legmoho','legadveconv','legeshotgunmech','legarad','legajam','legkeres','legacluster','legamstor','legflak','legabm','legbastion','legendary_bastion','legnanotct2','legnanotct2plat','legrwall','leglab','legtarg','legsd','legpede','legerailtank','legeheatraymech','legrezbot','legafus','leglraa','legdtl','legdtf','legministarfall','legstarfall','leggatet3','legperdition','legsilo','legsrailt4','legelrpcmech','legdtr','legnanotct3','legapopupdef'},weapondefs={legcomlaser={accuracy=50,areaofeffect=12,avoidfriendly=true,avoidfeature=true,collidefriendly=false,collidefeature=true,beamtime=0.1,corethickness=.5,duration=0.09,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=0,impulseboost=0,impulsefactor=0,name='Light close-quarters g2g/g2a laser',noselfdamage=true,range=900,reloadtime=0.1,rgbcolor='0.45 0 1',soundhitdry='',soundhitwet='sizzle',soundstart='lasrcrw1',soundtrigger=1,sprayangle=400,targetmoveerror=0.05,thickness=6,tolerance=1000,texture1='shot',texture2='empty',turret=true,weapontype='LaserCannon',weaponvelocity=3000,damage={bombers=180,default=1750,fighters=110,subs=5}},shotgun={areaofeffect=75,energypershot=0,avoidfeature=false,craterboost=0,cratermult=0,cameraShake=0,edgeeffectiveness=0.65,explosiongenerator='custom:genericshellexplosion-small',impulseboost=0.2,impulsefactor=0.2,intensity=3,name='60 Gauge Raptor Popper',noselfdamage=true,predictboost=1,projectiles=9,range=550,reloadtime=1,rgbcolor='1 0.75 0.25',size=5,soundhit='xplomed2xs',soundhitwet='splsmed',soundstart='kroggie2xs',soundstartvolume=12,sprayangle=3000,turret=true,commandfire=true,weapontimer=1,weapontype='Cannon',weaponvelocity=600,stockpile=true,stockpiletime=4,customparams={stockpilelimit=20},damage={default=4400,commanders=0}}},weapons={[1]={def='legcomlaser',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={def='shotgun',onlytargetcategory='SURFACE'},[5]={def=''}}},legcomlvl5={energymake=2280,metalmake=64,speed=100,workertime=1700,autoheal=4500,health=53900,buildoptions={'legdeflector','legfus','legbombard','legadvestore','legmoho','legadveconv','legeshotgunmech','legarad','legajam','legkeres','legacluster','legamstor','legflak','legabm','legbastion','legendary_bastion','legnanotct2','legnanotct2plat','legrwall','leglab','legtarg','legsd','legpede','legerailtank','legeheatraymech','legrezbot','legafus','leglraa','legdtl','legdtf','legministarfall','legstarfall','leggatet3','legperdition','legsilo','legsrailt4','legelrpcmech','legdtr','legnanotct3','legapopupdef'},weapondefs={machinegun={accuracy=80,areaofeffect=10,avoidfeature=false,beamburst=true,beamdecay=1,beamtime=0.07,burst=6,burstrate=0.10667,camerashake=0,corethickness=0.35,craterareaofeffect=0,craterboost=0,cratermult=0,edgeeffectiveness=1,explosiongenerator="custom:laserhit-medium-red",firestarter=10,impulsefactor=0,largebeamlaser=true,laserflaresize=30,name="Rapid-fire close quarters g2g armor-piercing laser",noselfdamage=true,pulsespeed=q8,range=1100,reloadtime=0.50,rgbcolor="0.7 0.3 1.0",rgbcolor2="0.8 0.6 1.0",soundhitdry="",soundhitwet="sizzle",soundstart="lasfirerc",soundtrigger=1,sprayangle=500,targetborder=0.2,thickness=5.5,tolerance=4500,turret=true,weapontype="BeamLaser",weaponvelocity=920,damage={default=1300,vtol=180}},shotgunarm={areaofeffect=112,commandfire=true,avoidfeature=false,craterboost=0,cratermult=0,cameraShake=0,edgeeffectiveness=0.65,explosiongenerator="custom:genericshellexplosion-medium",impulsefactor=0.8,intensity=0.2,mygravity=1,name="GaussCannon",noselfdamage=true,predictboost=1,projectiles=20,range=650,reloadtime=1,rgbcolor="0.8 0.4 1.0",size=4,sizeDecay=0.044,stages=16,alphaDecay=0.66,soundhit="xplomed2xs",soundhitwet="splsmed",soundstart="kroggie2xs",sprayangle=3500,tolerance=6000,turret=true,waterweapon=true,weapontimer=2,weapontype="Cannon",weaponvelocity=900,stockpile=true,stockpiletime=2,customparams={stockpilelimit=50},damage={default=10000,commanders=0}},exp_heavyrocket={areaofeffect=70,collidefriendly=0,collidefeature=0,cameraShake=0,energypershot=125,avoidfeature=0,avoidfriendly=0,burst=4,burstrate=0.3,cegtag="missiletrailsmall-red",colormap='0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008',craterboost=0,craterareaofeffect=0,cratermult=0,dance=24,edgeeffectiveness=0.65,explosiongenerator="custom:burnblack",firestarter=70,flighttime=1.05,flamegfxtime=1,impulsefactor=0.123,impactonly=1,model="catapultmissile.s3o",movingaccuracy=600,name="Raptor Boomer",noselfdamage=true,proximitypriority={},range=700,reloadtime=1,smoketrail=true,smokePeriod=4,smoketime=16,smokesize=8.5,smokecolor=0.5,size=2,smokeTrailCastShadow=false,soundhit="rockhit",soundhitwet="splsmed",soundstart="rapidrocket3",startvelocity=165,rgbcolor='1 0.25 0.1',texture1="null",texture2="smoketrailbar",trajectoryheight=1,targetmoveerror=0.2,turnrate=5000,tracks=true,turret=true,allowNonBlockingAim=true,weaponacceleration=660,weapontimer=6,weapontype="MissileLauncher",weaponvelocity=950,wobble=2000,damage={default=1300},customparams={exclude_preaim=true,overrange_distance=777,projectile_destruction_method="descend"}}},weapons={[1]={def='machinegun',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={def='shotgunarm',onlytargetcategory='WEAPON'},[5]={def='exp_heavyrocket',onlytargetcategory='SURFACE'}}}}--NuttyB v1.52c Armada Com
-- Authors: ChrispyNut, BackBash
-- docs.google.com/spreadsheets/d/1QSVsuAAMhBrhiZdTihVfSCwPzbbZWDLCtXWP23CU0ko
{armcom={customparams={evolution_target='armcomlvl2',evolution_condition='timer_global',evolution_timer=420},energymake=100,metalmake=10,autoheal=55,health=4500,speed=41,canresurrect=true,buildoptions={'armsolar','armwin','armmstor','armestor','armmex','armmakr','armlab','armvp','armap','armeyes','armrad','armdrag','armllt','armrl','armdl','armtide','armuwms','armuwes','armuwmex','armfmkr','armsy','armfdrag','armtl','armfrt','armfrad','armhp','armfhp','armgeo','armamex','armhp','armbeamer','armjamt','armsy','armrectr','armclaw'},weapondefs={armcomlaser={range=330,rgbcolor='0.7 1 1',soundstart='lasrfir1',damage={default=175}},old_armsnipe_weapon={areaofeffect=32,avoidfeature=true,avoidfriendly=true,collidefeature=true,collidefriendly=false,corethickness=0.75,craterareaofeffect=0,craterboost=0,commandfire=true,cratermult=0,cegtag='railgun',duration=0.12,edgeeffectiveness=0.85,energypershot=400,explosiongenerator='custom:laserhit-large-blue',firestarter=100,impulseboost=0.4,impulsefactor=1,intensity=0.8,name='Long-range g2g armor-piercing rifle',range=550,reloadtime=1,rgbcolor='0 1 1',rgbcolor2='0 1 1',soundhit='sniperhit',soundhitwet='sizzle',soundstart='sniper3',soundtrigger=true,stockpile=true,stockpiletime=7,customparams={stockpilelimit=5},texture1='shot',texture2='empty',thickness=4,tolerance=1000,turret=true,weapontype='LaserCannon',weaponvelocity=3000,damage={commanders=100,default=4900}}},weapons={[3]={def='old_armsnipe_weapon',onlytargetcategory='NOTSUB'}}},armcomlvl2={autoheal=90,builddistance=175,canresurrect=true,energymake=315,health=7000,speed=57.5,metalmake=20,workertime=900,buildoptions={'armsolar','armwin','armmstor','armestor','armmex','armmakr','armlab','armvp','armap','armeyes','armrad','armdrag','armllt','armrl','armdl','armtide','armuwms','armuwes','armuwmex','armfmkr','armsy','armfdrag','armtl','armfrt','armfrad','armhp','armfhp','armadvsol','armgeo','armamex','armnanotcplat','armhp','armnanotc','armclaw','armbeamer','armhlt','armguard','armferret','armcir','armjamt','armjuno','armsy','armrectr'},customparams={evolution_target='armcomlvl3',evolution_condition='timer_global',evolution_timer=1320},weapondefs={armcomlaser={areaofeffect=16,avoidfeature=false,beamtime=0.1,corethickness=0.1,craterareaofeffect=0,craterboost=0,cratermult=0,cylindertargeting=1,edgeeffectiveness=1,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=1,impulseboost=0,impulsefactor=0,laserflaresize=7.7,name='Light close-quarters g2g/g2a laser',noselfdamage=true,range=425,reloadtime=0.7,rgbcolor='0 1 1',soundhitdry='',soundhitwet='sizzle',soundstart='lasrfir1',soundtrigger=1,targetmoveerror=0.05,thickness=4,tolerance=10000,turret=true,weapontype='BeamLaser',weaponvelocity=900,damage={default=950,VTOL=150}},old_armsnipe_weapon={areaofeffect=42,avoidfeature=true,avoidfriendly=true,collidefeature=true,collidefriendly=false,corethickness=0.75,craterareaofeffect=0,craterboost=0,commandfire=true,cratermult=0,cegtag='railgun',duration=0.12,edgeeffectiveness=0.85,energypershot=700,explosiongenerator='custom:laserhit-large-blue',firestarter=100,impulseboost=0.4,impulsefactor=1,intensity=1,name='Long-range g2g armor-piercing rifle',range=700,reloadtime=1,rgbcolor='0.2 0.1 1',rgbcolor2='0.2 0.1 1',soundhit='sniperhit',soundhitwet='sizzle',soundstart='sniper3',soundtrigger=true,stockpile=true,stockpiletime=6,customparams={stockpilelimit=10},texture1='shot',texture2='empty',thickness=4,tolerance=1000,turret=true,weapontype='LaserCannon',weaponvelocity=3000,damage={commanders=10,default=11000}}},weapons={[1]={def='armcomlaser',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={def='old_armsnipe_weapon',onlytargetcategory='NOTSUB'}}},armcomlvl3={autoheal=50,builddistance=250,canresurrect=true,energymake=2712,health=10000,speed=71.5,metalmake=62,workertime=1500,buildoptions={'armanni','armpb','armamb','armmoho','armuwmme','armflak','armmercury','armgate','armsd','armfort','armtarg','armarad','armamd','armveil','armuwadvms','armuwadves','armmmkr','armclaw','armjuno','armuwmex','armhp','armsy','armfdrag','armtl','armfrt','armfrad','armhp','armlab','armvp','armap','armsy','armuwmmm','armuwfus','armplat','armfdrag','armfhlt','armfflak','armatl','armkraken','armnanotcplat','armbrtha','armannit3','armlwall','armnanotct2','armafus','armfus','armckfus','armraz','armzeus','armsnipe','armvang','armrectr','armgatet3','legendary_pulsar','armnanotct3'},customparams={evolution_target='armcomlvl4',evolution_condition='timer_global',evolution_timer=1740},weapondefs={old_armsnipe_weapon={areaofeffect=64,avoidfeature=true,avoidfriendly=true,collidefeature=true,collidefriendly=false,corethickness=0.75,craterareaofeffect=0,craterboost=0,commandfire=true,cratermult=0,cegtag='railgun',duration=0.12,edgeeffectiveness=1,energypershot=2000,explosiongenerator='custom:laserhit-large-blue',firestarter=100,impulseboost=0.4,impulsefactor=1,intensity=1.4,name='Long-range g2g armor-piercing rifle',range=1250,reloadtime=.5,rgbcolor='0.4 0.1 0.7',rgbcolor2='0.4 0.1 0.7',soundhit='sniperhit',soundhitwet='sizzle',soundstart='sniper3',soundtrigger=true,stockpile=true,stockpiletime=3,customparams={stockpilelimit=10},texture1='shot',texture2='empty',thickness=6,tolerance=1000,turret=true,weapontype='LaserCannon',weaponvelocity=3000,damage={commanders=10,default=35000}},armcomlaser={areaofeffect=12,avoidfeature=false,beamtime=0.1,corethickness=0.1,craterareaofeffect=0,craterboost=0,cratermult=0,cylindertargeting=1,edgeeffectiveness=1,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=1,impulseboost=0,impulsefactor=0,laserflaresize=7.7,name='Light close-quarters g2g/g2a laser',noselfdamage=true,range=500,reloadtime=0.6,rgbcolor='0.1 0 1',soundhitdry='',soundhitwet='sizzle',soundstart='lasrcrw2',soundtrigger=1,targetmoveerror=0.05,thickness=6,tolerance=10000,turret=true,weapontype='BeamLaser',weaponvelocity=900,damage={default=1450,VTOL=180}}},weapons={[5]={badtargetcategory='MOBILE',def='armcomlaser',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={def='old_armsnipe_weapon',onlytargetcategory='NOTSUB'},[4]={def=''},[1]={def=''},[6]={def=''}}},armcomlvl4={autoheal=150,builddistance=300,canresurrect=true,energymake=3112,health=20000,speed=82,metalmake=86,workertime=2000,buildoptions={'armanni','armpb','armamb','armmoho','armuwmme','armflak','armmercury','armgate','armsd','armfort','armtarg','armarad','armamd','armveil','armuwadvms','armuwadves','armmmkr','armclaw','armjuno','armuwmex','armhp','armsy','armfdrag','armtl','armfrt','armfrad','armhp','armlab','armvp','armap','armsy','armuwmmm','armuwfus','armplat','armfdrag','armfhlt','armfflak','armatl','armkraken','armnanotcplat','armbrtha','armannit3','armlwall','armnanotct2','armafus','armfus','armckfus','armraz','armzeus','armsnipe','armvang','armrectr','armgatet3','legendary_pulsar','armnanotct3'},weapondefs={old_armsnipe_weapon={areaofeffect=72,avoidfeature=true,avoidfriendly=true,collidefeature=true,collidefriendly=false,corethickness=0.75,craterareaofeffect=0,craterboost=0,commandfire=true,cratermult=0,cegtag='railgun',duration=0.12,edgeeffectiveness=1,energypershot=2000,explosiongenerator='custom:laserhit-large-blue',firestarter=100,impulseboost=0.4,impulsefactor=1,intensity=1.4,name='Long-range g2g armor-piercing rifle',range=1250,reloadtime=.5,rgbcolor='0.4 0.1 0.7',rgbcolor2='0.4 0.1 0.7',soundhit='sniperhit',soundhitwet='sizzle',soundstart='sniper3',soundtrigger=true,stockpile=true,stockpiletime=2,customparams={stockpilelimit=15},texture1='shot',texture2='empty',thickness=6,tolerance=1000,turret=true,weapontype='LaserCannon',weaponvelocity=3000,damage={commanders=10,default=45000}},ata={areaofeffect=16,avoidfeature=false,beamtime=1.25,collidefriendly=false,corethickness=0.5,craterareaofeffect=0,craterboost=0,cratermult=0,edgeeffectiveness=0.30,energypershot=7000,explosiongenerator='custom:laserhit-large-blue',firestarter=90,impulsefactor=0,largebeamlaser=true,laserflaresize=7,name='Heavy long-range g2g tachyon accelerator beam',noselfdamage=true,range=1100,reloadtime=15,rgbcolor='1 0 1',scrollspeed=5,soundhitdry='',soundhitwet='sizzle',soundstart='annigun1',soundtrigger=1,texture3='largebeam',thickness=10,tilelength=150,tolerance=10000,turret=true,weapontype='BeamLaser',weaponvelocity=3100,damage={commanders=480,default=48000}},armcomlaser={areaofeffect=12,avoidfeature=false,beamtime=0.1,corethickness=0.1,craterareaofeffect=0,craterboost=0,cratermult=0,cylindertargeting=1,edgeeffectiveness=1,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=1,impulseboost=0,impulsefactor=0,laserflaresize=7.7,name='Light close-quarters g2g/g2a laser',noselfdamage=true,range=550,reloadtime=0.5,rgbcolor='0.659 0 1',soundhitdry='',soundhitwet='sizzle',soundstart='lasrcrw2',soundtrigger=1,targetmoveerror=0.05,thickness=6,tolerance=10000,turret=true,weapontype='BeamLaser',weaponvelocity=900,damage={default=1750,VTOL=200}}},weapons={[1]={def='armcomlaser',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={def='old_armsnipe_weapon',onlytargetcategory='NOTSUB'},[4]={badtargetcategory='VTOL GROUNDSCOUT',def='ATA',onlytargetcategory='SURFACE'},[5]={def=''},[6]={def=''}}}}--NuttyB v1.52c Cortex Com
-- Authors: ChrispyNut, BackBash
-- docs.google.com/spreadsheets/d/1QSVsuAAMhBrhiZdTihVfSCwPzbbZWDLCtXWP23CU0ko
{corcom={customparams={evolution_target='corcomlvl2',evolution_condition='timer_global',evolution_timer=420},autoheal=80,speed=45,energymake=75,metalmake=6,health=5500,buildoptions={[28]='corhllt',[29]='cornecro',[30]='corlevlr',[31]='corak',[32]='cormaw'},weapondefs={corcomlaser={range=370,damage={bombers=180,default=260,fighters=110,subs=5}},disintegrator={energypershot=1000,reloadtime=8}}},corcomlvl2={speed=62,health=8500,energymake=255,metalmake=16,autoheal=300,builddistance=200,workertime=600,buildoptions={[1]='corsolar',[2]='coradvsol',[3]='corwin',[4]='corgeo',[5]='cormstor',[6]='corestor',[7]='cormex',[8]='corexp',[9]='cormakr',[10]='corcan',[11]='correap',[12]='corlab',[13]='corvp',[14]='corap',[15]='corhp',[16]='cornanotc',[17]='coreyes',[18]='corrad',[19]='cordrag',[20]='cormaw',[21]='corllt',[22]='corhllt',[23]='corhlt',[24]='corpun',[25]='corrl',[26]='cormadsam',[27]='corerad',[28]='cordl',[29]='corjamt',[30]='corjuno',[31]='corsy',[32]='coruwgeo',[33]='corfasp',[34]='cornerco',[35]='coruwes',[36]='corplat',[37]='corfhp',[38]='coruwms',[39]='corfhlt',[40]='cornanotcplat',[41]='corfmkr',[42]='cortide',[43]='corfrad',[44]='corfrt',[45]='corfdrag',[46]='cortl',[47]='cornecro'},customparams={evolution_target='corcomlvl3',evolution_condition='timer_global',evolution_timer=1320,shield_power=500,shield_radius=100},weapondefs={armcomlaser={areaofeffect=16,avoidfeature=false,beamtime=0.1,corethickness=0.1,craterareaofeffect=0,craterboost=0,cratermult=0,cylindertargeting=1,edgeeffectiveness=1,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=1,impulseboost=0,impulsefactor=0,laserflaresize=7.7,name='Light close-quarters g2g/g2a laser',noselfdamage=true,range=500,reloadtime=0.4,rgbcolor='0.6 0.3 0.8',soundhitdry='',soundhitwet='sizzle',soundstart='lasrfir1',soundtrigger=1,targetmoveerror=0.05,thickness=4,tolerance=10000,turret=true,weapontype='BeamLaser',weaponvelocity=900,damage={bombers=180,default=1500,fighters=110,subs=5}},disintegrator={areaofeffect=36,avoidfeature=false,avoidfriendly=false,avoidground=false,bouncerebound=0,cegtag='dgunprojectile',commandfire=true,craterboost=0,cratermult=0.15,edgeeffectiveness=0.15,energypershot=500,explosiongenerator='custom:expldgun',firestarter=100,firesubmersed=false,groundbounce=true,impulseboost=0,impulsefactor=0,name='Disintegrator',noexplode=true,noselfdamage=true,range=250,reloadtime=6,paralyzer={},soundhit='xplomas2s',soundhitwet='sizzlexs',soundstart='disigun1',soundhitvolume=36,soundstartvolume=96,soundtrigger=true,tolerance=10000,turret=true,waterweapon=true,weapontimer=4.2,weapontype='DGun',weaponvelocity=300,damage={commanders=0,default=20000,raptors=10000}}},weapons={[1]={def='armcomlaser',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={def='DISINTEGRATOR',onlytargetcategory='NOTSUB'}}},corcomlvl3={speed=80,health=30000,energymake=2180,metalmake=49,autoheal=1500,workertime=1200,builddistance=250,buildoptions={[1]='corfus',[2]='corafus',[3]='corageo',[4]='corbhmth',[5]='cormoho',[6]='cormexp',[7]='cormmkr',[8]='coruwadves',[9]='coruwadvms',[10]='corarad',[11]='corshroud',[12]='corfort',[13]='corlab',[14]='cortarg',[15]='corsd',[16]='corgate',[17]='cortoast',[18]='corvipe',[19]='cordoom',[20]='corflak',[21]='corscreamer',[22]='corvp',[23]='corfmd',[24]='corap',[25]='corint',[26]='corplat',[27]='corsy',[28]='coruwmme',[29]='coruwmmm',[30]='corenaa',[31]='corfdoom',[32]='coratl',[33]='coruwfus',[34]='corjugg',[35]='corshiva',[36]='corsumo',[37]='corgol',[38]='corkorg',[39]='cornanotc2plat',[40]='cornanotct2',[41]='cornecro',[42]='cordoomt3',[43]='corhllllt',[44]='cormaw',[45]='cormwall',[46]='corgatet3',[47]='legendary_bulwark',[48]='cornanotct3'},customparams={evolution_target='corcomlvl4',evolution_condition='timer_global',evolution_timer=1740},weapondefs={corcomlaser={areaofeffect=12,avoidfeature=false,beamtime=0.1,corethickness=0.1,craterareaofeffect=0,craterboost=0,cratermult=0,cylindertargeting=1,edgeeffectiveness=1,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=1,impulseboost=0,impulsefactor=0,laserflaresize=5.5,name='J7Laser',noselfdamage=true,range=900,reloadtime=0.4,rgbcolor='0.7 0 1',soundhitdry='',soundhitwet='sizzle',soundstart='lasrfir1',soundtrigger=1,targetmoveerror=0.05,thickness=3,tolerance=10000,turret=true,weapontype='BeamLaser',weaponvelocity=900,damage={default=2000,subs=5}},disintegrator={areaofeffect=36,avoidfeature=false,avoidfriendly=false,avoidground=false,bouncerebound=0,cegtag='dgunprojectile',commandfire=true,craterboost=0,cratermult=0.15,edgeeffectiveness=0.15,energypershot=500,explosiongenerator='custom:expldgun',firestarter=100,firesubmersed=false,groundbounce=true,impulseboost=0,impulsefactor=0,name='Disintegrator',noexplode=true,noselfdamage=true,range=250,reloadtime=3,paralyzer={},soundhit='xplomas2s',soundhitwet='sizzlexs',soundstart='disigun1',soundhitvolume=36,soundstartvolume=96,soundtrigger=true,size=4,tolerance=10000,turret=true,waterweapon=true,weapontimer=4.2,weapontype='DGun',weaponvelocity=300,damage={commanders=0,default=20000,scavboss=1000,raptors=10000}}},weapons={[1]={def='CORCOMLASER',onlytargetcategory='NOTSUB',fastautoretargeting=true},[5]={def=''}}},corcomlvl4={speed=80,health=50000,energymake=2380,metalmake=56,autoheal=3550,workertime=1800,builddistance=300,buildoptions={[1]='corfus',[2]='corafus',[3]='corageo',[4]='corbhmth',[5]='cormoho',[6]='cormexp',[7]='cormmkr',[8]='coruwadves',[9]='coruwadvms',[10]='corarad',[11]='corshroud',[12]='corfort',[13]='corlab',[14]='cortarg',[15]='corsd',[16]='corgate',[17]='cortoast',[18]='corvipe',[19]='cordoom',[20]='corflak',[21]='corscreamer',[22]='corvp',[23]='corfmd',[24]='corap',[25]='corint',[26]='corplat',[27]='corsy',[28]='coruwmme',[29]='coruwmmm',[30]='corenaa',[31]='corfdoom',[32]='coratl',[33]='coruwfus',[34]='corjugg',[35]='corshiva',[36]='corsumo',[37]='corgol',[38]='corkorg',[39]='cornanotc2plat',[40]='cornanotct2',[41]='cornecro',[42]='cordoomt3',[43]='corhllllt',[44]='cormaw',[45]='cormwall',[46]='corgatet3',[47]='legendary_bulwark',[48]='cornanotct3'},customparams={shield_power=500,shield_radius=100},weapondefs={CORCOMLASER={areaofeffect=12,avoidfeature=false,beamtime=0.1,corethickness=0.1,craterareaofeffect=0,craterboost=0,cratermult=0,cylindertargeting=1,edgeeffectiveness=1,explosiongenerator='custom:laserhit-small-red',firestarter=70,impactonly=1,impulseboost=0,impulsefactor=0,laserflaresize=5.5,name='J7Laser',noselfdamage=true,range=1000,reloadtime=0.4,rgbcolor='0.7 0 1',soundhitdry='',soundhitwet='sizzle',soundstart='lasrfir1',soundtrigger=1,targetmoveerror=0.05,thickness=3,tolerance=10000,turret=true,weapontype='BeamLaser',weaponvelocity=900,damage={default=2500,subs=5}},disintegratorxl={areaofeffect=105,avoidfeature=false,avoidfriendly=true,avoidground=false,burst=1,burstrate=0,bouncerebound=0,cegtag='gausscannonprojectilexl',craterareaofeffect=0,craterboost=0,cratermult=0,commandfire=true,cameraShake=0,edgeeffectiveness=1,energypershot=0,explosiongenerator='custom:burnblackbiggest',firestarter=100,firesubmersed=false,gravityaffected=true,impulsefactor=0,intensity=4,name='Darkmatter Photon-Disruptor',noexplode=true,noselfdamage=true,range=500,reloadtime=1,rgbcolor='0.7 0.3 1.0',size=5.5,soundhit='xplomas2',soundhitwet='sizzlexs',soundstart='disigun1',soundtrigger=true,tolerance=10000,turret=true,weapontimer=4.2,weapontype='DGun',weaponvelocity=505,damage={commanders=0,default=20000,scavboss=1000,raptors=10000}},corcomeyelaser={allowNonBlockingAim=true,avoidfriendly=true,areaofeffect=6,avoidfeature=false,beamtime=0.033,camerashake=0.1,collidefriendly=false,corethickness=0.35,craterareaofeffect=12,craterboost=0,cratermult=0,edgeeffectiveness=1,energypershot=0,explosiongenerator='custom:laserhit-small-red',firestarter=90,firetolerance=300,impulsefactor=0,laserflaresize=2,name='EyeLaser',noselfdamage=true,proximitypriority=1,range=870,reloadtime=0.033,rgbcolor='0 1 0',rgbcolor2='0.8 0 0',scrollspeed=5,soundhitdry='flamhit1',soundhitwet='sizzle',soundstart='heatray3burn',soundstartvolume=6,soundtrigger=1,thickness=2.5,turret=true,weapontype='BeamLaser',weaponvelocity=1500,damage={default=185}}},weapons={[1]={def='CORCOMLASER',onlytargetcategory='NOTSUB',fastautoretargeting=true},[3]={badtargetcategory='VTOL',def='disintegratorxl',onlytargetcategory='SURFACE'},[6]={def=''},[5]={badtargetcategory='VTOL GROUNDSCOUT',def='corcomeyelaser',onlytargetcategory='SURFACE'}}}}