{
legparagon = {
weapondefs = {
			plasma = {
				customparams = {
					carried_unit = "legparadrone",     --Name of the unit spawned by this carrier unit.
				}
			},
		},
},
armfirewall = {
weapondefs = {
			lightning = {
				burst = 4,
				burstrate = 0.02,
				range = 500,
				reloadtime = 0.1,
				paralyzer = true,
				paralyzetime = 8,
				customparams = {
spark_maxunits = 0
				},
				damage = {
					default = 40,
				},
			},
},
		weapons = {
			[1] = {
				def = "lightning",
				onlytargetcategory = "NOTSUB",
				fastautoretargeting = true,
			},
		},
},
corageot3 = {
weapondefs = {
cor_georockets = {
				areaofeffect = 200,
				avoidfeature = true,
				avoidfriendly = false,
				burnblow = true,
				canattackground = true,
				castshadow = false,
				cegtag = "missiletrailaa-large",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 200,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.6,
				energypershot = 0,
				explosiongenerator = "custom:genericshellexplosion-huge-aa",
				firestarter = 90,
				flighttime = 10,
				impulsefactor = 0,
				metalpershot = 0,
				model = "corscreamermissile.s3o",
				name = "Long Range Seeker Rocket Platform",
				noselfdamage = true,
				proximitypriority = -1,
				range = 1400,
				reloadtime = 1.2,
				smokecolor = 0.9,
				smokeperiod = 2,
				smokesize = 4,
				smoketime = 24,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "impact",
				soundhitvolume = 8,
				soundhitwet = "splslrg",
				soundstart = "aarocket",
				soundstartvolume = 8,
				startvelocity = 1000,
				texture1 = "null",
				texture2 = "smoketrailaaflak",
				tolerance = 10000,
				tracks = true,
				trajectoryheight = 2,
				turnrate = 40000,
				turret = true,
				weapontimer = 1,
				weaponacceleration = 1000,
				weapontype = "StarburstLauncher",
				weaponvelocity = 1400,
				damage = {
					default  = 900,
					vtol = 2000,
					commander = 450,
				},
			},
},
weapons = {
[1] = {
				def = "COR_GEOROCKETS",
				fastautoretargeting = true,
				onlytargetcategory = "NOTSUB",
    },
},
},
armspace ={
buildoptions = {
"armoc",
"armosat",
"armofighter",
"armocan",
"armosolar",
"armobruiser",
"armotachyon",
},
},
armspacet3 = {
buildoptions = {
"armoc",
"armobomber",
"armohorizon",
"armokaiser",
"armoliberator",
},
},
armofighter = {
weapondefs = {
			lightlaser = {
				collidefriendly = false,
				collidefeature = false,
				areaofeffect = 12,
				avoidfeature = false,
				avoidfriendly = false,
				beamtime = 0.12,
				corethickness = 0.175,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:laserhit-small-red",
				firestarter = 30,
				impactonly = 1,
				impulsefactor = 0,
				laserflaresize = 7,
				name = "Light orbital laser",
				noselfdamage = true,
				range = 400,
				reloadtime = 0.8,
				rgbcolor = "0.05 0.05 1",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				proximitypriority = 1,
				soundtrigger = 1,
				thickness = 2,
				tolerance = 50000,
				turret = false,
				weapontype = "BeamLaser",
				weaponvelocity = 2250,
				minIntensity = 0.5,
				damage = {
					default = 35,
				},
			},
		},
		weapons = {
			[1] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
[2] = {
				def = "LIGHTLASER",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armocan = {
weapondefs = {
			Orbital_Cannon = {
				areaofeffect = 300,
				avoidfeature = false,
				avoidfriendly = false,      
				craterareaofeffect = 0,
				collidefriendly = false,
				collidefeature = false,
				canattackground = true,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.5,
				explosiongenerator = "custom:genericshellexplosion-medium",
				firestarter = 10,
				impulsefactor = 1,
				name = "Orbital Bombardment",
				tolerance = 65000,
				noselfdamage = true,
				range = 100,
				reloadtime = 10,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "KroGun1",
				turret = true,
				weapontimer = 1,
				weapontype = "Cannon",
				weaponvelocity = 500,
				damage = {
					default = 500,
					shield = 100,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_CANNON",
				maindir = "0 -1 0",
				maxangledif = 90,
				onlytargetcategory = "SURFACE",
			},
		},
},
armorocket = {
weapondefs = {
			orbital_rocket = {
				areaofeffect = 250,
				alwaysvisible = true,
				canattackground = false,
				collideenemy = true,
				cegtag = "cruisemissiletrail-tacnuke",
				cylindertargeting = 1,
				energypershot = 0,
				explosiongenerator = "custom:newnuketac",
				firestarter = 10,
				impulsefactor = 1.1,
				name = "Orbital Rocket System",
				range = 1300,
				reloadtime = 6,
				model = "cortronmissile.s3o",
				stockpile = false,
				soundhit = "xplomed4",
				soundstart = "mismed1",
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 4,
				startvelocity = 200,
				tracks = true,
				tolerance = 40000,
				turnrate = 40000,
				weaponacceleration = 1000,
				weapontimer = 1,
				weapontype = "StarburstLauncher",
				weaponvelocity = 2000,
				damage = {
					default = 2400,
				},
			},
		},
		weapons = {
			[1] = {
				def = "ORBITAL_ROCKET",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armobruiser = {
weapondefs = {
			space_emg = {
				collidefriendly = false,
				collidefeature = false,
				accuracy = 1,
				areaofeffect = 20,
				avoidfeature = false,
				avoidfriendly = false,
				burnblow = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				canattackground = false,
				duration = 0.05,
				edgeeffectiveness = 0.5,
				energypershot = 2,
				explosiongenerator = "custom:genericshellexplosion-small",
				impulsefactor = 0,
				intensity = 5,
				name = "Space Laser Battery",
				noselfdamage = true,
				proximitypriority = 1,
				range = 700,
				reloadtime = 0.5,
				rgbcolor = "0.05 0.05 1",
				soundhit = "xplosml3",
				soundhitwet = "sizzle",
				soundstart = "Lasrhvy2",
				thickness = 5,
				tolerance = 40000,
				turret = true,
				weapontimer = 1,
				weapontype = "LaserCannon",
				weaponvelocity = 1400,
				damage = {
					default = 75,
				},
			},
		},
		weapons = {
			[1] = {
				def = "SPACE_EMG",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[2] = {
				def = "SPACE_EMG",
				fastautoretargeting = true,
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armotachyon = {
weapondefs = {
exata = {
				beamtime = 0.3,
				name = "Orbital 2 orbital tachyon lance.",
				range = 1200,
				reloadtime = 8,
				minIntensity = 1,
				energypershot = 100,
				damage = {
					default = 2600,
				},
			},
		},
		weapons = {
			[1] = {
				def = "EXATA",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armokaiser = {
weapondefs = {
			plasma = {
				range = 1300,
				heightBoostFactor = 0,
				customparams = {
					carried_unit = "armodrone",     --Name of the unit spawned by this carrier unit.
					spawns_surface = "LAND",
				},
			},
			aamissile = {
				avoidfriendly = false,
				collidefriendly = false,
				areaofeffect = 100,
				burnblow = false,
				cegtag = "missiletrailaa",
				collidefeature = false,
				flighttime = 5,
				name = "Anti Air and Spaceship Missile",
				range = 1000,
				weaponacceleration = 300,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1200,
				damage = {
					default = 1000,
				},
			},
		},
		weapons = {
			[1] = {
				def = "PLASMA",
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "AAMISSILE",
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
armodrone = {
weapondefs = {
armodrone_missile = {
				areaofeffect = 50,
				avoidfeature = false,
				burnblow = false,
				canattackground = false,
				cegtag = "missiletrailsmall-red",
				collidefriendly = false,
				collidefeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-catapult",
				firestarter = 70,
				flighttime = 9,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "catapultmissile.s3o",
				name = "Seeking Interplanetary Missile Launcher",
				noselfdamage = true,
				range = 1000,
				reloadtime = 3,
				smoketrail = true,
				smokePeriod = 7,
				smoketime = 13,
				smokesize = 5.4,
				smokecolor = 0.95,
				smokeTrailCastShadow = false,
				castshadow = false,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "rockhvy2",
				startvelocity = 800,
				texture1 = "null",
				texture2 = "smoketrailaa3",
				tolerance = 20000,
				tracks = true,
				turnrate = 50000,
				turret = true,
				weaponacceleration = 500,
				weapontimer = 1,
				weapontype = "MissileLauncher",
				weaponvelocity = 1200,
				damage = {
					default = 250,
					vtol = 500,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "ARMODRONE_MISSILE",
				maindir = "0 0 1",
				maxangledif = 360,
				onlytargetcategory = "SPACENOTOBJECT VTOL",
			},
		},
},
armoliberator = {
weapondefs = {
			heavyplasma = {
				accuracy = 100,
				areaofeffect = 200,
				collidefriendly = false,
				collidefeature = false,
				hightrajectory = 1,
				range = 2100,
				heightBoostFactor = 0,
				damage = {
					default = 400,
				},
			},
			ferret_missile = {
				areaofeffect = 50,
				collidefriendly = false,
				collidefeature = false,
				burnblow = false,
				edgeeffectiveness = 0.15,
				flighttime = 5,
				name = "Pop-up rapid-fire o2a missile launcher",
				range = 1000,
				reloadtime = 2,
				damage = {
					default = 600,
					vtol = 1200,
				},
			},
		},
		weapons = {
			[2] = {
				def = "HEAVYPLASMA",
				maindir = "0 0 1",
				maxangledif = 320,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[4] = {
				def = "HEAVYPLASMA",
				maindir = "-4 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[5] = {
				def = "HEAVYPLASMA",
				maindir = "4 0 1",
				maxangledif = 180,
				onlytargetcategory = "SURFACE T4AIR",
			},
			[6] = {
				maindir = "0 -1 -2",
				maxangledif = 270,
				def = "FERRET_MISSILE",
				onlytargetcategory = "VTOL SPACENOTOBJECT",
			},
			[7] = {
				def = "FERRET_MISSILE",
				onlytargetcategory = "VTOL SPACENOTOBJECT",
			},
		},
},
corspace = {
buildoptions = {
"corosat",
"coroc",
"corosolar",
"corofighter",
"corocan",
"corobruiser",
"coroheavy",
},
},
corspacet3 = {
buildoptions = {
"coroc",
"corobomber",
"corohunter",
"coroheatray",
"coroapoc",
},
},
coroheatray ={
weapondefs = {
			laser = {
				collidefriendly = false,
				collidefeature = false,
				canattackground = false,
				areaofeffect = 72,
				avoidfriendly = false,
				energypershot = 350,
				range = 1200,
				damage = {
					default = 4000,
				},
			},
		},
		weapons = {
			[1] = {
				onlytargetcategory = "SPACENOTOBJECT",
			},
			[2] = {
				onlytargetcategory = "SPACENOTOBJECT",
			},
		},
},
}