-- ===================== 玩家专属单位配置 =====================
playerUnitList = {
    {"armthundt4","armthundt4_human","激光轰炸机","史诗激光轰炸机",220,100000,"vtol","Epic Laser Bomber","Epic Laser Bomber!"},
    {"legafigdef","legafigdef_human","史诗阿贾克斯","防御制空战斗机!",270,15000,"vtol","Epic Ajax","Defensive Air Fighter!"},
    {"corvamp","corvamp_human","史诗夜鹰","雷达隐形战斗机",380,19000,"vtol","Epic Hawk","Radar Stealth Fighter!"},
    {"armhawk","armhawk_human","史诗狂风","雷达隐形战斗机",360,21000,"vtol","Epic Wind","Radar Stealth Fighter!"},
    {"armbrawl","armbrawl_human","女妖","史诗炮艇",160,30000,"vtol","Epic Banshee","Gunship"},
    {"corape","corape_human","史诗黄蜂","史诗炮艇",160,30000,"vtol","Epic Corape","Gunship"},
    {"legkam","legkam_human","爆 蚊","自爆无人机",400,160,"vtol","Baneling","Self-destructs to deal explosive damage to target area!"},
    {"legafigdef","legafigdef_human_t4","T4实验级阿贾克斯","防御制空战斗机!",270,15000,"vtol","T4 Epic Ajax","Defensive Air Fighter!"},
    {"corvamp","corvamp_human_t4","T4实验级夜鹰","雷达隐形战斗机",380,19000,"vtol","T4 Epic Hawk","Radar Stealth Fighter!"},
    {"armhawk","armhawk_human_t4","T4实验级狂风","雷达隐形战斗机",360,21000,"vtol","T4 Epic Wind","Radar Stealth Fighter!"},

    {"armaca","armaca_t4","T4 工程飞机","T4科技工程单位",192,200,"vtol","T4 Construction Aircraft","Tech 4 Constructor"},
    {"armack","armack_t4","T4 工程机器人","T4科技工程单位",40,930,"standard","T4 Construction Bot","Tech 4 Constructor"},
    {"armacv","armacv_t4","T4 工程载具","T4科技工程单位",55,2050,"standard","T4 Construction Vehicle","Tech 4 Constructor"},
    {"coraca","coraca_t4","T4 工程飞机","T4科技工程单位",192,205,"vtol","T4 Construction Aircraft","Tech 4 Constructor"},
    {"corack","corack_t4","T4 工程机器人","T4科技工程单位",40,1000,"standard","T4 Construction Bot","Tech 4 Constructor"},
    {"coracv","coracv_t4","T4 工程载具","T4科技工程单位",55,2150,"standard","T4 Construction Vehicle","Tech 4 Constructor"},
    {"legaca","legaca_t4","T4 工程飞机","T4科技工程单位",203,195,"vtol","T4 Construction Aircraft","Tech 4 Constructor"},
    {"legack","legack_t4","T4 工程机器人","T4科技工程单位",46,860,"standard","T4 Construction Bot","Tech 4 Constructor"},
    {"legacv","legacv_t4","T4 工程载具","T4科技工程单位",60,1950,"standard","T4 Construction Vehicle","Tech 4 Constructor"},

    {"legfortt4","legfortt4_human","T4实验级 暴君","巨型飞行要塞",nil,nil,"vtol","T4 Epic Tyrannus","Gigantic Flying Fortress!"},
    {"corfblackhyt4","corfblackhyt4_human","T4实验级 海德拉","带有垂直起降推进器的旗舰...等等，什么？",100,nil,"vtol","T4 Flying Black Hydra","Flagship with Vtol thrusters... wait what?"},
    {"armfepocht4","armfepocht4_human","T4实验级 纪元","带垂直起降推进器的旗舰... 等等，什么？",100,nil,"vtol","T4 Flying Epoch","Flagship with Vtol thrusters... wait what?"},
    {"legeheatraymech_old","legeheatraymech_human","巨像","热能武器机甲",40,200000,"standard","Colossus","Heat Ray Weapon Mech!"},
    {"cormart","cormart_human","攻城坦克","固定火炮",58,10000,"standard","Siege Tank","Fixed Gun Battle Tank!"},
    {"legshot","legshot_human","不朽者","防护罩机甲",50,55000,"standard","Immortal","Shield Mech!"},
    {"armmeatball","armmeatball_human","歌利亚","机枪步行机甲",30,220000,"standard","Goliath","Machine Gun Weapon Mech!"},
    {"corkarganetht4","corkarg_human","雷神","重型攻击机甲",40,500000,"standard","Thor","Eternal Weapon Mech!"},
    {"cordemon","cordemon_human","火蝠","火焰喷射机甲",60,720000,"standard","Firebat","Flamethrower Mech"},
    {"legstr","legstr_human","陆战队员","机枪步兵",84,80000,"standard","Marine","Machine Gun Infantry!"},
    {"corkarg","corkarganetht4_t4","追猎者","全地形两栖突击机甲",nil,nil,"standard","Stalker","All-Terrain Amphibious Assault Mech"},
    {"armliche","armliche_t4","T4 巫妖","战略原子轰炸机!",nil,nil,"vtol","T4 Epic Lich","Atomic Bomber"},
    {"legelrpcmech","legelrpcmech_t4","金甲虫","远程集束等离子攻城机甲",nil,nil,"standard","Reaver","Long-Range Cluster Plasma Siege Mech"},
    {"legbunk","legbunk_t4","狂热者","快速突击机甲",nil,nil,"standard","Zealot","Fast Assault Mech"},
    {"corshiva","corshiva_t4","战 狼","两栖攻城机甲",nil,nil,"standard","Warhound","Amphibious Siege Mech"},

    {"armaak","armaak_t4","T4 大天使","两栖防空机器人",nil,nil,"standard","T4 Epic AaK","Archangel Amphibious Anti-Air Bot"},
    {"armyork","armyork_t4","T4 粉碎者","防空高射炮载具",nil,nil,"standard","T4 Shredder","Anti-Air Flak Vehicle"},
    {"corsent","corsent_t4","T4 狂怒","T4 防空高射炮车",nil,nil,"standard","T4 Fury","Anti-Air Flak Vehicle"},
    {"coraak","coraak_t4","T4 蝎尾狮","重型两栖防空机器人",nil,nil,"standard","T4 Manticore","Heavy Amphibious Anti-Air Bot"},
    {"legadvaabot","legadvaabot_t4","T4 阿奎隆","T4 重型两栖防空机器人",nil,nil,"standard","T4 Aquilon","Heavy Amphibious Anti-Air Bot"},
    {"legvflak","legvflak_t4","T4 卡戎","T4 防空机枪卡车",nil,nil,"standard","T4 Charon","Anti-Air Minigun Truck"},

    {"raptor_land_spiker_basic_t4_v1","hydralisk","刺 蛇","对地对空尖刺异虫",140,nil,"standard","Hydralisk","Anti-Ground and Anti-Air Spiked Alien"},
    {"raptor_land_kamikaze_basic_t4_v1","baneling","爆 虫","自毁型异虫 死亡时能造成大范围伤害",nil,nil,"standard","Baneling","Self-Destructs to deal explosive damage to target area"},
    {"raptor_land_assault_acid_t2_v1","roach","蟑 螂","酸液突击单位",80,nil,"standard","Roach","Acid Assault Unit"},
    {"raptor_air_kamikaze_basic_t2_v1","scourge","爆 蚊","自毁式飞行异虫",nil,nil,"vtol","Scourge","Self-Destruct Flying Alien"},
    {"raptor_air_fighter_basic_t4_v1","mutalisk","异 龙","快速飞行攻击异虫",350,nil,"vtol","Mutalisk","Fast Flying Attack Alien"},
    {"raptor_matriarch_basic","ultralisk","雷 兽","重型攻击范围性顺劈猛兽",100,nil,"standard","Ultralisk","Heavy Assault Beast"},
    {"legfortt4","battlecruiser","战列巡洋舰","强大的战舰。可以使用大和炮",40,nil,"vtol","Battlecruiser","Powerful warship. Can use Yamato Cannon"},
    {"legmost3","voidray","虚空辉光舰","高能光束武器战舰",nil,nil,"vtol","Void Ray","High-Energy Beam Weapon Warship"},
    {"corkarganetht4","immortal","不朽者","防护罩机甲",nil,nil,"standard","Immortal","Shield Mech!"},

    {"legstarfall","legstarfall_human","终极对空星落","远程火箭发射器",0,50000,"standard","Epic Starfall","Starfall!"},
    {"armapt3","armapt3_human","T4 飞行工厂","生产T4 飞行单位",0,20000,"standard","T4 Flight Factory","Production T4 flight unit"},
    {"armshltx","armshltx_human","T4 地面工厂","生产T4 地面单位",0,30000,"standard","T4 Ground Factory ","Production T4 ground unit"},
    {"corapt3","corapt3_human","T4 飞行工厂","生产T4 飞行单位",0,20000,"standard","T4 Flight Factory ","Production T4 flight unit"},
    {"corgant","corgant_human","T4 地面工厂","生产T4 地面单位",0,30000,"standard","T4 Ground Factory ","Production T4 ground unit"},
    {"legapt3","legapt3_human","T4 飞行工厂","生产T4 飞行单位",0,20000,"standard","T4 Flight Factory ","Production T4 flight unit"},
    {"leggant","leggant_human","T4 地面工厂","生产T4 地面单位",0,30000,"standard","T4 Ground Factory ","Production T4 ground unit"},
--  {"corbuzz","corbuzz_human","洲际导弹 灾难","核弹洲际弹道导弹发射器",0,20000,"standard","Epic Intercontinental Missile Disaster","Intercontinental Missile Disaster!"},
    {"corbuzz","corbuzz_human","浩劫轰击","速射远程等离子炮!",0,80000,"standard","Epic Calamity","Rapid-Fire Long-Range Plasma Cannon!"},
    {"armvulc","armvulc_human","终极诸神黄昏","速射远程等离子炮!",0,80000,"standard","Epic Ragnarok","Rapid-Fire Long-Range Plasma Cannon!"},
    {"legstarfall","legstarfall_t4","天劫轰击","远程核弹发射器",nil,50000,"standard","Epic Starfall","Starfall!"},
    
    {"armvulc","armvulc_t4","可移动的诸神黄昏","速射远程等离子炮!",60,nil,"standard","Epic CanMove Ragnarok","Rapid-Fire Long-Range Plasma Cannon!"},
    {"corbuzz","corbuzz_t4","可移动的浩劫轰击","速射远程等离子炮!",60,nil,"standard","Epic CanMove Calamity","Rapid-Fire Long-Range Plasma Cannon!"},
    {"legstarfall","legstarfall_mt4","可移动的星陨","远程等离子发射器",60,nil,"standard","Epic CanMove Starfall","Starfall!"},

    {"armguard","armguard_t4","T4 铁拳堡垒","区域压制等离子火炮",0,5500,"standard","T4 Gauntlet","Area Control Plasma Artillery"},
    {"armbeamer","armbeamer_t4","T4 光束塔","光束激光炮塔",0,5800,"standard","T4 Beam Turret","Beam Laser Turret"},
    {"armhlt","armhlt_t4","T4 守望者","区域压制激光塔",0,6800,"standard","T4 Laser Turret","Area Control Laser Tower"},
    {"armmercury","armmercury_t4","T4 水星","远程防空塔",0,7900,"standard","T4 Laser Turret","Long Range Anti-Air Tower"},
    {"armcir","armcir_t4","T4 链锯","中程防空导弹阵地",0,8600,"standard","T4 Circular Turret","Medium-Range Anti-Air Missile Battery"},
    {"armrl","irondome","铁 穹","区域拒止阵列",nil,5500,"standard","Iron Dome","Area Denial Array"},

    {"corpun","corpun_t4","T4 煽动者","区域压制等离子火炮",0,8900,"standard","T4 Agitator","Circular Laser Turret"},
    {"corllt","corllt_t4","T4 激光炮塔","激光塔",0,4800,"standard","T4 Guard","Light Laser Tower"},
    {"corerad","corerad_t4","T4 根除者","中程防空导弹阵列",0,6800,"standard","T4 Eradicator","Medium-Range Anti-Air Missile Battery"},
    {"corhlt","corhlt_t4","T4 终结者","区域压制激光炮塔",0,7800,"standard","T4 Warden","Area Control Laser Tower"},
    {"cormadsam","cormadsam_t4","T4  MADSAM","加固防空导弹炮台",0,9800,"standard","T4 SAM","Hardened Anti-Air Missile Battery"},

    {"legacluster","legacluster_t4","T4 开膛者","弹出式集束等离子火炮",0,9700,"standard","T4 Eviscerator","Pop-up Cluster Plasma Artillery"},
    {"legmg","legmg_t4","T4 喧嚣壁垒","重型地对空加特林机枪炮塔",0,7900,"standard","T4 Cacophony","Heavy Land/Air Gatling Gun Turret"},
    {"leglupara","leglupara_t4","T4 卢帕拉","抗炸弹中程防空高射炮台",0,8900,"standard","T4 Lupara","Bomb-Resistant Medium-Range Anti-Air Flak Battery"},
    {"legrhapsis","legrhapsis_t4","T4 狂想曲壁垒","齐射防空导弹阵列",0,9800,"standard","T4 Rhapsis","Salvo Anti-Air Missile Battery"},
    {"legbombard","legbombard_t4","T4 轰炸者","榴弹发射器防御",0,8800,"standard","T4 Bombardier","Grenade Launcher Defence"},
    {"leglrpc","leglrpc_t4","T4 奥林匹斯","远程集束等离子炮",0,8800,"standard","T4 Olympus","Long-Range Cluster Plasma Cannon"},
}
