--No Metal Mod by Ambo V0.1 (Merely Zero Metal, Converters Allowed)
for name,ud in pairs(UnitDefs) do
  ud.metalcost = 0
  ud.metalCost = 0
  ud.buildCostMetal = 0
end

for name,ud in pairs(UnitDefs) do
  if ud.extractsMetal and ud.extractsMetal > 0 then
    ud.maxThisUnit = 0
  end
end-- Source: ["~lua/main-defs.lua"]
local a,b,c,d=UnitDefs or{},'repulsor',pairs,table.merge;function addWeapon(c,e,f)a[c]=a[c]or{}a[c].weapons=a[c].weapons or{}a[c].weapondefs=a[c].weapondefs or{}a[c].customparams=a[c].customparams or{}table.insert(a[c].weapons,{def=b,onlytargetcategory=f or''})a[c].weapondefs[b]=e;if e.shield and e.shield.power>0 then e.range=e.shield.radius;a[c].customparams=d(a[c].customparams or{},{off_on_stun='true',shield_color_mult=0.8,shield_power=e.shield.power,shield_radius=e.shield.radius})end end;for a,b in c(a)do if string.sub(a,1,24)=='raptor_air_fighter_basic'then if b.weapondefs then for a,a in c(b.weapondefs)do a.name='Spike'a.accuracy=200;a.collidefriendly=0;a.collidefeature=0;a.avoidfeature=0;a.avoidfriendly=0;a.areaofeffect=64;a.edgeeffectiveness=0.3;a.explosiongenerator='custom:raptorspike-large-sparks-burn'a.cameraShake={}a.dance={}a.interceptedbyshieldtype=0;a.model='Raptors/spike.s3o'a.reloadtime=1.1;a.soundstart='talonattack'a.startvelocity=200;a.submissile=1;a.smoketrail=0;a.smokePeriod={}a.smoketime={}a.smokesize={}a.smokecolor={}a.soundhit={}a.texture1={}a.texture2={}a.tolerance={}a.tracks=0;a.turnrate=60000;a.weaponacceleration=100;a.weapontimer=1;a.weaponvelocity=1000;a.weapontype={}a.wobble={}end end elseif a:match'^[acl][ore][rgm]com'and not a:match'_scav$'then table.mergeInPlace(b,{customparams={combatradius=0,fall_damage_multiplier=0,paratrooper=true,wtboostunittype={}},featuredefs={dead={damage=9999999,reclaimable=false,mass=9999999}}})end end;local b={raptor_air_kamikaze_basic_t2_v1={selfdestructas='raptor_empdeath_big'},raptor_land_swarmer_emp_t2_v1={weapondefs={raptorparalyzersmall={damage={shields=70},paralyzetime=6}}},raptor_land_assault_emp_t2_v1={weapondefs={raptorparalyzerbig={damage={shields=150},paralyzetime=10}}},raptor_allterrain_arty_emp_t2_v1={weapondefs={goolauncher={paralyzetime=6}}},raptor_allterrain_arty_emp_t4_v1={weapondefs={goolauncher={paralyzetime=10}}},raptor_air_bomber_emp_t2_v1={weapondefs={weapon={damage={shields=1100,default=2000},paralyzetime=10}}},raptor_allterrain_swarmer_emp_t2_v1={weapondefs={raptorparalyzersmall={damage={shields=70},paralyzetime=6}}},raptor_allterrain_assault_emp_t2_v1={weapondefs={raptorparalyzerbig={damage={shields=150},paralyzetime=6}}},raptor_matriarch_electric={weapondefs={goo={paralyzetime=13},melee={paralyzetime=13},spike_emp_blob={paralyzetime=13}}}}for b,c in c(b)do if a[b]then a[b]=d(a[b],c)end end;for b,b in c({'raptor_antinuke','raptor_turret_acid_t2_v1','raptor_turret_acid_t3_v1','raptor_turret_acid_t4_v1','raptor_turret_antiair_t2_v1','raptor_turret_antiair_t3_v1','raptor_turret_antiair_t4_v1','raptor_turret_antinuke_t2_v1','raptor_turret_antinuke_t3_v1','raptor_turret_basic_t2_v1','raptor_tu