--mod by FiendishDevil
{
	freefusion = {
		cloakcost = 3000,
		blocking = true,
		buildtime = 641700,
		energycost = 475000,
		energymake = 1000,
		energystorage = 90000,
		explodeas = "ScavComBossExplo",
		floater = true,
		footprintx = 6,
		footprintz = 6,
		health = 17300,
		metalmake = 120,
		metalcost = 22500,
		metalstorage = 10000,
		mincloakdistance = 100,
		onoffable = true,
		customparams = {
			removestop = true,
			removewait = true,
			subfolder = "ArmBuildings/LandEconomy",
			techlevel = 3,
			unitgroup = "metal",
			usebuildinggrounddecal = true,
			i18n_en_humanname = 'Cold Fusion Converter',
    			i18n_en_tooltip = 'Self contained cloakable energy converter produces 1000 energy and 120 metal (Hazardous)',
		},

	},
  armaca = {
	buildoptions = {
		[34] = "freefusion",
		[35] = "armgatet3",
		[36] = "armnanotct2",
		[37] = "armbotrail",
	},
},
  armacv = {
	buildoptions = {
		[31] = "freefusion",
		[32] = "armgatet3",
		[33] = "armnanotct2",
		[34] = "armbotrail",
	},
},
  armack = {
	buildoptions = {
		[31] = "freefusion",
		[32] = "armgatet3",
		[33] = "armnanotct2",
		[34] = "armbotrail",
	},

},


  coraca = {
	buildoptions = {
		[33] = "freefusion",
		[34] = "corgatet3",
		[35] = "cornanotct2",
		[36] = "corhllllt",
	},
},
  coracv = {
	buildoptions = {
		[30] = "freefusion",
		[31] = "corgatet3",
		[32] = "cornanotct2",
		[33] = "corhllllt",
	},
},
  corack = {
	buildoptions = {
		[30] = "freefusion",
		[31] = "corgatet3",
		[32] = "cornanotct2",
		[33] = "corhllllt",
	},

},
  legaca = {
	buildoptions = {
			"legfus",
			"legafus",
			"legageo",
			"coruwageo",
			"legrampart",
			"legmoho",
			"cormexp",
			"legadveconv",
			"legadvestore",
			"legamstor",
			"legarad",
			"legajam",
			"legforti",
			"corasp",
			"corfasp",
			"legtarg",
			"legsd",
			"legdeflector",
			"legacluster",
			"legbombard",
			"legbastion",
			"legflak",
			"leglraa",
			"legperdition",
			"legabm",
			"legsilo",
			"leglrpc",
			"legstarfall",
			"legap",
			"legaap",
			"corplat",
			"leggant",
		"freefusion",
		"leggatet3",
		"legnanotct2",
		"legrwall",
	},
},
  legacv = {
	buildoptions = {
			"legfus",
			"legafus",
			"leggant",
			"legageo",
			"legrampart",
			"legmoho",
			"cormexp",
			"legadveconv",
			"legadvestore",
			"legamstor",
			"legarad",
			"legajam",
			"legforti",
			"corasp",
			"legtarg",
			"legsd",
			"legdeflector",
			"legacluster",
			"legbombard",
			"legbastion",
			"legflak",
			"leglraa",
			"legperdition",
			"legabm",
			"legsilo",
			"leglrpc",
			"legstarfall",
			"legvp",
			"legavp",
		"freefusion",
		"leggatet3",
		"legnanotct2",
		"legrwall",
	},
},
  legack = {
	buildoptions = {
			"legfus",
			"legafus",
			"leggant",
			"legageo",
			"legrampart",
			"legmoho",
			"cormexp",
			"legadveconv",
			"legadvestore",
			"legamstor",
			"legarad",
			"legajam",
			"legforti",
			"corasp",
			"legtarg",
			"legsd",
			"legdeflector",
			"legacluster",
			"legbombard",
			"legbastion",
			"legflak",
			"leglraa",
			"legperdition",
			"legabm",
			"legsilo",
			"leglrpc",
			"legstarfall",
			"leglab",
			"legalab",
		"freefusion",
		"leggatet3",
		"legnanotct2",
		"legrwall",
	},
},
leggant = {buildoptions={
[110]="legpede",},},
legpede = {
		movementclass = "EPICALLTERRAIN",
},

cornanotc={buildoptions={[1]="cornanotc",[2]="coradvsol",[3]="cormakr",[4]="corjamt",[5]="corllt",[6]="corrl",[7]="cornanotcplat",[8]="coreyes",[9]="corck",[10]="corvalk",},},
cornanotcplat={buildoptions={[1]="cornanotcplat",[2]="cortide",[3]="corfmkr",[4]="cornanotc",},},
legnanotc={buildoptions={[1]="legnanotc",[2]="legadvsol",[3]="legeconv",[4]="legjam",[5]="leglht",[6]="legrl",[7]="legnanotcplat",[8]="legeyes",[9]="legck",[10]="legatrans",},},
legnanotcplat={buildoptions={[1]="legnanotcplat",[2]="legtide",[3]="legfmkr",[4]="legnanotc",},},
armnanotc={buildoptions={[1]="armnanotc",[2]="armadvsol",[3]="armmakr",[4]="armjamt",[5]="armllt",[6]="armrl",[7]="armnanotcplat",[8]="armeyes",[9]="armck",[10]="armatlas",},},
armnanotcplat={buildoptions={[1]="armnanotcplat",[2]="armtide",[3]="armfmkr",[4]="armnanotc",},},
legnanotct2={buildoptions={[1]="legnanotct2",[2]="legfus",[3]="legafus",[4]="legadveconv",[5]="leglraa",[6]="legforti",[7]="legnanotct2plat",[8]="legdeflector",[9]="legeyes",[10]="legack",[11]="legabm",[12]="freefusion",},},
legnanotct2plat={buildoptions={[1]="legnanotct2plat",[2]="coruwfus",[3]="coruwmmm",[4]="legnanotct2",[5]="corfgate",},},
cornanotct2={buildoptions={[1]="cornanotct2",[2]="corfus",[3]="corafus",[4]="cormmkr",[5]="corscreamer",[6]="corfort",[7]="cornanotc2plat",[8]="corgate",[9]="coreyes",[10]="corack",[11]="corfmd",[12]="freefusion",},},
cornanotc2plat={buildoptions={[1]="cornanotc2plat",[2]="coruwfus",[3]="coruwmmm",[4]="cornanotct2",[5]="corfgate",},},
armnanotct2={buildoptions={[1]="armnanotct2",[2]="armfus",[3]="armafus",[4]="armmmkr",[5]="armmercury",[6]="armfort",[7]="armnanotc2plat",[8]="armgate",[9]="armeyes",[10]="armack",[11]="armamd",[12]="freefusion",},},
armnanotc2plat={buildoptions={[1]="armnanotc2plat",[2]="armuwfus",[3]="armuwmmm",[4]="armnanotct2",[5]="armfgate",},}, 


}