window.CUSTOM_CONTENT_DATABASE = [
  {
    "id": "armassemblycomplex",
    "name": "Assembly Complex",
    "tooltip": "Upgraded Vehicle Plant with much higher build power.",
    "baseId": "armvp",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armvp.png",
    "source": "Unattributed (found in saved presets)",
    "confidence": "guessed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 11
  },
  {
    "id": "armbotrail",
    "name": "The Depawner",
    "tooltip": "Shoots down the Pawn Launcher's shell in flight -- if it connects, the Pawn never spawns.",
    "baseId": "armbotrail",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armbotrail.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [],
    "presetCount": 0
  },
  {
    "id": "armbull_heavy",
    "name": "The Bull",
    "tooltip": "Slow heavy assault unit. High-damage, slow-firing laser.",
    "baseId": "armbull",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "armbull.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "armbulwark",
    "name": "Bulwark Tower",
    "tooltip": "Heavy area-control tower. Tougher, harder-hitting.",
    "baseId": "armhlt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armhlt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 11
  },
  {
    "id": "armdepawner",
    "name": "The Depawner",
    "tooltip": "Shoots down the Pawn Launcher's shell in flight -- if it connects, the Pawn never spawns.",
    "baseId": "armflak",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armflak.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "armhyperreactor",
    "name": "Hyper Reactor",
    "tooltip": "Massively upscaled Fusion Reactor. Produces 3000 energy.",
    "baseId": "armfus",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armfus.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 11
  },
  {
    "id": "arminterceptor_artillery",
    "name": "Artillery Interceptor",
    "tooltip": "Missile point defense. Shoots down incoming missiles.",
    "baseId": "armamd",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armamd.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 10
  },
  {
    "id": "arminterceptor_energy",
    "name": "Energy Interceptor",
    "tooltip": "Beam point defense. Always ready, no stockpile needed.",
    "baseId": "armhlt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armhlt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 10
  },
  {
    "id": "armllt_armored",
    "name": "Armored Tower",
    "tooltip": "Armored laser tower: more health plus a personal shield.",
    "baseId": "armllt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armllt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 10
  },
  {
    "id": "armllt_hp",
    "name": "High Power Laser Tower",
    "tooltip": "High-cost laser tower: longer range, far more damage.",
    "baseId": "armllt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armllt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 10
  },
  {
    "id": "armllt_rapid",
    "name": "Rapid Fire Tower",
    "tooltip": "Rapid-fire anti-swarm turret. Weak vs single targets.",
    "baseId": "armllt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armllt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "armsupportrelay",
    "name": "Support Relay",
    "tooltip": "Long-range assist & repair turret.",
    "baseId": "armnanotc",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "armnanotc.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs7)",
      "mark magic 3 (tweakdefs7)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs7)",
      "mark magic 7 (tweakdefs7)",
      "mark magic 8 (tweakdefs7)",
      "mark magic 9 (tweakdefs7)",
      "mark magic 10 (tweakdefs7)"
    ],
    "presetCount": 11
  },
  {
    "id": "armthort4",
    "name": "Epic Thor",
    "tooltip": "Ultimate Terminator Tank",
    "baseId": "armthor",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "armthor.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "bioprinter",
    "name": "Black Market BioPrinter",
    "tooltip": "The most anticipated barely illegal underground Bio Printer",
    "baseId": "lootboxnano_t4_var3",
    "baseIsRealUnit": false,
    "type": "Unknown",
    "icon": null,
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "scav hell custom (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "Marks scav hell (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "scavs custom (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "scavs (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "testy (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 36
  },
  {
    "id": "birdangler",
    "name": "Bird Angler",
    "tooltip": "Heavy long range Anti Air Turret",
    "baseId": "raptor_turret_antiair_t3_v1",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "raptors/raptor_turretl_antiair.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "scav hell custom (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "Marks scav hell (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "scavs custom (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "testy (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 35
  },
  {
    "id": "birdofprey",
    "name": "Bird of Prey",
    "tooltip": "Khrathm... no, not that one! Air Fighter",
    "baseId": "raptor_air_fighter_basic_t4_v1",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "raptors/raptorw2.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "scav hell custom (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "Marks scav hell (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "scavs custom (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "testy (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 35
  },
  {
    "id": "corassemblycomplex",
    "name": "Assembly Complex",
    "tooltip": "Upgraded Vehicle Plant with much higher build power.",
    "baseId": "corvp",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corvp.png",
    "source": "Unattributed (found in saved presets)",
    "confidence": "guessed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 11
  },
  {
    "id": "corbulwark",
    "name": "Bulwark Tower",
    "tooltip": "Heavy area-control tower. Tougher, harder-hitting.",
    "baseId": "corhlt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corhlt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 11
  },
  {
    "id": "cordemont4",
    "name": "Hellblazer",
    "tooltip": "Earth scorching Demon",
    "baseId": "cordemon",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "cordemon.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "cordepawner",
    "name": "The Depawner",
    "tooltip": "Shoots down the Pawn Launcher's shell in flight -- if it connects, the Pawn never spawns.",
    "baseId": "corflak",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corflak.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "corgol_heavy",
    "name": "The Dozer",
    "tooltip": "Slow heavy assault unit. High-damage, slow-firing laser.",
    "baseId": "corgol",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "corgol.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "corhyperreactor",
    "name": "Hyper Reactor",
    "tooltip": "Massively upscaled Fusion Reactor. Produces 3300 energy.",
    "baseId": "corfus",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corfus.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 11
  },
  {
    "id": "corinterceptor_artillery",
    "name": "Artillery Interceptor",
    "tooltip": "Missile point defense. Shoots down incoming missiles.",
    "baseId": "corfmd",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corfmd.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 10
  },
  {
    "id": "corinterceptor_energy",
    "name": "Energy Interceptor",
    "tooltip": "Beam point defense. Always ready, no stockpile needed.",
    "baseId": "corhlt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corhlt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 10
  },
  {
    "id": "corllt_armored",
    "name": "Armored Tower",
    "tooltip": "Armored laser tower: more health plus a personal shield.",
    "baseId": "corllt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corllt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 10
  },
  {
    "id": "corllt_hp",
    "name": "High Power Laser Tower",
    "tooltip": "High-cost laser tower: longer range, far more damage.",
    "baseId": "corllt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corllt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 10
  },
  {
    "id": "corllt_rapid",
    "name": "Rapid Fire Tower",
    "tooltip": "Rapid-fire anti-swarm turret. Weak vs single targets.",
    "baseId": "corllt",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "corllt.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "corsupportrelay",
    "name": "Support Relay",
    "tooltip": "Long-range assist & repair turret.",
    "baseId": "cornanotc",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "cornanotc.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs7)",
      "mark magic 3 (tweakdefs7)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs7)",
      "mark magic 7 (tweakdefs7)",
      "mark magic 8 (tweakdefs7)",
      "mark magic 9 (tweakdefs7)",
      "mark magic 10 (tweakdefs7)"
    ],
    "presetCount": 11
  },
  {
    "id": "corthermitet3",
    "name": "Core Melter",
    "tooltip": "Experimental Heat Ray Heavy Spider",
    "baseId": "corthermite",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "corthermite.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "epicunitprinter",
    "name": "Epic Unit Printer",
    "tooltip": "The mother of all private army unit printers.",
    "baseId": "lootboxnano_t4_var9",
    "baseIsRealUnit": false,
    "type": "Unknown",
    "icon": null,
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "grenadier",
    "name": "Grenadier Beetle",
    "tooltip": "Grenadier Beetle",
    "baseId": "raptorartillery",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "raptors/raptorr1.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "scav hell custom (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "Marks scav hell (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "scavs custom (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "testy (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 35
  },
  {
    "id": "hunterdrone",
    "name": "Swarmship",
    "tooltip": "Anti Air Drone Carrier",
    "baseId": "legheavydrone",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "legheavydrone.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "infinitybox",
    "name": "Infinity Box",
    "tooltip": "Oww, what´s in the box?! Produces 33000 energy and 60 metal",
    "baseId": "lootboxplatinum",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "lootboxes/lootboxplatinum.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "jaeger",
    "name": "Jaeger Mk I",
    "tooltip": "Experimental Hunter Killer",
    "baseId": "corcomboss",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "scavengers/corcomboss.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "jaegermk2",
    "name": "Jaeger Mk II",
    "tooltip": "Experimental Hunter Killer",
    "baseId": "armscavengerbossv2_easy",
    "baseIsRealUnit": false,
    "type": "Unknown",
    "icon": null,
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 36
  },
  {
    "id": "legassemblycomplex",
    "name": "Assembly Complex",
    "tooltip": "Upgraded Vehicle Plant with much higher build power.",
    "baseId": "legvp",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "legvp.png",
    "source": "Unattributed (found in saved presets)",
    "confidence": "guessed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 11
  },
  {
    "id": "legbulwark",
    "name": "Bulwark Tower",
    "tooltip": "Heavy area-control tower. Tougher, harder-hitting.",
    "baseId": "leglht",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "leglht.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 11
  },
  {
    "id": "legdepawner",
    "name": "The Depawner",
    "tooltip": "Shoots down the Pawn Launcher's shell in flight -- if it connects, the Pawn never spawns.",
    "baseId": "legflak",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "legflak.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "leghyperreactor",
    "name": "Hyper Reactor",
    "tooltip": "Massively upscaled Fusion Reactor. Produces 3600 energy.",
    "baseId": "legfus",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "legfus.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 11
  },
  {
    "id": "leginc_heavy",
    "name": "The Beamer",
    "tooltip": "Slow heavy assault unit. High-damage, slow-firing laser.",
    "baseId": "leginc",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "leginc.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "leginterceptor_artillery",
    "name": "Artillery Interceptor",
    "tooltip": "Missile point defense. Shoots down incoming missiles.",
    "baseId": "legabm",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "legabm.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 10
  },
  {
    "id": "leginterceptor_energy",
    "name": "Energy Interceptor",
    "tooltip": "Beam point defense. Always ready, no stockpile needed.",
    "baseId": "leglht",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "leglht.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs6)",
      "mark magic 3 (tweakdefs6)",
      "mark magic 4 (tweakdefs9)",
      "mark magic 5 (tweakdefs6)",
      "mark magic 7 (tweakdefs6)",
      "mark magic 8 (tweakdefs6)",
      "mark magic 9 (tweakdefs6)",
      "mark magic 10 (tweakdefs6)"
    ],
    "presetCount": 10
  },
  {
    "id": "leglht_armored",
    "name": "Armored Tower",
    "tooltip": "Armored heat ray tower: more health plus a personal shield.",
    "baseId": "leglht",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "leglht.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 10
  },
  {
    "id": "leglht_hp",
    "name": "High Power Laser Tower",
    "tooltip": "High-cost heat ray tower: longer range, far more damage.",
    "baseId": "leglht",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "leglht.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs5)",
      "mark magic 3 (tweakdefs5)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs5)",
      "mark magic 7 (tweakdefs5)",
      "mark magic 8 (tweakdefs5)",
      "mark magic 9 (tweakdefs5)",
      "mark magic 10 (tweakdefs5)"
    ],
    "presetCount": 10
  },
  {
    "id": "leglht_rapid",
    "name": "Rapid Fire Tower",
    "tooltip": "Rapid-fire anti-swarm turret. Weak vs single targets.",
    "baseId": "leglht",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "leglht.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs4)",
      "mark magic 3 (tweakdefs4)",
      "mark magic 4 (tweakdefs2)",
      "mark magic 5 (tweakdefs4)",
      "mark magic 7 (tweakdefs4)",
      "mark magic 8 (tweakdefs4)",
      "mark magic 9 (tweakdefs4)",
      "mark magic 10 (tweakdefs4)"
    ],
    "presetCount": 10
  },
  {
    "id": "legsupportrelay",
    "name": "Support Relay",
    "tooltip": "Long-range assist & repair turret.",
    "baseId": "legnanotc",
    "baseIsRealUnit": true,
    "type": "Building",
    "icon": "legnanotc.png",
    "source": "Ours (current)",
    "confidence": "confirmed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs7)",
      "mark magic 3 (tweakdefs7)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs7)",
      "mark magic 7 (tweakdefs7)",
      "mark magic 8 (tweakdefs7)",
      "mark magic 9 (tweakdefs7)",
      "mark magic 10 (tweakdefs7)"
    ],
    "presetCount": 11
  },
  {
    "id": "overcom",
    "name": "Metal OverCommander",
    "tooltip": "When hope was lost, he kept building",
    "baseId": "armcomboss",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "scavengers/armcomboss.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "raptor fort latest (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "tetris raptor (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 33
  },
  {
    "id": "overseer",
    "name": "Raptor Overseer",
    "tooltip": "Raptor Overseer",
    "baseId": "raptorh5",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "raptors/raptorh5.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "scav hell custom (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "Marks scav hell (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "scavs custom (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "testy (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 35
  },
  {
    "id": "portafus",
    "name": "Portable Advanced Fusion Reactor",
    "tooltip": "Portable, affordable, explosive! Produces 3300 energy",
    "baseId": "lootboxgold",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "lootboxes/lootboxgold.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "portfus",
    "name": "Pocket Fusion Reactor",
    "tooltip": "You can almost put it in your Pocket! Produces 1100 energy",
    "baseId": "lootboxsilver",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "lootboxes/lootboxsilver.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "raptorbioreactor",
    "name": "Raptor Bio-Reactor",
    "tooltip": "Salvaged Raptor bio-tech energy building. Produces 2800 energy.",
    "baseId": "lootboxgold",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "lootboxes/lootboxgold.png",
    "source": "Unattributed (found in saved presets)",
    "confidence": "guessed",
    "foundInPresets": [
      "tetris scav mode + custom buildings (tweakdefs4)",
      "mark magic (tweakdefs4)",
      "mark magic 1 (tweakdefs4)",
      "mark magic 2 (tweakdefs7)",
      "mark magic 3 (tweakdefs7)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs7)",
      "mark magic 7 (tweakdefs7)",
      "mark magic 8 (tweakdefs7)",
      "mark magic 9 (tweakdefs7)",
      "mark magic 10 (tweakdefs7)"
    ],
    "presetCount": 11
  },
  {
    "id": "regurgitator",
    "name": "Regurgitator",
    "tooltip": "Sprays Acid on enemies",
    "baseId": "raptor_air_gunship_acid_t2_v1",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "raptors/raptorf1.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "scav hell custom (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "Marks scav hell (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "scavs custom (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "testy (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 35
  },
  {
    "id": "slinger",
    "name": "Slinger",
    "tooltip": "Launches big Projectiles over greater distance",
    "baseId": "raptor_turret_basic_t3_v1",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "raptors/raptor_turretl.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "scav hell custom (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "Marks scav hell (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "scavs custom (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "testy (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 35
  },
  {
    "id": "spitter",
    "name": "Spitter",
    "tooltip": "Launches AoE Projectiles",
    "baseId": "raptor_turret_basic_t2_v1",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "raptors/raptor_turrets.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs3)",
      "massive sci fi (tweakdefs3)",
      "latest scav zombies mode june 2026 (tweakdefs3)",
      "water test level (tweakdefs3)",
      "mode 2 (tweakdefs3)",
      "supreme scamus (tweakdefs3)",
      "scav hell custom (tweakdefs3)",
      "broes spare mode (tweakdefs3)",
      "Marks scav hell (tweakdefs3)",
      "tetris scav mode (tweakdefs3)",
      "scavs custom (tweakdefs3)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs3)",
      "Europe scavs (tweakdefs3)",
      "mark tweaks testing (tweakdefs3)",
      "All in or die (tweakdefs3)",
      "latest waffles (tweakdefs3)",
      "Marks epic scav zombies t4 (tweakdefs3)",
      "tweaks (tweakdefs3)",
      "scav hell (tweakdefs3)",
      "epic scav zombies (tweakdefs3)",
      "SCAV ZOMBIES (tweakdefs3)",
      "Marks latest scav zombies (tweakdefs3)",
      "testy (tweakdefs3)",
      "tetris scav mode + custom buildings (tweakdefs3)",
      "mark magic (tweakdefs3)",
      "mark magic 1 (tweakdefs3)",
      "mark magic 2 (tweakdefs3)",
      "mark magic unranked test (tweakdefs3)",
      "mark magic 3 (tweakdefs3)",
      "mark magic 4 (tweakdefs3)",
      "mark magic 5 (tweakdefs3)",
      "mark magic 7 (tweakdefs3)",
      "mark magic 8 (tweakdefs3)",
      "mark magic 9 (tweakdefs3)",
      "mark magic 10 (tweakdefs3)"
    ],
    "presetCount": 35
  },
  {
    "id": "swarmship",
    "name": "Swarmship",
    "tooltip": "Anti Air Drone Carrier",
    "baseId": "cordronecarryair",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": null,
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "scavs (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 37
  },
  {
    "id": "umbrellamk2",
    "name": "Umbrella Mk II",
    "tooltip": "Mobile all-terrain Shield Unit",
    "baseId": "armscab",
    "baseIsRealUnit": true,
    "type": "Unit",
    "icon": "armscab.png",
    "source": "CrossGamer",
    "confidence": "confirmed",
    "foundInPresets": [
      "waterworld (tweakdefs1)",
      "massive sci fi (tweakdefs1)",
      "latest scav zombies mode june 2026 (tweakdefs1)",
      "water test level (tweakdefs1)",
      "mode 2 (tweakdefs1)",
      "supreme scamus (tweakdefs1)",
      "scav hell custom (tweakdefs1)",
      "broes spare mode (tweakdefs1)",
      "Marks scav hell (tweakdefs1)",
      "tetris scav mode (tweakdefs1)",
      "scavs custom (tweakdefs1)",
      "BACK UP SAVE SCAV ZOMBIES (tweakdefs1)",
      "raptor fort latest (tweakdefs1)",
      "mark tweaks testing (tweakdefs1)",
      "All in or die (tweakdefs1)",
      "latest waffles (tweakdefs1)",
      "Marks epic scav zombies t4 (tweakdefs1)",
      "tweaks (tweakdefs1)",
      "scav hell (tweakdefs1)",
      "epic scav zombies (tweakdefs1)",
      "tetris raptor (tweakdefs1)",
      "SCAV ZOMBIES (tweakdefs1)",
      "Marks latest scav zombies (tweakdefs1)",
      "testy (tweakdefs1)",
      "tetris scav mode + custom buildings (tweakdefs1)",
      "mark magic (tweakdefs1)",
      "mark magic 1 (tweakdefs1)",
      "mark magic 2 (tweakdefs1)",
      "mark magic unranked test (tweakdefs1)",
      "mark magic 3 (tweakdefs1)",
      "mark magic 4 (tweakdefs1)",
      "mark magic 5 (tweakdefs1)",
      "mark magic 7 (tweakdefs1)",
      "mark magic 8 (tweakdefs1)",
      "mark magic 9 (tweakdefs1)",
      "mark magic 10 (tweakdefs1)"
    ],
    "presetCount": 36
  }
];
