-- FiendishDevil -- content pulled from public BAR replays (bar-replay-miner global scan, 2026-08-15)
-- 4 distinct snippet(s), 34 total occurrences across scanned games

-- === "--mod by FiendishDevil" (seen 24x) ===
--mod by FiendishDevil
{

legstarfall = {firestate=2,},
armvulc= {firestate=2,},
corbuzz= {firestate=2,},

  armaca = {
	buildoptions = {
		[36] = "armnanotct2",
		[37] = "armlwall",
		[38] = "armwint2",
		[39] = "armshockwave",
		
	},
},
  armacv = {
	buildoptions = {
		[33] = "armnanotct2",
		[34] = "armlwall",
		[35] = "armwint2",
		[36] = "armshockwave",
	},
},
  armack = {
	buildoptions = {
		[33] = "armnanotct2",
		[34] = "armlwall",
		[35] = "armwint2",
		[36] = "armshockwave",
	},

},


  coraca = {
	buildoptions = {
		[35] = "cornanotct2",
		[36] = "corhllllt",
		[37] = "cormwall",
		[38] = "corwint2",
	},
},
  coracv = {
	buildoptions = {
		[32] = "cornanotct2",
		[33] = "corhllllt",
		[34] = "cormwall",
		[35] = "corwint2",
	},
},
  corack = {
	buildoptions = {
		[32] = "cornanotct2",
		[33] = "corhllllt",
		[34] = "cormwall",
		[35] = "corwint2",
	},

},
  legaca = {
	buildoptions = {
			"legfus",
			"legafus",
			"legageo",
			"leganavaladvgeo",
			"legrampart",
			"legmoho",
			"legadveconv",
			"legadvestore",
			"legamstor",
			"legarad",
			"legajam",
			"legforti",
			"legtarg",
			"legsd",
			"legdeflector",
			"legacluster",
			"legapopupdef",
			"legbastion",
			"legflak",
			"leglraa",
			"legperdition",
			"legabm",
			"legsilo",
			"leglrpc",
			"legstarfall",
			"legap",
			"legaap",
			"legsplab",
			"leggant",
		"legnanotct2",
		"legrwall",
"legmohocon",
"legwint2",
	},
},
  legacv = {
	buildoptions = {
			"legfus",
			"legafus",
			"leggant",
			"legageo",
			"legrampart",
			"legmoho",
			"legadveconv",
			"legadvestore",
			"legamstor",
			"legarad",
			"legajam",
			"legforti",
			"legtarg",
			"legsd",
			"legdeflector",
			"legacluster",
			"legapopupdef",
			"legbastion",
			"legflak",
			"leglraa",
			"legperdition",
			"legabm",
			"legsilo",
			"leglrpc",
			"legstarfall",
			"legvp",
			"legavp",
		"legnanotct2",
		"legrwall",
"legmohocon",
"legwint2",
	},
},
  legack = {
	buildoptions = {
			"legfus",
			"legafus",
			"leggant",
			"legageo",
			"legrampart",
			"legmoho",
			"legadveconv",
			"legadvestore",
			"legamstor",
			"legarad",
			"legajam",
			"legforti",
			"legtarg",
			"legsd",
			"legdeflector",
			"legacluster",
			"legapopupdef",
			"legbastion",
			"legflak",
			"leglraa",
			"legperdition",
			"legabm",
			"legsilo",
			"leglrpc",
			"legstarfall",
			"leglab",
			"legalab",
		"legnanotct2",
		"legrwall",
"legmohocon",
"legwint2",
	},
},
armacsub= {buildoptions={
[110]="armnanotc2plat",},},
coracsub = {buildoptions={
[110]="cornanotc2plat",},},
leganavyconsub = {buildoptions={
[110]="legnanotct2plat",},},
coravp = {buildoptions={
[110]="corprinter",},},
legavp = {buildoptions={
[110]="legafcv",},},
armaap = {buildoptions={
[110]="armfify",},},
leggant = {buildoptions={
[110]="legpede",[111]="legbunk",},},
armasy= {buildoptions={
[110]="armexcalibur",[111]="armseadragon",},},
corasy  = {buildoptions={
[110]="corprince",[111]="coresuppt3",[112]="coronager",[113]="cordesolator",},},
			
legpede = {movementclass =

-- === "--Nuke mod by FiendishDevil" (seen 7x) ===
--Nuke mod by FiendishDevil
{
corsilo = {
		customparams = {
    			i18n_en_tooltip = 'Cluster Nuke ICBM Launcher',
		},
		weapondefs = {
			crblmssl = {
				areaofeffect = 1000,
				craterareaofeffect = 1000,
				customparams = {
					cluster_def = 'nuke_cluster',
					cluster_number = 4,
				},
				damage = {
					commanders = 2500,
					default = 11500,
				},
			},
			nuclear_launch = {
				areaofeffect = 0,
				avoidfeature = false,
				avoidfriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				impulsefactor = 0,
				metalpershot = 0,
				name = "Nuclear Launch",
				range = 0,
				reloadtime = 30,
				soundhit = "nukelaunchalarm",
				soundhitvolume = 50,
				tolerance = 10000,
				turnrate = 10000,
				weaponacceleration = 101,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 100,
				damage = {
					default = 0,
				},
			},
			nuke_cluster = {
				areaofeffect = 350,
				avoidfeature = false,
				cegtag = "ministarfire",
				craterareaofeffect = 350,
				craterboost = 2.4,
				cratermult = 1.2,
				edgeeffectiveness = 0.45,
				explosiongenerator = "custom:newnuketac",
				gravityaffected = "false",
				impulsefactor = 0.5,
				name = "Cluster Nuke",
				noselfdamage = true,
				range = 750,
				rgbcolor = "0.7 0.7 1.0 1.0 1.0 1.0 1.0 1.0",
				soundhit = "xplomed4",
				soundhitwet = "splsmed",
				soundstart = "cannhvy2",
				weapontype = "Cannon",
				damage = {
					default = 5250,
				},
			},

		},
		weapons = {
			[1] = {
				def = "CRBLMSSL",
				onlytargetcategory = "NOTSUB",
			},
			[2] = {
				def = "NUCLEAR_LAUNCH",
				onlytargetcategory = "NOTSUB",
			},
			[3] = {
				def = "NUKE_CLUSTER",
				onlytargetcategory = "NOTSUB",
			},
		},
	},
legsilo = {
		customparams = {
    			i18n_en_tooltip = 'Nuclear Napalm ICBM Launcher',
		},
		weapondefs = {
			legicbm = {
				cegtag = "burnflame",
				colormap = "0.75 0.73 0.67 0.024   0.37 0.4 0.30 0.021   0.22 0.21 0.14 0.018  0.024 0.014 0.009 0.03   0.0 0.0 0.0 0.008",
				rgbcolor = ".17 0.98 0.11",
				flamegfxtime = 1,
				customparams = {
					area_onhit_ceg = "fire-area-1000-repeat",
					area_onhit_damageCeg = "burnflamexl-gen",
					area_onhit_resistance = "fire",
					area_onhit_damage = 500,
					area_onhit_range = 1000,
					area_onhit_time = 30,
				},
				damage = {
					commanders = 1500,
					default = 5500,
				},
			},
			nuclear_launch = {
				areaofeffect = 0,
				avoidfeature = false,
				avoidfriendly = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0,
				impulsefactor = 0,
				metalpershot = 0,
				name = "Nuclear Launch",
				range = 0,
				reloadtime = 30,
				soundhit = "nukelaunchalarm",
				soundhitvolume = 50,
				tolerance = 10000,
				turnrate = 10000,
				weaponacceleration = 101,
				weapontimer = 0.1,
				weapontype = "Cannon",
				weaponvelocity = 100,
				damage = {
					default = 0,
				},
			},
		},
		weapons = {
			[1] = {
				def

-- === "--T3mex mod by FiendishDevil" (seen 2x) ===
--T3mex mod by FiendishDevil

local a,b,c=UnitDefs,table.merge,table.copy;

a.t3mex= {
		name="Cold Fusion Metal Extractor",
		description="Metal Extractor / Storage",
		maxacc = 0,
		activatewhenbuilt = true,
		maxdec = 0,
		buildangle = 2048,
		energycost = 24300,
		metalcost = 1920,
		buildpic = "scavengers/scavsafeareabeacon.DDS",
		buildtime = 42300,
		canrepeat = false,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "70 40 70",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energyupkeep = -600,
		explodeas = "geo",
		extractsmetal = 0.012,
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		health = 11700,
		maxslope = 30,
		maxwaterdepth = 20,
		metalstorage = 7200,
		objectname = "scavs/scavsafeareabeacon.s3o",
		script = "Units/ARMEYES.cob",
		onoffable = true,
		seismicsignature = 0,
		selfdestructas = "geo",
		sightdistance = 273,
		yardmap = "h oooooooo osssssso osssssso ossoosso ossoosso osssssso osssssso oooooooo",
		customparams = {
			i18n_en_humanname="Cold Fusion Metal Extractor",
			i18n_en_tooltip="Metal Extractor / Storage",
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/legmoho_aoplane.dds",
			buildinggrounddecalsizey = 9,
			buildinggrounddecalsizex = 9,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'metal',
			cvbuildable = true,
			metal_extractor = 12,
			normaltex = "unittextures/leg_normal.dds",
			removestop = true,
			removewait = true,
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 0.0263531005859 -0.0",
				collisionvolumescales = "85.8415527344 30.0151062012 74.3409423828",
				collisionvolumetype = "Box",
				damage = 2100,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 20,
				metal = 1274,
				object = "Units/freefusion_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 1050,
				footprintx = 5,
				footprintz = 5,
				height = 4,
				metal = 509,
				object = "Units/cor5X5A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			activate = "mohorun2",
			canceldestruct = "cancel2",
			deactivate = "mohooff2",
			underattack = "warning1",
			working = "mohorun2",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "twractv3",
			},
			select = {
				[1] = "mohoon2",
			},
		},
	}
a.t3arm = {
		name="Construction Assembly T3 General Interface Rapid Laborer",
		description="Tech 3 Constructor",
		builddistance = 136,
		builder = true,
		buildpic = "scavengers/SCAVBEACON.DDS",
		buildtime = 19000,
		canmove = true,
		collisionvolumeoffsets = "0 0 0",
		collisionvolumescales = "27 35 23",
		collisionvolumetype = "box",
		corpse = "DEA

-- === "--Catgirl mod by FiendishDevil" (seen 1x) ===
--Catgirl mod by FiendishDevil

local a,b,c=UnitDefs,table.merge,table.copy;

a.t3mex= {
		icontype = "legmex",
		name="Cold Fusion Metal Extractor",
		description="Metal Extractor / Storage",
		maxacc = 0,
		activatewhenbuilt = true,
		maxdec = 0,
		buildangle = 2048,
		energycost = 24300,
		metalcost = 1920,
		buildpic = "scavengers/scavsafeareabeacon.DDS",
		buildtime = 42300,
		canrepeat = false,
		collisionvolumeoffsets = "0 -1 0",
		collisionvolumescales = "70 40 70",
		collisionvolumetype = "CylY",
		corpse = "DEAD",
		energyupkeep = -600,
		explodeas = "geo",
		extractsmetal = 0.016,
		footprintx = 4,
		footprintz = 4,
		idleautoheal = 5,
		idletime = 1800,
		health = 11700,
		maxslope = 30,
		maxwaterdepth = 20,
		metalstorage = 7200,
		objectname = "scavs/scavsafeareabeacon.s3o",
		onoffable = true,
		script = "Units/ARMEYES.cob",
		radardistancejam = 500,
		radardistance = 2100,
		radaremitheight = 72,
		onoffable = true,
		seismicsignature = 0,
		selfdestructas = "geo",
		sightdistance = 273,
		yardmap = "h oooooooo osssssso osssssso ossoosso ossoosso osssssso osssssso oooooooo",
		customparams = {
			i18n_en_humanname="Cold Fusion Metal Extractor",
			i18n_en_tooltip="Metal Extractor / Storage",
			usebuildinggrounddecal = true,
			buildinggrounddecaltype = "decals/legmoho_aoplane.dds",
			buildinggrounddecalsizey = 9,
			buildinggrounddecalsizex = 9,
			buildinggrounddecaldecayspeed = 30,
			unitgroup = 'metal',
			cvbuildable = true,
			metal_extractor = 16,
			normaltex = "unittextures/leg_normal.dds",
			removestop = true,
			removewait = true,
			techlevel = 3,
		},
		featuredefs = {
			dead = {
				blocking = true,
				category = "corpses",
				collisionvolumeoffsets = "0.0 0.0263531005859 -0.0",
				collisionvolumescales = "85.8415527344 30.0151062012 74.3409423828",
				collisionvolumetype = "Box",
				damage = 2100,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 20,
				metal = 1274,
				object = "Units/armmstor_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 1050,
				footprintx = 5,
				footprintz = 5,
				height = 4,
				metal = 509,
				object = "Units/cor5X5A.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			activate = "mohorun2",
			canceldestruct = "cancel2",
			deactivate = "mohooff2",
			underattack = "warning1",
			working = "mohorun2",
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "twractv3",
			},
			select = {
				[1] = "mohoon2",
			},
		},
	}
a.t3arm={icontype = "legck",name="Construction Assembly T3 General Interface Rapid Laborer",description="Tech 3 Constructor",activatewhenbuilt=true,builddistance=136,builder=true,buildpic="scavengers/SCAVBEACON.DDS",buildtime=19000,canmove=tr

