// SUPERSEDED (2026-08-16): data.js is now hand-written after actually
// reading each author's real code, not generated by this script. The
// raw credit-comment titles this produced were often garbled
// concatenations of adjacent comments and didn't say what the content
// actually DOES -- user feedback: "it should just show me what the
// content is with a description of what it does". Kept for reference/
// re-running the raw extraction if needed, but data.js should not be
// regenerated from this without manually re-writing the descriptions.
//
// Original purpose: parses bar-replay-miner/global-credits-by-author/*.lua
// into a browsable catalog of real credit-comment titles + occurrence
// counts from the 200k-replay scan.
const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, '..', '..', 'bar-replay-miner', 'global-credits-by-author');
const OUT_FILE = path.join(__dirname, 'data.js');

const HEADER_RE = /^-- (.+?) -- content pulled from public BAR replays.*\n-- (\d+) distinct snippet\(s\), (\d+) total occurrences across scanned games/;
const SNIPPET_START_RE = /^-- === "(.*?)" \(seen (\d+)x\) ===$/gm;

const authors = [];
for (const file of fs.readdirSync(SRC_DIR).filter(f => f.endsWith('.lua'))) {
	const text = fs.readFileSync(path.join(SRC_DIR, file), 'utf8');
	const headerMatch = text.match(HEADER_RE);
	if (!headerMatch) {
		console.warn(`⚠ ${file} doesn't match the expected header format, skipping.`);
		continue;
	}
	const [, authorName, snippetCount, totalOccurrences] = headerMatch;

	const starts = [...text.matchAll(SNIPPET_START_RE)];
	const snippets = starts.map((m, i) => {
		const codeStart = m.index + m[0].length;
		const codeEnd = i + 1 < starts.length ? starts[i + 1].index : text.length;
		return {
			title: m[1],
			occurrences: parseInt(m[2], 10),
			code: text.slice(codeStart, codeEnd).trim(),
		};
	});
	snippets.sort((a, b) => b.occurrences - a.occurrences);

	authors.push({
		author: authorName,
		snippetCount: parseInt(snippetCount, 10),
		totalOccurrences: parseInt(totalOccurrences, 10),
		snippets,
	});
}

authors.sort((a, b) => b.totalOccurrences - a.totalOccurrences);

fs.writeFileSync(OUT_FILE, `window.BEHAVIOR_MODS = ${JSON.stringify(authors, null, 2)};\n`, 'utf8');
console.log(`Wrote ${authors.length} authors, ${authors.reduce((s, a) => s + a.snippets.length, 0)} total snippets, to ${OUT_FILE}`);
authors.forEach(a => console.log(`  ${a.author}: ${a.snippets.length} snippets, ${a.totalOccurrences} occurrences`));
