// Hand-written after actually reading each author's real code in
// bar-replay-miner/global-credits-full/ (not auto-generated from the raw
// credit-comment titles, which were often garbled concatenations of
// adjacent comments -- see build-data.js's old approach, superseded).
// occurrences = how many times this content was seen across the
// 200k-replay global scan, a rough signal of how proven/played it is.
window.BEHAVIOR_MODS = [
	// --- CrossGamer's gadgets (2026-08-17) --- read directly from
	// bar-replay-miner/global-credits/*.lua (real per-gadget credit files,
	// not the replay scan), traced while investigating "MIRV" for the
	// user. Turned out to be 12 distinct gadgets, not the "7" this
	// project had assumed earlier without actually verifying -- that
	// number came from an unread roadmap note, not a real count.
	{
		author: 'CrossGamer',
		title: 'MIRV Nuke',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: "Makes the three factions' Nuke Silos (armsilo/corsilo/legsilo) split their main missile into 6-8 smaller \"MIRV child\" cluster warheads on impact (damage divided by 6-15 depending on which version -- multiple slightly different revisions were found, suggesting it was iterated on over time) instead of one single big hit. Turns a nuke from a pinpoint strike into an area-saturation weapon.",
		verdict: 'Significant nuke rework -- changes nuke tactics from precision to area denial.',
	},
	{
		author: 'CrossGamer',
		title: 'Scavenger Beacon to Nuke Silo',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: 'Converts all 8 tiers of Scavenger loot beacons (the PvE reward buildings) into fully functional nuke silos, cloning the real Nuke Silo\'s weapon onto each one and applying the same MIRV cluster-split as the MIRV Nuke gadget above. Higher-tier beacons get much faster stockpile times (T4 down to 10s vs. the normal ~90s). Also called "Beacon Nuke" in some scans -- same content, found twice under different extracted titles.',
		verdict: 'Turns PvE loot beacons into serious offensive weapons -- major PvE-to-PvP power spike if adopted.',
	},
	{
		author: 'CrossGamer',
		title: 'Anti-Nuke T3 Mod',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: "Creates an upgraded T3 tier of each faction's Anti-Nuke (armamdt3/corfmdt3/legabmt3), cloned from the real T2 version: 2.5x health, 3x cost, double coverage range, stockpile time cut to a third, ~10% cheaper per-shot, capped at 30 stockpiled interceptors. Added to every advanced (T2/T3) constructor's buildoptions.",
		verdict: 'Straightforward tech-tier upgrade for anti-nuke coverage -- low risk.',
	},
	{
		author: 'CrossGamer',
		title: 'Antinuke to ICBM Visuals & Stats',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: "Reworks every anti-nuke interceptor missile's look and feel to resemble a real ICBM (swapped 3D model, exhaust trail effects, launch/impact sounds) plus stat changes (faster, more damage, bigger blast radius, longer stockpile time). Purely cosmetic/flavor plus a moderate stat rebalance layered on top.",
		verdict: 'Mostly visual flavor with a stat tweak riding along -- low risk either way.',
	},
	{
		author: 'CrossGamer',
		title: 'Air T2 Builds Nuke',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: "Adds the Nuke Silo and Anti-Nuke to every faction's T2 advanced air constructor's buildoptions directly, letting you build nukes/anti-nukes straight from an air con instead of needing a dedicated ground constructor first.",
		verdict: 'Small QoL accessibility unlock for nuke tech.',
	},
	{
		author: 'CrossGamer',
		title: 'AdvSAM AA Homing Nuke',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: "Turns the Armada Mercury and Cortex Screamer (advanced AA missile units) into tactical homing nukes -- their SAM missile gets a massive turnrate boost (near-perfect tracking), 15,000 damage (also to VTOL), a big area-of-effect, and the engine's nuclear flag. The launcher unit itself also gets much more expensive (6,500 metal, 90,000 energy, 150,000 buildtime) to match.",
		verdict: 'Major single-unit power spike -- effectively a mobile, homing tactical nuke launcher.',
	},
	{
		author: 'CrossGamer',
		title: 'Portable Shield',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: 'Converts one specific mobile unit per faction (Armada Croc, Cortex Salamander, Legion Floating tank) into a "Mobile Shield" -- disables its weapon entirely and gives it a large personal deflector shield instead (6,175 shield power, 550 radius), at increased cost. A genuinely mobile, deployable shield generator.',
		verdict: 'Interesting tactical tool -- a shield that can reposition, unlike stock static shield generators.',
	},
	{
		author: 'CrossGamer',
		title: 'Knockback',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: "Global weapon rework: normalizes every weapon's damage-per-second down (the higher a weapon's DPS, the more its raw damage gets reduced) while massively increasing physical knockback/impulse and crater size on every hit. Also makes all non-flying units affected by gravity with fall damage. The net effect: fights look and feel much more physical/chaotic (units get sent flying) without proportionally changing time-to-kill.",
		verdict: 'Big feel/chaos change to combat -- not a small tweak, changes how every fight looks.',
	},
	{
		author: 'CrossGamer',
		title: 'Chain Lightning',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: "Adds a small lightning-arc spark effect to every weapon in the game that doesn't already have one (skips shields) -- each hit has a chance to fork a small amount of extra damage (10% of the original) to nearby enemies within 120 range, hitting up to 8 units.",
		verdict: 'Universal minor AoE-splash addition -- affects every weapon in the game, so test for balance before committing.',
	},
	{
		author: 'CrossGamer',
		title: 'No Dgun',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: 'Strips the D-Gun (disintegrator special weapon) from every commander-type unit (detected via customparams.iscommander, isdecoycommander, or a "COMMANDER" movement class) -- removes the weapon slot and its weapondef entirely rather than just disabling it.',
		verdict: 'Simple, contained removal -- meaningfully changes commander-vs-commander dueling since D-Gun is normally a key defensive tool.',
	},
	{
		author: 'CrossGamer',
		title: 'Flying Tanks & Walking Planes Mod',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: 'A large curated list of specific ground vehicles (Flash, Stumpy, Bulldog, Thor, and dozens more per faction) get flight capability, while a large curated list of specific aircraft (fighters, bombers, gunships, and more per faction) get grounded into walking/hovering units instead. A hand-picked swap, not a blanket rule.',
		verdict: 'Wild, chaotic gameplay-inversion mod -- fun/novelty territory, not balance-focused.',
	},
	{
		author: 'CrossGamer',
		title: 'Gravity Inversion Mod',
		occurrences: null,
		source: '200k-replay scan (global-credits)',
		description: 'A blanket version of the same idea as Flying Tanks above: EVERY flying unit in the game becomes a ground unit, and every ground unit with a movement class becomes a flying unit -- applied universally via a rule (not a curated list), with commanders/bosses explicitly excluded. Looks like a broader evolution of the Flying Tanks mod\'s hand-picked approach.',
		verdict: 'Same idea as Flying Tanks but applied to the whole game automatically -- pick one, not both (they\'d conflict).',
	},
	{
		author: 'Bezz',
		title: 'T3 Commander & Army Overhaul',
		occurrences: 1308,
		description: "The single most-played piece of custom content found in the entire scan. Transforms your commander into a near-unkillable T3 combat monster cloned from a Raptor boss unit (Armada's Bantha / Cortex's Kortog / Legion's Heat Ray Mech): 85,000-145,000 HP, 2.3-2.45x weapon damage, full long-range detection (sight/radar/sonar/cloak all maxed), and it can no longer build anything -- pure combat unit. Also globally rebalances the entire unit roster: regular units get 8.5x HP (defense buildings 8x, heavy units 2.8x, siege units 5x, other buildings 5.5x), 2-3.6x damage scaling by category, static AA gets faster reload plus bonus damage, nukes get +50% damage, and defense buildings hit commanders 2.1x harder specifically. Also includes a separate barbarian-AI balance patch (caps T1 army size, halves T1 unit HP vs BARb AI). This is a total-conversion-style rebalance, not a small tweak -- expect very different pacing if used.",
		verdict: 'Major, high-impact. Changes core game balance for every unit, not just commanders.',
	},
	{
		author: 'LoH',
		title: 'BaRandom',
		occurrences: 807,
		description: 'Every unit and building in the game gets a random rarity tier rolled (Common through joke-tier names like "GOD" and "Beyond All Reason") with tier-scaled stat boosts to power/HP/sight/radar. Units also get a random archetype reshaping their whole stat profile -- Glass Cannon, Tank, Sniper, or Brawler for mobile units; Fortress, Watchtower, or Suppressor for buildings -- plus flavor "mutations" per role (a Metal Extractor might roll "Deep Bore" or "Volatile Vein", an energy plant might roll "Surge" or "Efficient Core"). Every unit gets renamed in the build menu with its rolled rarity tag in brackets. Essentially an ARPG loot-rarity system laid over the entire BAR tech tree.',
		verdict: 'Fun/chaos mode, not competitive balance. Every game is a different random loadout.',
	},
	{
		author: 'Ambo',
		title: 'Random Rarities',
		occurrences: 210,
		description: 'Same rarity-randomizer concept as LoH\'s BaRandom -- its own file credits "Special thanks to MGGW" and shares near-identical code structure, so this reads as a close sibling/derivative rather than independent design. If you want this style of mod, BaRandom (LoH, above) is the more-played original.',
		verdict: 'Redundant with BaRandom unless you specifically prefer this version\'s tuning.',
	},
	{
		author: 'MGGW',
		title: 'Quad Pharos / Lava QoL',
		occurrences: 65,
		description: 'Conditionally unlocks buildoptions (e.g. orbital constructors) based on which modoptions/factions are actually active in the game, plus quality-of-life adjustments specific to lava-tide maps (checks the map\'s lava-tide settings before applying anything). Careful, defensive coding -- checks game state before acting rather than assuming.',
		verdict: 'Low-risk, map/modoption-conditional utility patch.',
	},
	{
		author: 'LordOfHangovers',
		title: 'LavaT3pack (by Djarshi, mislabeled)',
		occurrences: 14,
		description: 'Data-quality note: the file traced to "LordOfHangovers" is actually "LavaT3pack Djarshi v4.11" -- real author is Djarshi, not LordOfHangovers. Adds cross-faction constructor buildoptions themed for lava maps (a taxed cross-faction unlock, similar structure to TetrisCo\'s Cross Faction Tax found in the base Tetris preset).',
		verdict: 'Misattributed by the extraction pipeline -- content itself looks like a legitimate small QoL pack.',
	},
	{
		author: 'onetrick',
		title: 'LavaPack v5.0 (by Djarshi, mislabeled)',
		occurrences: 3,
		description: 'Same misattribution as above -- the file traced to "onetrick" is actually "LavaPack (Djarshi) v5.0". Reads the map\'s "is lava" modoption and conditionally unlocks buildoptions per faction when playing on a lava map.',
		verdict: 'Misattributed by the extraction pipeline -- likely a newer version of the LavaT3pack above.',
	},
	{
		author: 'Djarshi',
		title: 'Correction: not actually Djarshi\'s content',
		occurrences: 6,
		description: 'The file traced to "Djarshi" in this scan is actually a copy of LoH\'s BaRandom (identical code, just different rarity-chance constants) -- not "LavaPack" as an earlier pass of this project assumed. Djarshi\'s real content (LavaT3pack / LavaPack) is correctly attributed above under LordOfHangovers and onetrick, where the author-tracing pipeline actually placed it.',
		verdict: 'Data-quality correction, not a real distinct mod -- see LordOfHangovers/onetrick for Djarshi\'s actual content.',
	},
	{
		author: 'FiendishDevil',
		title: 'T3 Con Buildoption Unlocks',
		occurrences: 34,
		description: 'Adds T2 nanoturret / wall / shockwave-defense buildoptions to T3 air constructors (Armada and Cortex), and sets a few units (legstarfall, armvulc, corbuzz) to auto-fire-at-will by default (firestate=2) instead of requiring a manual order.',
		verdict: 'Small, low-risk QoL unlock -- lets T3 air cons build things they normally can\'t.',
	},
	{
		author: 'Luigi',
		title: 'BaRandom + personal edits',
		occurrences: 1,
		description: 'A personally-edited copy of LoH\'s BaRandom with tweaked rarity-chance constants -- not independent content.',
		verdict: 'Not worth adopting separately from LoH\'s original BaRandom.',
	},
	// --- NuttyB Configurator toggles (2026-08-16) --- the real community
	// tool copied in at bar-toolkit-hub/nuttyb-configurator/. Its actual
	// payload (tweakdata.txt) is 15 real toggles, base64-decoded and read
	// directly -- not from the 200k-replay scan, so `occurrences` is null
	// here (no play-count signal available); `source` distinguishes these.
	{
		author: 'ChrispyNut, BackBash',
		title: 'NuttyB Main Def Tweaks',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: "The core NuttyB PvE-difficulty def file. Adds a new shield weapon (\"repulsor\") that can be attached to any unit via a helper function, reworks Raptor air fighters' weapon into a faster, more accurate \"Spike\" projectile, extends paralyze/EMP duration across many Raptor unit types (kamikaze, swarmers, assault, artillery, bombers, the Matriarch boss), and buffs stats across the full Raptor turret family (acid/antiair/antinuke/basic/burrow/EMP turrets, tiers 2-4). Also disables commander fall damage/paratrooper knockback. This is the file that actually makes NuttyB's raptors dangerous.",
		verdict: 'Core to the NuttyB experience -- this is the actual difficulty increase, not just flavor.',
	},
	{
		author: 'Hedgehogzs',
		title: 'T4 Defences (Legendary Bastion/Bulwark/Pulsar)',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: 'Adds 3 new top-tier defensive buildings -- Legendary Pulsar (cloned from the T3 Annihilator, rapid-fire tachyon bolts), Legendary Bulwark, and Legendary Bastion. The exact same units also turned up independently in Mewi\'s replay-traced content (see the Content Gallery) -- this NuttyB toggle looks like the original/canonical source they were copied from.',
		verdict: 'Already in the Content Gallery as new units (via Mewi) -- this is where they actually come from.',
	},
	{
		author: 'RCore',
		title: 'Mini Bosses',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: "Dynamically scales Raptor mini-boss (Matriarch) and Queen stats based on player count and the game's raptor spawn-count multiplier setting, instead of using fixed numbers -- keeps bosses appropriately threatening whether you're playing solo or in a large team game.",
		verdict: 'Adaptive difficulty scaling -- useful if you play with varying player counts.',
	},
	{
		author: 'TetrisCo',
		title: 'Cross Faction Tax 70%',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: 'Unlocks every faction\'s T2 factory/lab buildoptions for the other two factions, at a 70% cost markup (renamed with a "(Taxed)" suffix so it\'s visible in the build menu). This is the exact same mod already wired into the base "Tetris scav mode"/"Tetris stable" preset this project has used all along -- confirms it\'s a genuinely shared, widely-adopted piece of community content, not unique to either source.',
		verdict: 'Already effectively in use -- this is the same Cross Faction Tax already in your current presets.',
	},
	{
		author: 'NuttyB (uncredited toggle)',
		title: 'T3 Eco Builtin v6',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: 'Adds T3 Advanced Fusion Reactor and Advanced Energy Converter buildoptions to every faction\'s T3 constructors (bot/vehicle/air), and widens the T3 converter buildings\' footprint to fit. Conceptually similar territory to this project\'s own Bio-Reactor/Scav Recycler con-tier wiring, just targeting the stock Advanced Fusion/Converter buildings instead.',
		verdict: 'Straightforward, low-risk economy QoL unlock.',
	},
	{
		author: 'Nervensaege, TetrisCo',
		title: 'T3 Cons & Taxed Factories',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: "Upgrades each faction's T2 nanoturret-style assist buildings into real T3 constructor variants with adjusted cost/stats, and unlocks taxed cross-faction factory access (same tax pattern as TetrisCo's Cross Faction Tax above).",
		verdict: 'Overlaps partly with Cross Faction Tax -- check for conflicts before combining both.',
	},
	{
		author: 'NuttyB (uncredited toggle)',
		title: 'Unit Launchers ("Meatballlunch Reloaded")',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: 'Adds two new stockpiled ordinance variants to the Pawn Launcher weapon (armbotrail) -- "Meatball Launcher" and "Assimilator Launcher" -- both far higher range/cost/damage than the stock shell. Note: this modifies the exact same weapon (armbotrail\'s arm_botrail) that this project\'s own Depawner interceptor targets -- worth checking compatibility before combining.',
		verdict: 'Compatibility risk: touches the same weapon our Depawner intercepts. Test together before combining.',
	},
	{
		author: 'ChrispyNut, BackBash',
		title: 'NuttyB Main Unit Tweaks',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: 'Broad base-game balance/QoL pass at the individual-unit level: buffs the Cortex Tremor (cortron) raptor-adjacent unit\'s stats and weapon damage, makes all 3 factions\' forts repairable (normally they aren\'t), and changes gate units to explode as an EMP blast instead of their default explosion.',
		verdict: 'Small assorted balance/QoL fixes, low risk individually.',
	},
	{
		author: 'ChrispyNut, BackBash',
		title: 'NuttyB Evolving Commander (Armada / Cortex / Legion)',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: "NuttyB's own commander-progression system, one toggle per faction: buffs the starting commander's stats (health/energymake/metalmake/autoheal/speed), grants extra starting buildoptions immediately (no waiting), reworks the commander's main weapon, and sets the commander to automatically evolve into its next level on a fixed timer (420 seconds) rather than through gameplay milestones. Conceptually similar territory to this project's own Commander Progression Chain, but a different implementation -- NuttyB buffs the single evolving commander in place on a timer, our system creates 10 separate rank units the real commander unlocks one at a time.",
		verdict: 'Direct alternative to our own Commander Progression Chain -- pick one, not both, to avoid conflicting commander overrides.',
	},
	{
		author: 'BackBash',
		title: 'Experimental Wave Challenge',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: 'Configures Raptor "squad" spawn behavior -- groups specific Raptor unit types into coordinated squads (with set unit counts, anger-tier ranges, rarity, and raider/aggression behavior chance) instead of every Raptor spawning and acting independently. Makes waves feel like coordinated attacks rather than a scattered mob.',
		verdict: 'Meaningfully changes wave feel/difficulty -- experimental per its own name, worth testing before committing to it.',
	},
	{
		author: 'NuttyB (uncredited toggle)',
		title: 'LRPC Rebalance v2',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: "Rebalances all 3 factions' Long Range Plasma Cannons (armbrtha/corint/leglrpc) -- more health, and adjusted damage/range/reload per weapon, making them tankier and more effective siege weapons.",
		verdict: 'Simple, contained stat rebalance -- low risk.',
	},
	{
		author: 'BackBash',
		title: 'T4 Air Rework',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: 'Reworks a T4 air unit (legfortt4, renamed "Experimental Tyrannus" as a tribute to a community member) with adjusted weapon behavior on its machine-gun-style weapon.',
		verdict: 'Narrow, single-unit rework -- low risk, low impact outside that specific unit.',
	},
	{
		author: 'NuttyB (uncredited toggle)',
		title: 'Mega Nuke',
		source: 'NuttyB Configurator',
		occurrences: null,
		description: 'Massively increases the Nuclear Missile Silo\'s cost and caps it at 1 per player (maxthisunit=1), while making the nuke itself far more powerful (bigger blast radius, more damage). Turns nukes from a spammable mid-game tool into a single rare, decisive endgame weapon.',
		verdict: 'Significant pacing change -- makes nukes a once-per-game event rather than a repeatable tool.',
	},
];
