// Scav Spawn Pool Editor — vanilla JS, no build step, no server needed.
// Loads window.SCAV_POOLS / SCAV_FULL_TEXT / SCAV_BLOCK_RANGES from data.js
// (generated by tools/build-data.js from the real game file), lets you edit
// unit weights per Domain/Role/Tier, add new units, and export a complete,
// drop-in-ready replacement scav_spawn_defs.lua.

const STORAGE_KEY = 'bar-scav-editor-state-v1';

const DOMAIN_LABELS = {
	LandUnitsList: 'Land',
	SeaUnitsList: 'Sea',
	AirUnitsList: 'Air',
};

let state = null; // deep-cloned, editable copy of SCAV_POOLS
let selection = { domain: null, role: null, tier: null };

function loadState() {
	const saved = localStorage.getItem(STORAGE_KEY);
	if (saved) {
		try {
			return JSON.parse(saved);
		} catch (e) {
			console.warn('Failed to parse saved state, starting fresh.', e);
		}
	}
	return JSON.parse(JSON.stringify(window.SCAV_POOLS));
}

function saveState() {
	localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
}

function resetState() {
	if (!confirm('Discard all your edits and reload the original spawn pools?')) return;
	localStorage.removeItem(STORAGE_KEY);
	state = JSON.parse(JSON.stringify(window.SCAV_POOLS));
	selection = { domain: null, role: null, tier: null };
	render();
}

function countUnits(pools) {
	let n = 0;
	for (const domain of Object.values(pools)) {
		for (const role of Object.values(domain)) {
			for (const tier of Object.values(role)) n += Object.keys(tier).length;
		}
	}
	return n;
}

function el(tag, attrs = {}, children = []) {
	const node = document.createElement(tag);
	for (const [k, v] of Object.entries(attrs)) {
		if (k === 'class') node.className = v;
		else if (k === 'text') node.textContent = v;
		else if (k.startsWith('on') && typeof v === 'function') node.addEventListener(k.slice(2), v);
		else node.setAttribute(k, v);
	}
	for (const c of [].concat(children)) {
		if (c == null) continue;
		node.appendChild(typeof c === 'string' ? document.createTextNode(c) : c);
	}
	return node;
}

function renderNav() {
	const nav = document.getElementById('nav');
	nav.innerHTML = '';
	for (const domain of Object.keys(state)) {
		const domainNode = el('div', { class: 'nav-domain' }, [
			el('div', { class: 'nav-domain-label', text: DOMAIN_LABELS[domain] || domain }),
		]);
		for (const role of Object.keys(state[domain])) {
			const roleNode = el('div', { class: 'nav-role', text: role });
			const tierList = el('div', { class: 'nav-tiers' });
			const tierKeys = Object.keys(state[domain][role]).sort((a, b) => +a - +b);
			for (const tier of tierKeys) {
				const count = Object.keys(state[domain][role][tier]).length;
				const isActive = selection.domain === domain && selection.role === role && selection.tier === tier;
				const btn = el('button', {
					class: 'tier-btn' + (isActive ? ' active' : ''),
					text: `T${tier} (${count})`,
					onclick: () => { selection = { domain, role, tier }; render(); },
				});
				tierList.appendChild(btn);
			}
			domainNode.appendChild(roleNode);
			domainNode.appendChild(tierList);
		}
		nav.appendChild(domainNode);
	}
}

function renderEditor() {
	const editor = document.getElementById('editor');
	editor.innerHTML = '';
	const { domain, role, tier } = selection;
	if (!domain) {
		editor.appendChild(el('p', { class: 'hint', text: 'Pick a domain / role / tier on the left to edit its unit pool.' }));
		return;
	}
	const units = state[domain][role][tier];
	const title = el('h2', { text: `${DOMAIN_LABELS[domain] || domain} — ${role} — Tier ${tier}` });
	editor.appendChild(title);
	editor.appendChild(el('p', { class: 'hint', text: 'Weight = relative spawn frequency within this tier/role. Add any *_scav unit id to widen variety.' }));

	const table = el('table', { class: 'unit-table' });
	const thead = el('thead', {}, el('tr', {}, [
		el('th', { text: 'Unit ID' }), el('th', { text: 'Weight' }), el('th', { text: '' }),
	]));
	table.appendChild(thead);
	const tbody = el('tbody');
	for (const unitId of Object.keys(units).sort()) {
		const row = el('tr');
		row.appendChild(el('td', { class: 'unit-id', text: unitId }));
		const weightInput = el('input', {
			type: 'number', min: '0', step: '0.5', value: String(units[unitId]),
			onchange: (e) => {
				const v = parseFloat(e.target.value);
				units[unitId] = isNaN(v) ? 0 : v;
				saveState();
				renderNav();
			},
		});
		row.appendChild(el('td', {}, weightInput));
		row.appendChild(el('td', {}, el('button', {
			class: 'btn-remove', text: '✕',
			onclick: () => { delete units[unitId]; saveState(); render(); },
		})));
		tbody.appendChild(row);
	}
	table.appendChild(tbody);
	editor.appendChild(table);

	const addRow = el('div', { class: 'add-row' });
	const idInput = el('input', { type: 'text', placeholder: 'e.g. armzeus_scav', class: 'add-id' });
	const weightInput = el('input', { type: 'number', min: '0', step: '0.5', value: '3', class: 'add-weight' });
	const addBtn = el('button', {
		text: '+ Add unit', class: 'btn-add',
		onclick: () => {
			const id = idInput.value.trim();
			if (!id) return;
			if (!id.endsWith('_scav')) {
				if (!confirm(`"${id}" doesn't end in "_scav" — the scav unit variant may not exist under that exact name. Add anyway?`)) return;
			}
			const w = parseFloat(weightInput.value) || 1;
			units[id] = w;
			idInput.value = '';
			saveState();
			render();
		},
	});
	addRow.appendChild(idInput);
	addRow.appendChild(weightInput);
	addRow.appendChild(addBtn);
	editor.appendChild(addRow);
}

function render() {
	renderNav();
	renderEditor();
	document.getElementById('total-count').textContent = countUnits(state);
	document.getElementById('original-count').textContent = countUnits(window.SCAV_POOLS);
}

// ---- Lua serialization / export ----

function serializePoolBlock(poolsForList) {
	let out = '{\n';
	for (const role of Object.keys(poolsForList)) {
		out += `\t${role} = {\n`;
		const tierKeys = Object.keys(poolsForList[role]).sort((a, b) => +a - +b);
		for (const tier of tierKeys) {
			const units = poolsForList[role][tier];
			out += `\t\t[${tier}] = {\n`;
			for (const unitId of Object.keys(units)) {
				out += `\t\t\t${unitId} = ${units[unitId]},\n`;
			}
			out += `\t\t},\n`;
		}
		out += `\t},\n`;
	}
	out += '}';
	return out;
}

function buildFullLuaFile() {
	const ranges = window.SCAV_BLOCK_RANGES;
	const fullText = window.SCAV_FULL_TEXT;
	// Splice all three domain blocks back into the original file, in source order.
	const domains = Object.keys(ranges).sort((a, b) => ranges[a].start - ranges[b].start);
	let result = '';
	let cursor = 0;
	for (const domain of domains) {
		const { start, end } = ranges[domain];
		result += fullText.slice(cursor, start);
		result += `local ${domain} = ${serializePoolBlock(state[domain])}`;
		cursor = end;
	}
	result += fullText.slice(cursor);
	return result;
}

function downloadFile(filename, text) {
	const blob = new Blob([text], { type: 'text/plain' });
	const url = URL.createObjectURL(blob);
	const a = el('a', { href: url, download: filename });
	document.body.appendChild(a);
	a.click();
	document.body.removeChild(a);
	URL.revokeObjectURL(url);
}

function exportFile() {
	const text = buildFullLuaFile();
	downloadFile('scav_spawn_defs.lua', text);
}

function previewDiff() {
	const modal = document.getElementById('preview-modal');
	const pre = document.getElementById('preview-text');
	pre.textContent = buildFullLuaFile();
	modal.classList.remove('hidden');
}

function closePreview() {
	document.getElementById('preview-modal').classList.add('hidden');
}

window.addEventListener('DOMContentLoaded', () => {
	state = loadState();
	render();
	document.getElementById('btn-reset').addEventListener('click', resetState);
	document.getElementById('btn-export').addEventListener('click', exportFile);
	document.getElementById('btn-preview').addEventListener('click', previewDiff);
	document.getElementById('btn-close-preview').addEventListener('click', closePreview);
});
